Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2022-10, with the labels that each got.

#94 chore: ESLint 적용 범위 수정
  constants/Config.ts
  hooks/useLocalLogin.ts
  hooks/useMediaQuery.ts
  next.config.js
  styles/GlobalStyle.tsx
  styles/font.ts
  styles/global.ts
  utils/index.ts
  utils/layout.tsx
Labels: 🐛 Bug

#86 프로젝트 업로드 폼 자잘한 버그 fix
  components/common/Input/index.tsx
  components/common/TextArea/index.tsx
  components/common/form/RHFControllerFormItem.tsx
Labels: 🐛 Bug, 🏃🏻‍♀️Sprint 1

#89 refactor: 액세스 토큰 관리 구조 변경
  components/auth/AuthProvider.tsx
  components/auth/AuthRequired.tsx
  components/auth/accessToken.ts
  components/auth/identityProvider/useFacebookAuth.ts
  components/auth/states/accessTokenAtom.ts
  components/auth/useAuth.ts
  components/auth/util/accessToken.ts
  components/auth/util/useStateParam.ts
  pages/_app.tsx
  pages/auth/callback/facebook/login.tsx
  pages/auth/callback/facebook/register.tsx
  utils/index.ts
Labels: 🏃🏻‍♀️Sprint 1

#100 chore: 바뀐 색상 코드 적용
  styles/colors.ts
Labels: 🏃🏻‍♀️Sprint 1
