Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2022-11, with the labels that each got.

#105 Feat/#96 멤버 상세 페이지 마크업
  .vscode/settings.json
  .yarn/install-state.gz
  components/common/MobileHeader/index.tsx
  components/projects/main/ProjectCard.stories.tsx
  components/projects/main/ProjectCard.tsx
  components/projects/upload/ProjectMemebers.tsx
  components/projects/upload/ProjectReleaseMembers.tsx
  components/projects/upload/SignupLink/SignupLink.stories.tsx
  components/projects/upload/SignupLink/index.tsx
  components/projects/upload/ToastProvider/ToastWithSignupLink.stories.tsx
  components/users/detail/InfoItem.tsx
  components/users/detail/PartItem.tsx
  components/users/detail/UserProjectCard.tsx
  pages/members/index.tsx
  pages/projects/[projectId]/index.tsx
  pages/projects/index.tsx
  pages/users/[userId]/index.tsx
  pages/users/index.tsx
  public/icons/icon-add.svg
  public/icons/icon-back.svg
  public/icons/icon-call.svg
  public/icons/icon-edit.svg
  public/icons/icon-link.svg
  public/icons/icon-mail.svg
Labels: ✨ Feature, 🏃🏻‍♀️Sprint 1

#116 fix: import 에러 수정
  components/projects/upload/SignUpLink/SignUpLink.stories.tsx
  components/projects/upload/SignUpLink/index.tsx
  components/projects/upload/SignupLink/SignupLink.stories.tsx
Labels: ⚡️ Urgent

#123 fix: import error fix
  components/users/detail/PartItem.tsx
  pages/auth/register.tsx
  pages/members/[memberId]/index.tsx
Labels: 🐛 Bug

#120 feat: 프로필 업로드 폼 UI 기능 구현 및 react-hook-form 붙이기
  components/members/upload/AddableItem.tsx
  components/members/upload/AddableWrapper.tsx
  components/members/upload/AdditionalInfoFormSection.tsx
  components/members/upload/BasicFormSection.tsx
  components/members/upload/PublicQuestionFormSection.tsx
  components/members/upload/SoptActivityFormSection.tsx
  components/members/upload/constants.ts
  components/members/upload/forms/CountableInput.tsx
  components/members/upload/forms/CountableTextArea.tsx
  components/members/upload/forms/SelectOptions.tsx
  components/members/upload/types.ts
  components/projects/upload/constants.ts
  pages/members/upload.tsx
Labels: ✨ Feature, 🏃🏻‍♀️Sprint 1

#137 feat: 메인페이지로 접속 시 member 페이지로 redirect
  pages/index.tsx
Labels: 🏃🏻‍♀️Sprint 1

#130 feat: 로그인 오류 메시지 고도화
  components/auth/identityProvider/useFacebookAuth.ts
  components/auth/useQueryString.ts
  components/auth/useStringRouterQuery.tsx
  pages/auth/callback/facebook/login.tsx
Labels: 🏃🏻‍♀️Sprint 1

#143 fix: 배포 시 동적 라우팅 404 에러 임시 fix
  components/common/Header/index.tsx
  pages/members/detail.tsx
  pages/members/index.tsx
  pages/projects/detail.tsx
  pages/projects/index.tsx
Labels: 🐛 Bug, 🏃🏻‍♀️Sprint 1, ⚡️ Urgent

#139 feat: 프로필 업로드 POST api 연결
  api/image/index.ts
  api/members/index.ts
  api/members/type.ts
  components/common/ImageUploader/index.tsx
  components/members/upload/AdditionalInfoFormSection.tsx
  components/members/upload/SoptActivityFormSection.tsx
  components/members/upload/constants.ts
  components/projects/upload/SignUpLink/SignUpLink.stories.tsx
  pages/members/upload.tsx
Labels: ✨ Feature, 🏃🏻‍♀️Sprint 1

#135 feat: 이메일 인증 오류 시 구글폼 연결 안내 기능 추가
  components/auth/register/VerifyByEmail.tsx
  public/icons/icon-arrow-right.svg
Labels: ✨ Feature, 🏃🏻‍♀️Sprint 1

#141 fix: 프로필 정보 GET 실패하는 버그
  api/members/index.ts
  apiHooks/members.ts
  components/common/Header/index.tsx
  pages/members/index.tsx
Labels: 🐛 Bug, 🏃🏻‍♀️Sprint 1

#144 fix: 의도대로 동작하지 않는 enabled 옵션 임시 fix
  apiHooks/members.ts
Labels: 🐛 Bug, 🏃🏻‍♀️Sprint 1, ⚡️ Urgent

#147 fix: 이름 옆 전공 대신 파트 정보 뜨도록
  pages/members/detail.tsx
Labels: 🐛 Bug, 🏃🏻‍♀️Sprint 1

#148 chore: 멤버카드 소개 말줄임 추가
  components/members/main/MemberCard/index.stories.tsx
  components/members/main/MemberCard/index.tsx
Labels: 🐛 Bug

#149 chore: 모바일헤더 뒤로가기 추가
  components/common/MobileHeader/index.tsx
Labels: 🐛 Bug

#162 fix: 모바일 뷰에서 한줄소개, 스킬 등록 안되는 버그 fix
  components/common/TextArea/index.tsx
  components/members/upload/AdditionalInfoFormSection.tsx
  components/members/upload/forms/CountableTextArea.tsx
Labels: 🐛 Bug, ⚡️ Urgent

#170 fix: 액세스 토큰 로드 버그 수정
  api/index.ts
  components/auth/states/accessTokenAtom.ts
Labels: ⚡️ Urgent

#165 feat: 프로필 업로드 폼 > 링크 카테고리 select > '직접입력' 옵션 선택 시 편집 가능하도록
  components/common/EditableSelect.tsx
  components/common/Select/index.tsx
  components/members/upload/AddableItem.tsx
  components/members/upload/AdditionalInfoFormSection.tsx
Labels: ✨ Feature

#163 refactor: projects api 변경 대응
  .yarn/install-state.gz
  api/members/index.ts
  api/members/type.ts
  api/project/index.ts
  api/project/types.ts
  api/projects/index.ts
  api/projects/type.ts
  api/user/index.ts
  api/user/types.ts
  apiHooks/members.ts
  components/common/ImageUploader/index.tsx
  components/projects/main/ProjectCard.stories.tsx
  components/projects/main/ProjectCard.tsx
  components/projects/upload/LinkForm/constants.ts
  components/projects/upload/LinkForm/index.tsx
  components/projects/upload/MemberForm/MemberSearch.stories.tsx
  components/projects/upload/MemberForm/MemberSearch.tsx
  components/projects/upload/MemberForm/constants.ts
  components/projects/upload/MemberForm/index.tsx
  components/projects/upload/ProjectStatus.tsx
  components/projects/upload/constants.ts
  components/projects/upload/hooks/useCreateProjectMutation.ts
  components/projects/upload/hooks/useGetMembersByNameQuery.ts
  components/projects/upload/hooks/useGetProjectListQuery.ts
  components/projects/upload/hooks/useGetProjectQuery.ts
  components/projects/upload/hooks/useGetUsersByNameQuery.ts
  components/projects/upload/types.ts
  components/projects/upload/utils.ts
  components/users/detail/UserProjectCard.tsx
  package.json
  pages/projects/detail.tsx
  pages/projects/index.tsx
  pages/projects/upload/index.tsx
  public/icons/icon-appstore.svg
  public/icons/icon-etc.svg
  public/icons/icon-github.svg
  public/icons/icon-googleplay.svg
  public/icons/icon-instagram.svg
  public/icons/icon-media.svg
  public/icons/icon-playstore.svg
  public/icons/icon-web.svg
Labels: 🏃🏻‍♀️Sprint 1, 🛠 Refactor

#173 feat: 프로젝트 업로드 폼 유효성 검사
  api/members/type.ts
  components/common/Text/index.tsx
  components/members/upload/AddableItem.tsx
  components/members/upload/AdditionalInfoFormSection.tsx
  components/members/upload/BasicFormSection.tsx
  components/members/upload/SoptActivityFormSection.tsx
  components/members/upload/constants.ts
  components/members/upload/forms/FormHeader.tsx
  components/members/upload/forms/FormItem.tsx
  components/members/upload/schema.ts
  components/members/upload/types.ts
  pages/members/upload.tsx
  pages/profile/create.tsx
  pages/profile/index.tsx
  public/icons/icon-warning.svg
Labels: ✨ Feature, 🏃🏻‍♀️Sprint 2

#182 fix: 회원가입 성공 route 오류 해결
  pages/auth/callback/facebook/register.tsx
Labels: 🐛 Bug, ⚡️ Urgent

#178 feat: 멤버 상세 및 자잘한 것 수정 & 프로필 수정 구현 #176
  .vscode/settings.json
  components/common/Header/index.tsx
  components/common/ImageUploader/index.tsx
  components/common/MobileHeader/index.tsx
  components/members/upload/BasicFormSection.tsx
  components/users/detail/GenLogo.tsx
  components/users/detail/PartItem.tsx
  pages/members/detail.tsx
  pages/members/index.tsx
  pages/members/upload.tsx
  public/icons/logo/index.ts
  public/icons/logo/time=1-11.svg
  public/icons/logo/time=12.svg
  public/icons/logo/time=14.svg
  public/icons/logo/time=15.svg
  public/icons/logo/time=16.svg
  public/icons/logo/time=17.svg
  public/icons/logo/time=18.svg
  public/icons/logo/time=19.svg
  public/icons/logo/time=20.svg
  public/icons/logo/time=21.svg
  public/icons/logo/time=22.svg
  public/icons/logo/time=23.svg
  public/icons/logo/time=24.svg
  public/icons/logo/time=25.svg
  public/icons/logo/time=26.svg
  public/icons/logo/time=27.svg
  public/icons/logo/time=28.svg
  public/icons/logo/time=29.svg
  public/icons/logo/time=30.svg
  public/icons/logo/time=31.svg
  styles/global.ts
Labels: 🐛 Bug, ✨ Feature

#185 chore: 크롬 자동완성 스타일 reset
  styles/global.ts
Labels: 🐛 Bug

#202 fix: 메이커스 소개 페이지 오류 수정
  components/common/Header/index.tsx
  components/makers/PersonBlock.tsx
Labels: 🐛 Bug

#210 fix: 타이틀 추가
  pages/_app.tsx
Labels: size/XS

#213 fix: 회원 인증 화면 포커스 문제 수정
  components/auth/register/VerifyByEmail.tsx
  components/common/SquareLink/index.tsx
  components/common/SquareLink/style.ts
  components/debug/SideToggleButton.tsx
  pages/auth/verify.tsx
Labels: size/M

#220 fix: 토큰 없을 때 리다이렉트 시 멤버 페이지가 잠깐 나왔다 로그인 페이지로 가는 버그 수정
  components/auth/AuthRequired.tsx
  pages/index.tsx
Labels: 🐛 Bug, size/S

#216 fix: 드롭다운과 메뉴 닫히지 않는 버그 수정
  components/common/Header/index.tsx
Labels: size/L

#217 fix: 푸터 z-index 수정
  components/common/Footer/index.tsx
Labels: size/XS

#224 fix: member에 라우트가 갇히는 문제 해결
  components/auth/AuthRequired.tsx
  pages/index.tsx
Labels: 🐛 Bug, ⚡️ Urgent, size/S

#225 fix: 메인 페이지 리다이렉트 수정
  pages/index.tsx
Labels: size/S

#212 feat: 프로필 업로드 > 생일 유효성 검사 추가
  components/members/upload/BasicFormSection.tsx
  components/members/upload/constants.ts
  components/members/upload/schema.ts
Labels: size/M

#227 feat: 프로필 업로드 > 링크 유효성 검사 추가
  components/members/upload/AdditionalInfoFormSection.tsx
  components/members/upload/schema.ts
Labels: size/M

#230 최신 순 정렬 & 동일한 이름의 프로젝트일 경우 최신 프로젝트만 보이도록 수정
  .yarn/install-state.gz
  pages/projects/index.tsx
Labels: size/S

#197 refactor: 스키마 누락된 검증 추가, 누락된 에러메시지 추가
  .yarn/cache/react-hook-form-npm-7.31.3-a649987f06-01601c904c.zip
  .yarn/cache/react-hook-form-npm-7.39.5-b7cf09b360-91bc9543c1.zip
  components/common/ImageUploader/index.tsx
  components/common/form/FormItem.tsx
  components/common/form/RHFControllerFormItem.tsx
  components/projects/upload/MemberForm/MemberSearch.tsx
  components/projects/upload/MemberForm/index.tsx
  components/projects/upload/ProjectCategory.tsx
  components/projects/upload/ProjectImageSection.tsx
  components/projects/upload/ProjectMemebers.tsx
  components/projects/upload/ProjectServiceType.tsx
  components/projects/upload/schema.ts
  package.json
  pages/projects/upload/index.tsx
  yarn.lock
Labels: size/L

#232 fix: 프로젝트 링크 빈 배열로 내려오지 않는 이슈 수정
  .yarn/install-state.gz
  components/projects/main/ProjectCard.tsx
Labels: 🐛 Bug, size/XS

#236 fix: 전공만 노출되는 버그 해결
  pages/members/detail.tsx
Labels: size/XS

#222 feat: 멤버 상세에서 프로젝트 카드 노출
  api/members/type.ts
  components/projects/main/ProjectCard.tsx
  components/projects/upload/LinkForm/index.tsx
  components/users/detail/MemberProjectCard.tsx
  pages/members/detail.tsx
  pages/projects/index.tsx
Labels: ✨ Feature, size/L

#228 chore: 배포 설정 변경
  .github/workflows/build-test.yml
  .github/workflows/chromatic.yml
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: size/M

#226 feat: 디버그 패널 개선
  components/debug/Debugger.tsx
  components/debug/SideBar.tsx
  components/debug/SideToggleButton.tsx
  components/debug/panels/NavigationPanel.tsx
Labels: size/M

#234 feat: 이미지 최적화
  components/makers/AboutMakers.tsx
  components/makers/PersonBlock.tsx
  components/members/main/MemberCard/index.tsx
  components/projects/main/ProjectCard.tsx
Labels: size/M

#240 feat: 멤버 상세와 프로젝트 상세 URL 변경
  components/common/Header/index.tsx
  components/makers/MakersMembers.tsx
  components/members/main/MemberDetail/index.tsx
  components/members/main/MemberList/index.tsx
  components/members/upload/BasicFormSection.tsx
  components/projects/main/ProjectCard.tsx
  components/projects/main/ProjectDetail.tsx
  components/projects/main/ProjectList.tsx
  components/users/detail/MemberProjectCard.tsx
  hooks/useStringRouterQuery.ts
  pages/auth/callback/facebook/login.tsx
  pages/members/detail.tsx
  pages/members/index.tsx
  pages/members/upload.tsx
  pages/projects/detail.tsx
  pages/projects/index.tsx
Labels: size/XXL
