Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2022-12, with the labels that each got.

#244 fix: dayjs custom format 추가
  components/projects/upload/utils.ts
Labels: size/XS

#175 refactor: 레이아웃 분리
  components/common/Footer/index.tsx
  components/layout/EmptyLayout.stories.tsx
  components/layout/EmptyLayout.tsx
  components/layout/HeaderFooterLayout.stories.tsx
  components/layout/HeaderFooterLayout.tsx
  components/layout/HeaderLayout.stories.tsx
  components/layout/HeaderLayout.tsx
  components/layout/index.tsx
  pages/_app.tsx
  pages/auth/login.tsx
  pages/auth/register-finished.tsx
  pages/auth/register.tsx
  pages/auth/verify.tsx
  pages/index.tsx
  pages/members/detail.tsx
  pages/members/index.tsx
  pages/members/upload.tsx
  pages/projects/detail.tsx
  pages/projects/index.tsx
  pages/projects/upload/index.tsx
  utils/layout.tsx
Labels: size/L

#246 fix: 잘못된 메이커스 멤버 정보 수정
  components/makers/data/generation1.ts
Labels: ⚡️ Urgent, size/XS

#245 refactor: 사이트 내 URL 모으기
  components/auth/AuthRequired.tsx
  components/auth/register/RegisterFinished.tsx
  components/auth/register/VerifyByEmail.tsx
  components/auth/useAuth.ts
  components/common/Footer/index.tsx
  components/common/Header/index.tsx
  components/common/LegacyHeader/index.tsx
  components/debug/panels/NavigationPanel.tsx
  components/makers/MakersMembers.tsx
  components/members/main/MemberDetail/index.tsx
  components/members/main/MemberList/index.tsx
  components/projects/main/ProjectCard.tsx
  components/users/detail/MemberProjectCard.tsx
  constants/links.ts
  pages/auth/callback/facebook/login.tsx
  pages/auth/callback/facebook/register.tsx
  pages/auth/login.tsx
  pages/index.tsx
  pages/makers/index.tsx
  pages/members/detail.tsx
  pages/members/upload.tsx
  pages/projects/detail.tsx
  pages/projects/upload/index.tsx
Labels: size/L

#253 fix: detail link 수정
  constants/links.ts
Labels: size/XS

#266 fix: 멤버 상세 프로필 텍스트 줄 넘어가는 버그 해결
  components/members/main/MemberDetail/index.tsx
Labels: 🐛 Bug, size/S

#269 fix: 활동 기수 내림차순으로 보여주도록 수정
  components/members/main/MemberDetail/index.tsx
Labels: 🐛 Bug, size/S

#270 fix: 프로필 내 프로젝트 목록에서 서비스타입 보여주도록
  api/members/type.ts
  components/users/detail/MemberProjectCard.tsx
Labels: 🐛 Bug, size/M

#271 fix: 멤버 상세에서 프로젝트 카드 클릭하면 멤버 페이지로 이동하는 버그 해결
  components/users/detail/MemberProjectCard.tsx
Labels: 🐛 Bug, size/XS

#273 fix: 기수별 SOPT 로고 잘못 표시되는 버그 해결
  components/users/detail/GenLogo.tsx
  components/users/detail/PartItem.tsx
  public/icons/logo/index.ts
Labels: 🐛 Bug, size/L

#275 feat: 상세 내 기수 정보의 프로젝트 뱃지에 카테고리 표시 & 링크 클릭시 새창에서 열리도록 변경
  .vscode/settings.json
  api/members/type.ts
  components/members/detail/ActivityBadge.tsx
  components/members/detail/InfoItem.tsx
  components/members/detail/MemberProjectCard.tsx
  components/members/detail/PartItem.tsx
  components/members/main/MemberDetail/index.tsx
Labels: ✨ Feature, size/M

#256 feat: GTM 설치
  components/googleTagManager/Noscript.tsx
  components/googleTagManager/Script.tsx
  pages/_app.tsx
  pages/_document.tsx
Labels: ✨ Feature, size/M

#278 feat: 파비콘 설정
  public/favicon.ico
Labels: size/XS

#282 Revert "Merge pull request #276 from sopt-makers/feature/#257"
  api/members/index.ts
  apiHooks/members.ts
  components/makers/MakersMembers.tsx
  components/members/main/MemberList/index.tsx
  components/members/main/MemberRoleMenu/MemberRoleDropdown.tsx
  components/members/main/MemberRoleMenu/MemberRoleMenuItem.tsx
  components/members/main/MemberRoleMenu/index.tsx
  components/members/main/MemberRoleMenu/useMemberRoleMenu.ts
  public/icons/icon-server.svg
Labels: size/L

#250 feat: 공통 모달(알럿, 컨펌 포함) 구현
  .yarn/cache/focus-trap-npm-7.2.0-e1aef3f55e-181138fab2.zip
  .yarn/cache/focus-trap-react-npm-10.0.2-881b9396cf-9bd3388376.zip
  .yarn/cache/tabbable-npm-6.0.1-220bd3eafe-65e378ad69.zip
  .yarn/install-state.gz
  api/members/index.ts
  api/members/type.ts
  apiHooks/index.ts
  apiHooks/members.ts
  components/common/Modal/Alert.tsx
  components/common/Modal/Confirm.tsx
  components/common/Modal/Portal.tsx
  components/common/Modal/index.stories.tsx
  components/common/Modal/index.tsx
  components/common/Modal/useModalState.ts
  components/common/Text/index.tsx
  components/layout/HeaderFooterLayout.tsx
  components/layout/HeaderLayout.tsx
  components/members/main/MemberDetail/ CoffeeChatModal.stories.tsx
  components/members/main/MemberDetail/CoffeeChatModal.tsx
  components/members/main/MemberDetail/index.tsx
  hooks/useOnClickOutside.ts
  package.json
  public/icons/icon-appjam-build.svg
  public/icons/icon-coffeechat.svg
  public/icons/icon-mentoring.svg
  public/icons/icon-modal-check.svg
  public/icons/icon-modal-close.svg
  public/icons/icon-network.svg
  public/icons/icon-postnote-etc.svg
  public/icons/icon-project-suggest.svg
  styles/global.ts
  styles/spacing.ts
  styles/typography.ts
  utils/buildCSSWithLength.ts
  utils/index.ts
  yarn.lock
Labels: size/XXL

#287 Revert "Merge pull request #282 from sopt-makers/revert/#257"
  api/members/index.ts
  apiHooks/members.ts
  components/makers/MakersMembers.tsx
  components/members/main/MemberList/index.tsx
  components/members/main/MemberRoleMenu/MemberRoleDropdown.tsx
  components/members/main/MemberRoleMenu/MemberRoleMenuItem.tsx
  components/members/main/MemberRoleMenu/index.tsx
  components/members/main/MemberRoleMenu/useMemberRoleMenu.ts
  public/icons/icon-server.svg
Labels: size/L

#289 refactor: 커피챗 로딩 추가
  components/members/main/MemberDetail/CoffeeChatModal.tsx
Labels: size/S

#286 feat: GA 페이지뷰 이벤트 측정되도록
  components/googleTagManager/gtm.ts
  pages/_app.tsx
Labels: size/S

#283 fix: 헤더 영역 높이 수정
  pages/makers/index.tsx
Labels: size/XS

#284 feat: 페이지 이동 로딩바 추가
  .yarn/cache/@badrap-bar-of-progress-npm-0.2.2-860cb6ba6d-9b0d7c2762.zip
  .yarn/install-state.gz
  package.json
  pages/_app.tsx
  yarn.lock
Labels: size/S

#252 feat: 구글 로그인 구현
  .env.development
  api/registration/index.ts
  components/auth/identityProvider/google/GoogleAuthButton.tsx
  components/auth/identityProvider/google/useGoogleAuth.ts
  components/auth/register/Register.tsx
  pages/auth/callback/google/login.tsx
  pages/auth/callback/google/register.tsx
  pages/auth/login.tsx
  public/icons/icon-google-color.svg
Labels: size/L

#294 feat: 멤버 정보 그룹핑 로직 lodash로 변경, 클릭시 디테일 페이지로 이동
  .yarn/install-state.gz
  components/projects/main/ProjectDetail.tsx
Labels: size/M

#295 feat: 구글 로그인 숨김 추가
  components/auth/identityProvider/google/useGoogleAuth.ts
  components/auth/register/Register.tsx
  pages/auth/login.tsx
Labels: ⚡️ Urgent, size/S

#299 fix: 환영 메시지 밑 여백 수정
  components/members/main/MemberList/index.tsx
Labels: 🐛 Bug, size/XS

#297 refactor: 디버그 패널 코드 최적화
  components/debug/Debugger.tsx
  pages/_app.tsx
Labels: size/S

#298 refactor: 환경 변수 모으기
  .env.development
  .github/workflows/build-test.yml
  api/index.ts
  components/auth/identityProvider/google/useGoogleAuth.ts
  components/auth/identityProvider/useFacebookAuth.ts
  components/googleTagManager/Noscript.tsx
  components/googleTagManager/Script.tsx
  components/projects/upload/SignUpLink/index.tsx
  constants/Config.ts
  constants/env.ts
  pages/_app.tsx
Labels: size/M

#308 chore: analyze 명령 추가
  .yarn/cache/@next-bundle-analyzer-npm-13.1.1-6c9de7a38a-c755cb46ac.zip
  .yarn/cache/@polka-url-npm-1.0.0-next.21-02342f3d90-c7654046d3.zip
  .yarn/cache/acorn-npm-8.8.1-20e4aea981-4079b67283.zip
  .yarn/cache/cross-env-npm-7.0.3-96d81820f4-26f2f3ea2a.zip
  .yarn/cache/duplexer-npm-0.1.2-952c810235-62ba61a830.zip
  .yarn/cache/gzip-size-npm-6.0.0-d5b52fdbf1-2df97f3596.zip
  .yarn/cache/mrmime-npm-1.0.1-d0aa4f5ddf-cc979da44b.zip
  .yarn/cache/opener-npm-1.5.2-7a1aa69f14-33b620c0d5.zip
  .yarn/cache/sirv-npm-1.0.19-2cea3eead6-c943cfc61b.zip
  .yarn/cache/totalist-npm-1.1.0-4e1d9cb01b-dfab80c710.zip
  .yarn/cache/webpack-bundle-analyzer-npm-4.7.0-493ca27caa-4ce3b379c6.zip
  .yarn/cache/ws-npm-7.5.9-26f12a5ed6-c3c100a181.zip
  .yarn/install-state.gz
  next.config.js
  package.json
  yarn.lock
Labels: size/L

#307 feat: 무한스크롤 구현, 필터 queryParams로 교체
  api/members/index.ts
  apiHooks/members.ts
  components/common/ResizedImage/index.tsx
  components/makers/MakersMembers.tsx
  components/members/main/MemberList/index.tsx
  hooks/useEnterScreen.ts
  hooks/useIntersectionObserver.ts
Labels: size/L

#302 feat: 프로필 업로드 > 경력 추가
  .yarn/cache/@popperjs-core-npm-2.11.6-5bcdc104bd-47fb328cec.zip
  .yarn/cache/@types-react-datepicker-npm-4.8.0-436ed0cec3-4404d6bd27.zip
  .yarn/cache/classnames-npm-2.3.2-d2fdae468d-2c62199789.zip
  .yarn/cache/date-fns-npm-2.29.3-fef7e3c72c-e01cf5b62a.zip
  .yarn/cache/react-datepicker-npm-4.8.0-40274fac86-d31a1002c5.zip
  .yarn/cache/react-fast-compare-npm-3.2.0-fbfa6627d9-8ef272c825.zip
  .yarn/cache/react-onclickoutside-npm-6.12.2-61c80f0d9a-a0c7f4fbcf.zip
  .yarn/cache/react-popper-npm-2.3.0-1045578379-837111c987.zip
  .yarn/cache/warning-npm-4.0.3-291e921d6d-4f2cb6a957.zip
  .yarn/install-state.gz
  api/members/type.ts
  components/common/MonthPicker.tsx
  components/members/upload/AddableItem.tsx
  components/members/upload/BasicFormSection.tsx
  components/members/upload/CareerFormSection.tsx
  components/members/upload/constants.ts
  components/members/upload/schema.ts
  components/members/upload/types.ts
  package.json
  pages/members/upload.tsx
  yarn.lock
Labels: ✨ Feature, size/L
