Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-08, with the labels that each got.

#925 feat: 모집 배너 변경
  components/common/Banner/RecruitingBanner/index.tsx
Labels: size/XS

#931 fix: 프로젝트 진행상황 - 기수 버그 수정, 프로젝트 이미지 추가
  components/projects/form/ProjectForm.tsx
  components/projects/form/UploadProjectProgress.tsx
  components/projects/form/fields/GenerationField.tsx
  components/projects/form/schema.ts
Labels: size/M

#924 fix: 이미지 한글 인코딩되지 않던 문제 수정
  api/endpoint/common/image.ts
  api/endpoint_LEGACY/image/index.ts
  components/common/ImageUploader/Legacy.tsx
  components/common/ImageUploader/index.tsx
  components/projects/form/ListImageUploader.tsx
Labels: size/M

#932 feat: 3기 모집 정보 제거
  components/common/Banner/ActiveBannerSlot.tsx
  components/common/Header/mobile/MobileSideBar.tsx
  components/makers/Notifier.tsx
Labels: size/S

#933 fix: 프로필 상세 > mbti 설명 개행 되도록
  components/members/detail/InterestSection/index.tsx
Labels: size/XS

#934 feat: 33기 적용
  constants/generation.ts
Labels: size/XS
