Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-07, with the labels that each got.

#841 feat: Color Scheme 적용
  pages/_app.tsx
  styles/global.ts
Labels: size/XS

#852 refactor: 진행 중인 끝말잇기와 끝난 끝말잇기 리스트 서버 상태 분리
  api/endpoint/wordchain/getWordchain.ts
  components/wordchain/WordchainChatting/Wordchain/index.tsx
  components/wordchain/WordchainChatting/index.tsx
  components/wordchain/WordchainChatting/types.ts
  components/wordchain/WordchainEntry/WordChainEntry.tsx
  components/wordchain/WordchainEntry/types.ts
Labels: 🛠 Refactor, size/L

#854 feat: 메이커스 로고 변경
  components/makers/AboutMakers.tsx
  pages/auth/login.tsx
  public/logos/logo-makers-full.svg
  public/vercel.svg
Labels: size/M

#855 fix: 끝말잇기 채팅 쿼리 이펙트 정리
  api/endpoint/wordchain/getWordchain.ts
  components/wordchain/WordchainChatting/index.tsx
Labels: size/M

#856 feat: 끝말잇기 채팅 > 새 페이지 fetch 시 스크롤을 fetch 전의 위치로 이동
  components/wordchain/WordchainChatting/index.tsx
Labels: size/S

#858 feat: 끝말잇기 로깅 추가
  components/eventLogger/events.ts
  components/wordchain/WordchainChatting/Wordchain/index.tsx
  components/wordchain/WordchainChatting/index.tsx
  components/wordchain/WordchainEntry/WordChainEntry.tsx
  pages/wordchain/index.tsx
Labels: size/M

#863 chore: 끝말잇기 채팅 > 스토리북 업데이트 대응 및 개선
  components/wordchain/WordchainChatting/StartWordChatMessage/index.stories.tsx
  components/wordchain/WordchainChatting/WordChatMessage/index.stories.tsx
  components/wordchain/WordchainChatting/Wordchain/index.stories.tsx
  components/wordchain/WordchainEntry/WordChainEntry.stories.tsx
  components/wordchain/WordchainEntry/WordChainEntry.tsx
  components/wordchain/WordchainEntry/WordchainMessage.stories.tsx
  components/wordchain/WordchainRules.stories.tsx
  pages/wordchain/index.tsx
Labels: size/L

#864 feat: 첫 끝말잇기 시작 메시지 워딩 수정
  components/wordchain/WordchainChatting/Wordchain/index.tsx
Labels: size/XS

#866 feat: 끝말잇기 채팅 초기 진입 시 스크롤 초기화 되기 전까지 로딩뷰 띄우기
  components/wordchain/WordchainChatting/index.tsx
Labels: size/S

#876 chore: 끝말잇기 규칙 텍스트 수정
  components/wordchain/WordchainRules.tsx
Labels: size/XS

#870 chore: eslint warning을 제거합니다.
  components/common/Header/desktop/DesktopHeader.tsx
  components/makers/Notifier.tsx
  components/members/common/select/Select.tsx
  components/mentoring/data/development.ts
  components/mentoring/data/production.ts
  components/projects/upload/MemberForm/index.tsx
  components/wordchain/WordchainChatting/index.tsx
  pages/wordchain/index.tsx
Labels: size/M

#877 feat: 마지막 단어를 보낸 유저가 본인이면 새 게임 시작 못하도록
  components/wordchain/WordchainChatting/Wordchain/index.tsx
Labels: size/XS

#882 feat: 끝말잇기 채팅 업데이트 개선
  components/wordchain/WordchainChatting/index.tsx
Labels: size/XS

#883 fix: polling 제거
  components/wordchain/WordchainChatting/index.tsx
Labels: size/XS

#887 chore: 끝말잇기 진입점 터치영역 수정
  components/wordchain/WordchainEntry/WordChainEntry.tsx
Labels: size/S

#878 feat: 프로젝트 상세 > 메인 이미지 슬라이더 추가
  .yarn/cache/ssr-window-npm-4.0.2-01f9c0151e-df18260092.zip
  .yarn/cache/swiper-npm-9.4.1-38d46d35a3-1180b3b766.zip
  components/projects/main/ProjectDetail.tsx
  components/projects/main/ProjectImageSlider.stories.tsx
  components/projects/main/ProjectImageSlider.tsx
  package.json
  yarn.lock
Labels: size/L

#889 Revert "feat: 스크롤이 최하단일 때에만 polling 되도록 (#884)"
  components/wordchain/WordchainChatting/index.tsx
Labels: size/XS

#879 refactor: 프로젝트 업로드 페이지 > 페이지 퍼블리싱 및 api 연결
  api/endpoint_LEGACY/projects/type.ts
  components/common/Divider/Divider.stories.tsx
  components/common/Divider/Divider.tsx
  components/projects/form/ProjectForm.tsx
  components/projects/form/UploadProjectProgress.tsx
  components/projects/form/constants.ts
  components/projects/upload/hooks/useGetProjectListQuery.ts
  pages/projects/upload/v2/index.tsx
Labels: size/L

#891 feat: 프로젝트 카드 호버시 디자인 수정
  components/projects/main/ProjectCard.tsx
Labels: size/L

#888 refactor: 프로젝트 수정 페이지 리팩토링
  components/projects/edit/ProjectEdit.tsx
  components/projects/form/ProjectForm.tsx
  components/projects/form/fields/MemberField.tsx
  components/projects/form/fields/member/MemberSearch.tsx
  components/projects/form/fields/member/MemberSearchContext.tsx
  components/projects/upload/hooks/useGetProjectListQuery.ts
  components/projects/upload/hooks/useGetProjectQuery.ts
  components/projects/utils.ts
  constants/links.ts
  functions/projects/edit/[id].ts
  pages/projects/edit/[id].tsx
  pages/projects/upload/v2/index.tsx
Labels: size/L

#892 chore: 프로젝트 업로드 리팩토링 링크 변경
  components/projects/upload/LinkForm/index.tsx
  components/projects/upload/MemberForm/index.tsx
  components/projects/upload/ProjectCategory.tsx
  components/projects/upload/ProjectDetail.tsx
  components/projects/upload/ProjectGeneration.tsx
  components/projects/upload/ProjectImageSection.tsx
  components/projects/upload/ProjectName.tsx
  components/projects/upload/ProjectPeriod.tsx
  components/projects/upload/ProjectServiceType.tsx
  components/projects/upload/ProjectStatus.tsx
  components/projects/upload/ProjectSummary.tsx
  components/projects/upload/constants.ts
  components/projects/upload/types.ts
  pages/projects/upload/index.tsx
  pages/projects/upload/legacy/index.tsx
  pages/projects/upload/v2/index.tsx
Labels: size/XL

#893 fix: ProjectEdit 수정사항 반영
  components/projects/edit/ProjectEdit.tsx
  components/projects/utils.ts
Labels: size/XS

#894 fix: 프로젝트 업로드 후 onSuccess 실행되지 않던 문제 수정
  components/projects/edit/ProjectEdit.tsx
  components/projects/form/ProjectForm.tsx
  pages/projects/upload/index.tsx
Labels: size/S

#851 feat: 소울메이트 컴포넌트들 생성
  .storybook/main.ts
  .vscode/typescripreact.code-snippets
  components/soulmate/icons/SoulmateIcon.tsx
  components/soulmate/icons/SoulmateIconFlag.tsx
  components/soulmate/icons/SoulmateIconHeart.tsx
  components/soulmate/icons/files/soulmateIcon.png
  components/soulmate/icons/files/soulmateIconCry.png
  components/soulmate/icons/files/soulmateIconFlag.png
  components/soulmate/icons/files/soulmateIconHeart.png
  components/soulmate/view/EntryCard.stories.tsx
  components/soulmate/view/EntryCard.tsx
  components/soulmate/view/chat/ChatLayout.stories.tsx
  components/soulmate/view/chat/ChatLayout.tsx
  components/soulmate/view/chat/ChatRule.stories.tsx
  components/soulmate/view/chat/ChatRule.tsx
  components/soulmate/view/chat/Feedback.stories.tsx
  components/soulmate/view/chat/Feedback.tsx
  components/soulmate/view/chat/Menu.stories.tsx
  components/soulmate/view/chat/Menu.tsx
  components/soulmate/view/chat/MissionProgress.stories.tsx
  components/soulmate/view/chat/MissionProgress.tsx
  components/soulmate/view/chat/SoulmateChat.stories.tsx
  components/soulmate/view/chat/SoulmateChat.tsx
  components/soulmate/view/common/SoulmateModal.stories.tsx
  components/soulmate/view/common/SoulmateModal.tsx
  components/soulmate/view/common/commonStyles.ts
  components/soulmate/view/layout/LobbyLayout.stories.tsx
  components/soulmate/view/layout/LobbyLayout.tsx
  components/soulmate/view/lobby/ExitSoulmateLink.stories.tsx
  components/soulmate/view/lobby/ExitSoulmateLink.tsx
  components/soulmate/view/lobby/MatchingStatus.stories.tsx
  components/soulmate/view/lobby/MatchingStatus.tsx
  components/soulmate/view/lobby/Register.stories.tsx
  components/soulmate/view/lobby/Register.tsx
  components/soulmate/view/lobby/RegisterSuccessModal.stories.tsx
  components/soulmate/view/lobby/RegisterSuccessModal.tsx
  package.json
  yarn.lock
Labels: size/XXL

#896 chore: project QA
  api/endpoint_LEGACY/projects/type.ts
  components/projects/form/ListImageUploader.tsx
  components/projects/form/ProjectForm.tsx
  components/projects/main/ProjectImageSlider.tsx
  components/projects/utils.ts
  pages/projects/upload/legacy/index.tsx
Labels: size/M

#900 feat: 디버그 패널 버튼 크기 변경
  components/debug/SideToggleButton.tsx
  pages/soulmate/index.tsx
Labels: size/S

#901 feat: 멤버 검색 css 수정, 끝말잇기 및 프로젝트 헤더쪽 layout shift 수정
  components/members/main/MemberList/MemberSearch.tsx
  components/members/main/MemberList/index.tsx
  components/projects/main/ProjectList.tsx
  components/wordchain/WordchainEntry/WordChainEntry.tsx
Labels: size/S

#902 feat: 모집설명회 배너 제작
  components/common/Banner/ActiveBannerSlot.tsx
  components/common/Banner/RecruitingBanner/icons.tsx
  components/common/Banner/RecruitingBanner/index.tsx
  components/common/Banner/RecruitingBanner/legacy/CountdownTimer.tsx
  components/common/Banner/RecruitingBanner/legacy/MobileRecruitingBanner.tsx
  components/common/Banner/RecruitingBanner/legacy/constants.ts
  components/common/Banner/RecruitingBanner/legacy/index.tsx
Labels: size/L

#905 fix: 프로필 업로드 스키마 수정
  components/members/upload/schema.ts
Labels: size/XS

#904 chore: 회원가입 완료 페이지 스타일링 수정
  components/auth/register/RegisterFinished.tsx
  pages/auth/register-finished.tsx
Labels: size/XS

#906 feat: 끝말잇기 모바일 대응
  components/wordchain/WordchainChatting/StartWordChatMessage/index.tsx
  components/wordchain/WordchainChatting/WordChatMessage/index.tsx
  components/wordchain/WordchainChatting/Wordchain/index.tsx
  components/wordchain/WordchainChatting/index.tsx
  pages/members/index.tsx
  pages/wordchain/index.tsx
  styles/typography.ts
Labels: ✨ Feature, size/L

#911 feat: 푸터에 메이커스 소개 추가
  components/common/Footer/index.tsx
  constants/links.ts
Labels: ✨ Feature, size/XS

#913 feat: 만든 사람들 > 메이커스 3기 모집 홍보 배너 추가
  components/makers/Notifier.tsx
Labels: ✨ Feature, size/M

#916 feat: 회원가입 플로우 변경 대비 프로필 업로드 스펙 변경
  components/members/upload/FormSection/Basic/index.tsx
  components/members/upload/FormSection/SoptActivity.tsx
  pages/members/edit.tsx
Labels: size/L

#918 fix: 프로필 수정 > 활동 기수 request body 형식 맞추기
  pages/members/edit.tsx
Labels: 🐛 Bug, size/XS

#919 fix: 3기 리크루팅 배너 로고 사이즈 수정
  components/common/Banner/RecruitingBanner/icons.tsx
  components/common/Banner/RecruitingBanner/index.tsx
Labels: 🐛 Bug, size/M

#920 fix: 이메일 null 예외 처리
  components/members/detail/MessageSection/index.tsx
Labels: 🐛 Bug, size/XS
