Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-05, with the labels that each got.

#633 feat & refactor: 프로젝트 업로드 > 멤버 폼 추가
  .yarn/cache/@radix-ui-react-dialog-npm-1.0.0-50f25f2343-32a1ab36a4.zip
  .yarn/cache/@radix-ui-react-dismissable-layer-npm-1.0.0-4455fc7257-c5af6445ea.zip
  .yarn/cache/@radix-ui-react-focus-scope-npm-1.0.0-2707a7cc27-2ee0b9a2d1.zip
  .yarn/cache/@radix-ui-react-portal-npm-1.0.0-9b1efb8f21-dfb194b2df.zip
  .yarn/cache/@radix-ui-react-primitive-npm-1.0.0-6caac41c73-fb3fe8c8c5.zip
  .yarn/cache/@radix-ui-react-slot-npm-1.0.0-2a9f31c53d-60c0190ebd.zip
  .yarn/cache/@radix-ui-react-use-escape-keydown-npm-1.0.0-6348865152-a6728d40e0.zip
  .yarn/cache/cmdk-npm-0.2.0-302237a911-b81add6dae.zip
  .yarn/cache/command-score-npm-0.1.2-b352919071-b733fd552d.zip
  .yarn/cache/react-hook-form-npm-7.39.5-b7cf09b360-91bc9543c1.zip
  .yarn/cache/react-hook-form-npm-7.43.9-3a3f4f3335-65b94de625.zip
  .yarn/cache/react-remove-scroll-npm-2.5.4-4f98bf8db3-01b0f65542.zip
  api/endpoint_LEGACY/members/type.ts
  components/projects/form/ProjectForm.stories.tsx
  components/projects/form/ProjectForm.tsx
  components/projects/form/fields/MemberField.stories.tsx
  components/projects/form/fields/MemberField.tsx
  components/projects/form/fields/member/MemberSearch.stories.tsx
  components/projects/form/fields/member/MemberSearch.tsx
  components/projects/form/fields/member/MemberSearchContext.tsx
  components/projects/form/presenter/FormEntry.tsx
  components/projects/form/schema.ts
  components/projects/upload/MemberForm/MemberSearch.stories.tsx
  package.json
  pages/projects/upload/v2/index.tsx
  yarn.lock
Labels: size/XL

#680 refactor: 프로젝트 업로드 > 서비스 타입 필드 추가
  components/projects/form/ProjectForm.tsx
  components/projects/form/fields/ServiceTypeField.stories.tsx
  components/projects/form/fields/ServiceTypeField.tsx
  components/projects/form/schema.ts
Labels: size/L

#679 refactor: 프로젝트 업로드 > 프로젝트 현재 상태
  components/common/Switch/index.tsx
  components/projects/form/ProjectForm.tsx
  components/projects/form/fields/StatusField.stories.tsx
  components/projects/form/fields/StatusField.tsx
  components/projects/form/schema.ts
Labels: size/M

#681 refactor: 프로젝트 업로드 > LinkField 추가
  components/projects/form/ProjectForm.tsx
  components/projects/form/constants.ts
  components/projects/form/fields/LinkField.stories.tsx
  components/projects/form/fields/LinkField.tsx
  components/projects/form/fields/MemberField.stories.tsx
  components/projects/form/schema.ts
Labels: size/L

#683 fix: 모바일 멤버 카드 간격 수정
  components/members/main/MemberList/index.tsx
Labels: size/XS

#686 feat: 멤버 카드 호버 스타일 수정
  components/members/main/MemberCard/MessageButton.tsx
  components/members/main/MemberCard/index.tsx
Labels: size/M

#685 feat: 프로필 상세 > 커리어 디자인 변경 반영
  components/members/detail/CareerSection/CareerItem.tsx
  components/members/detail/CareerSection/index.tsx
Labels: ✨ Feature, size/M

#690 feat: SOPTKATON 배너 제작
  components/common/Banner/SOPTKATONBanner/DesktopEventBanner.tsx
  components/common/Banner/SOPTKATONBanner/MobileEventBanner.tsx
  components/common/Banner/SOPTKATONBanner/constants.ts
  components/common/Banner/SOPTKATONBanner/index.tsx
  pages/members/index.tsx
  pages/projects/index.tsx
Labels: size/L

#696 feat: SOPTMATE 배너 생성
  .vscode/typescripreact.code-snippets
  components/common/Banner/ActiveBannerSlot.tsx
  components/common/Banner/SOPTMATEBanner/index.stories.tsx
  components/common/Banner/SOPTMATEBanner/index.tsx
  components/common/Banner/Timer.tsx
  pages/members/index.tsx
  pages/projects/index.tsx
Labels: size/L

#697 feat: 프로필 상세 > 나는 어느 쪽? 항목 디자인 변경 대응
  components/members/detail/InterestSection/index.tsx
  components/members/detail/MemberDetail.tsx
Labels: ✨ Feature, size/M

#693 chore: 체리피킹 되고 사용되지 않는 lodash api 제거
  pages/projects/[id].tsx
  pages/projects/index.tsx
Labels: size/XS

#695 feat: MemberList grid layout 개선
  components/members/main/MemberList/index.tsx
Labels: size/L

#700 feat: SOPTMATE 배너 제거
  components/common/Banner/ActiveBannerSlot.tsx
Labels: size/XS

#699 feat: MemberList 새로운 필터 추가(desktop)
  components/members/common/select/Select.tsx
  components/members/main/MemberList/GenerationSelect.stories.tsx
  components/members/main/MemberList/GenerationSelect.tsx
  components/members/main/MemberList/filters/MemberListFilter.stories.tsx
  components/members/main/MemberList/filters/MemberListFilter.tsx
  components/members/main/MemberList/filters/constants.ts
  components/members/main/MemberList/index.tsx
  public/icons/icon-diagonal-arrow.svg
Labels: size/L

#702 feat: MemberList 모바일 필터 구현
  .yarn/cache/@react-aria-ssr-npm-3.6.0-4d15a68cc5-fab5cf0efb.zip
  .yarn/cache/@react-aria-utils-npm-3.14.2-f37e7265e0-db3f59ace7.zip
  .yarn/cache/@react-stately-utils-npm-3.6.0-bff4d46030-d2ff4cfed5.zip
  .yarn/cache/@react-types-shared-npm-3.18.0-5a2e76de3b-8fc56701e9.zip
  .yarn/cache/clsx-npm-1.2.1-77792dc182-30befca801.zip
  .yarn/cache/react-modal-sheet-npm-1.10.2-a34e454a17-291f0bd414.zip
  api/endpoint_LEGACY/members/type.ts
  components/eventLogger/events.ts
  components/members/common/select/OrderBySelect.stories.tsx
  components/members/common/select/OrderBySelect.tsx
  components/members/common/select/Select.tsx
  components/members/common/select/context.ts
  components/members/main/MemberList/MemberSearch.tsx
  components/members/main/MemberList/OnBoardingBanner.tsx
  components/members/main/MemberList/filters/MemberListFilter.tsx
  components/members/main/MemberList/filters/MemberListFilterSheet.stories.tsx
  components/members/main/MemberList/filters/MemberListFilterSheet.tsx
  components/members/main/MemberList/filters/constants.ts
  components/members/main/MemberList/index.tsx
  components/members/main/contants.ts
  package.json
  pages/_app.tsx
  pages/members/index.tsx
  public/icons/icon-arrow-up-down.svg
  public/icons/icon-filter-check.svg
  yarn.lock
Labels: size/XL

#707 feat: 프로젝트 멤버 역할 명시적으로 변경
  api/endpoint_LEGACY/projects/type.ts
  components/projects/main/ProjectDetail.tsx
  components/projects/upload/MemberForm/constants.ts
Labels: size/S

#713 feat: 스크롤 복원기능 추가
  next.config.js
Labels: size/XS

#694 feat: [base branch] MemberList 필터 개선
  .yarn/cache/@react-aria-ssr-npm-3.6.0-4d15a68cc5-fab5cf0efb.zip
  .yarn/cache/@react-aria-utils-npm-3.14.2-f37e7265e0-db3f59ace7.zip
  .yarn/cache/@react-stately-utils-npm-3.6.0-bff4d46030-d2ff4cfed5.zip
  .yarn/cache/@react-types-shared-npm-3.18.0-5a2e76de3b-8fc56701e9.zip
  .yarn/cache/clsx-npm-1.2.1-77792dc182-30befca801.zip
  .yarn/cache/react-modal-sheet-npm-1.10.2-a34e454a17-291f0bd414.zip
  api/endpoint_LEGACY/members/type.ts
  components/eventLogger/events.ts
  components/members/common/select/OrderBySelect.stories.tsx
  components/members/common/select/OrderBySelect.tsx
  components/members/common/select/Select.tsx
  components/members/common/select/context.ts
  components/members/main/MemberList/GenerationSelect.stories.tsx
  components/members/main/MemberList/GenerationSelect.tsx
  components/members/main/MemberList/MemberSearch.tsx
  components/members/main/MemberList/OnBoardingBanner.tsx
  components/members/main/MemberList/filters/MemberListFilter.stories.tsx
  components/members/main/MemberList/filters/MemberListFilter.tsx
  components/members/main/MemberList/filters/MemberListFilterSheet.stories.tsx
  components/members/main/MemberList/filters/MemberListFilterSheet.tsx
  components/members/main/MemberList/filters/constants.ts
  components/members/main/MemberList/index.tsx
  components/members/main/contants.ts
  package.json
  pages/_app.tsx
  pages/members/index.tsx
  public/icons/icon-arrow-up-down.svg
  public/icons/icon-diagonal-arrow.svg
  public/icons/icon-filter-check.svg
  yarn.lock
Labels: size/XXL

#711 feat: react-remove-scroll 모달 스크롤 방지
  .yarn/cache/react-remove-scroll-npm-2.5.6-fd9e884f94-0a31f82213.zip
  components/common/Modal/index.tsx
  package.json
  yarn.lock
Labels: size/M

#714 fix: 무한스크롤 오류 수정, 스타일 수정
  components/members/main/MemberList/index.tsx
  pages/members/index.tsx
Labels: size/M

#715 fix: 등록순 필터 주석처리
  api/endpoint_LEGACY/members/index.ts
  components/members/main/MemberList/index.tsx
Labels: size/S

#716 fix: 모바일에서 바텀싯 스크롤되지 않는 문제 수정
  components/members/main/MemberList/filters/MemberListFilterSheet.tsx
Labels: size/S

#710 feat: 멘토링 카드 및 캐러셀 구현
  components/common/Carousel/Body.tsx
  components/common/Carousel/index.stories.tsx
  components/common/Carousel/index.tsx
  components/common/Carousel/useCarousel.ts
  components/mentoring/MentoringCard/index.stories.tsx
  components/mentoring/MentoringCard/index.tsx
  hooks/usePagination.ts
  public/icons/icon-arrow-purple.svg
Labels: ✨ Feature, size/L

#722 refactor: api 함수 폴더 구조 변경
  api/endpoint/makers/getMakersProfile.ts
  api/endpoint/members/getMembersSearchByName.ts
  api/endpoint_LEGACY/hooks/members.ts
  components/projects/form/fields/MemberField.tsx
  components/projects/upload/hooks/useGetMembersByNameQuery.ts
  pages/makers/index.tsx
Labels: 🛠 Refactor, size/XS

#720 feat: 멘토링 상세 페이지 마크업
  components/members/detail/CareerSection/index.tsx
  components/mentoring/MentoringDetail/InfoItem.tsx
  components/mentoring/MentoringDetail/index.stories.tsx
  components/mentoring/MentoringDetail/index.tsx
  components/mentoring/MentoringDetail/types.ts
  components/mentoring/data.ts
  functions/mentoring/[id].ts
  pages/mentoring/[id].tsx
  styles/typography.ts
Labels: ✨ Feature, size/XL

#727 feat: 멘토링 데이터 하드 코딩 및 프로바이더 만들기
  components/mentoring/data/development.ts
  components/mentoring/data/index.ts
  components/mentoring/data/production.ts
  components/mentoring/data/types.ts
Labels: ✨ Feature, size/L

#729 chore: 등록순 필터 서버이슈 대응
  api/endpoint_LEGACY/members/index.ts
  components/members/main/MemberList/index.tsx
  components/members/main/hooks/useMemberProfileQuery.ts
Labels: size/M

#730 feat: 멘토링 리스트 마크업
  components/members/main/MemberList/index.tsx
  components/mentoring/MentoringCard/index.tsx
  components/mentoring/MentoringList/index.tsx
  pages/members/index.tsx
  utils/index.ts
Labels: ✨ Feature, size/L

#734 feat: 멘토링 데이터 연결 및 멘토 멤버 프로필 데이터 fetch
  components/mentoring/MentoringCard/index.tsx
  components/mentoring/MentoringDetail/index.tsx
  components/mentoring/MentoringDetail/types.ts
  components/mentoring/MentoringList/index.tsx
  components/mentoring/data.ts
  components/mentoring/data/development.ts
  components/mentoring/data/index.ts
  components/mentoring/data/production.ts
  constants/links.ts
  pages/mentoring/[id].tsx
Labels: ✨ Feature, size/L

#735 feat: 멘토링 신청 기능 구현
  components/members/detail/MessageSection/MessageModal.tsx
  components/members/detail/MessageSection/index.tsx
  components/members/main/MemberList/index.tsx
  components/mentoring/MentoringDetail/index.tsx
  components/mentoring/data/development.ts
Labels: ✨ Feature, size/L

#736 chore: 멘토링 관련 Amplitude 이벤트 등록
  components/common/Carousel/index.tsx
  components/eventLogger/events.ts
  components/members/detail/MemberDetail.tsx
  components/members/detail/MessageSection/MessageModal.tsx
  components/members/detail/MessageSection/index.tsx
  components/members/main/MemberList/index.tsx
  components/mentoring/MentoringCard/index.tsx
  components/mentoring/MentoringDetail/index.tsx
  components/mentoring/MentoringList/index.tsx
Labels: ✨ Feature, size/L

#726 feat: [base branch] 멘토링 상세 페이지, 멘토링 리스트
  components/common/Carousel/index.tsx
  components/eventLogger/events.ts
  components/members/detail/MemberDetail.tsx
  components/members/detail/MessageSection/MessageModal.tsx
  components/members/detail/MessageSection/index.tsx
  components/members/main/MemberList/index.tsx
  components/mentoring/MentoringCard/index.tsx
  components/mentoring/MentoringDetail/index.tsx
  components/mentoring/MentoringDetail/types.ts
  components/mentoring/MentoringList/index.tsx
  components/mentoring/data.ts
  components/mentoring/data/development.ts
  components/mentoring/data/index.ts
  components/mentoring/data/production.ts
  components/mentoring/data/types.ts
  constants/links.ts
  pages/members/index.tsx
  pages/mentoring/[id].tsx
  utils/index.ts
Labels: ✨ Feature, size/XL

#740 fix: 한글 파일명 이미지 깨지는 버그 fix
  api/endpoint_LEGACY/image/index.ts
Labels: 🐛 Bug, size/XS

#741 fix: 멘토링 데이터 추가 및 수정
  components/mentoring/data/production.ts
Labels: 🐛 Bug, size/M
