Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-12, with the labels that each got.

#1220 fix: 피드 이미지 슬라이더 > 이미지 닫기 버튼이 사진보다 위로 올라오도록
  src/components/feed/detail/slider/FeedImageSlider.tsx
Labels: 🐛 Bug, size/XS

#1226 feat: 로그아웃시 인트로 페이지로
  src/components/auth/AuthRequired.tsx
Labels: size/XS

#1229 feat: 로깅 전용 headless 컴포넌트 추가
  package.json
  src/components/eventLogger/components/LoggingClick.tsx
  src/components/eventLogger/components/LoggingImpression.tsx
  src/components/eventLogger/components/LoggingPageView.tsx
  src/components/eventLogger/controllers/amplitude.ts
  src/components/eventLogger/controllers/consoleLog.ts
  src/components/eventLogger/controllers/storybookAction.ts
  src/components/eventLogger/events.ts
  src/components/eventLogger/hooks/useEventLogger.ts
  src/components/eventLogger/types.ts
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/list/FeedList.tsx
  yarn.lock
Labels: size/L

#1232 feat: 피드 리스트, 디테일 등 로깅 추가
  src/components/eventLogger/events.ts
  src/components/feed/common/hooks/useFeedReferral.ts
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/detail/FeedDetailInput.tsx
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/feed/page/FeedHomePage.tsx
  src/pages/feed/[id].tsx
Labels: size/L

#1235 feat: 커뮤니티 조회수 구현
  src/api/endpoint/feed/postPostHit.ts
  src/components/feed/common/hooks/useHit.ts
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/feed/page/FeedHomePage.tsx
Labels: size/L

#1228 feat: 헤더 디자인 변경
  playground-common/package.json
  src/components/common/Header/desktop/DesktopHeader.tsx
  src/components/common/Header/imageData.tsx
  src/components/common/Header/mobile/MobileHeader.tsx
  src/constants/links.ts
Labels: ✨ Feature, size/L

#1236 chore: 끝말잇기와 멘토링 멤버에서 삭제
  src/pages/members/index.tsx
Labels: size/S

#1231 feat: 피드 업로드 페이지 로깅 구현
  src/api/endpoint/feed/uploadFeed.ts
  src/components/eventLogger/events.ts
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/CodeUploadButton/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesButton/index.tsx
Labels: size/L

#1238 feat: 멤버 페이지 헤더 변경에 따른 간격 수정/추가
  src/components/members/main/MemberList/index.tsx
Labels: size/XS

#1239 feat: 커뮤니티 이미지 리사이징 추가
  src/components/common/ResizedImage/index.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/FeedCard.stories.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
Labels: size/M

#1240 자잘한 스타일 수정
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/feed/page/layout/MobileCommunityLayout.tsx
  src/components/feed/upload/ImageUploadButton/index.tsx
Labels: size/L

#1241 글쓰기 뒤로가기 버튼 에러 수정
  src/components/feed/page/FeedUploadPage.tsx
Labels: size/XS

#1242 이미지 사이즈 크게 조정
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/FeedCard.tsx
Labels: size/XS

#1243 조회수 워딩 통일
  src/components/feed/detail/DetailFeedCard.tsx
Labels: size/XS

#1244 feat: 커뮤니티 이미지 리사이징 추가
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
Labels: size/M

#1245 SUIT 버전 v1으로 통일
  public/fonts/SUIT-Light.woff2
  public/fonts/SUIT-Regular.woff2
  src/components/feed/detail/DetailFeedCard.tsx
Labels: size/S

#1246 fix: 페이지 이동시 애니메이션 들썩거리는 현상 수정
  src/components/feed/page/layout/DesktopCommunityLayout.tsx
Labels: size/XS

#1247 feat: 커뮤니티 스크롤 복원 구현
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/feed/page/FeedHomePage.tsx
  src/components/layout/HeaderOnlyDesktopLayout.tsx
  src/components/layout/index.tsx
  src/components/navigation/NavigationProvider.tsx
  src/components/navigation/navigationContext.ts
  src/components/navigation/useNavigateBack.ts
  src/pages/_app.tsx
  src/pages/feed/[id].tsx
Labels: size/L

#1253 feat: 본문 줄바꿈 안됨으로 스크롤 생기는 이슈 수정, info ellipsis 되도록 수정
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/FeedCard.tsx
Labels: size/M

#1251 chore: 인트로에서 로그인되어있을 시 이동 링크, feedList로 변경
  src/pages/intro/index.tsx
Labels: size/XS

#1254 feat: 카테고리 변경시 동작 고도화
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/page/FeedHomePage.tsx
Labels: size/M

#1256 feat: 피드 상세 스크롤 정책 수정
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetail.tsx
Labels: size/S

#1257 fix: 클릭 영역 수정, 프로필 이미지 없을때 프로필 연결 안되는 문제 수정
  src/components/feed/list/FeedCard.tsx
Labels: size/S

#1259 fix: 콘텐츠 input과 푸터 겹치는 문제 해결
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/DropDown/index.tsx
  src/components/feed/upload/Input/ContentsInput/index.tsx
  src/components/feed/upload/layout/DesktopFeedUploadLayout.tsx
  src/components/feed/upload/layout/MobileFeedUploadLayout.tsx
Labels: size/M

#1261 fix: width 100%로 수정
  src/components/feed/upload/layout/DesktopFeedUploadLayout.tsx
Labels: size/XS

#1255 feat: 디버그 패널 개선
  src/components/debug/SideBar.tsx
  src/pages/_app.tsx
Labels: size/S
