Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-11, with the labels that each got.

#1043 feat: 스크롤 정책 변경
  src/components/community/layout/DesktopCommunityLayout.tsx
  src/components/community/layout/MobileCommunityLayout.tsx
Labels: size/S

#1045 fix: 이미지 업로더 버그 fix
  src/components/common/ImageUploader/index.tsx
Labels: 🐛 Bug, size/XS

#1050 feat: 리액트 쿼리 v5 마이그레이션
  package.json
  src/api/endpoint/members/getMemberOfMe.ts
  src/api/endpoint/wordchain/getWordchain.ts
  src/api/endpoint/wordchain/newGame.ts
  src/api/endpoint/wordchain/postWord.ts
  src/api/endpoint_LEGACY/hooks/members.ts
  src/api/endpoint_LEGACY/hooks/projects.ts
  src/components/auth/callback/OAuthLoginCallback.tsx
  src/components/common/Example/index.tsx
  src/components/members/detail/MessageSection/MessageModal.tsx
  src/components/members/main/hooks/useMemberProfileQuery.ts
  src/components/mentoring/MentoringDetail/index.tsx
  src/components/mentoring/MentoringList/index.tsx
  src/components/projects/edit/ProjectEdit.tsx
  src/components/projects/upload/form/fields/member/MemberSearch.tsx
  src/components/projects/upload/form/fields/member/MemberSearchContext.tsx
  src/components/projects/upload/hooks/useGetMembersByNameQuery.ts
  src/components/projects/upload/hooks/useGetProjectListQuery.ts
  src/components/projects/upload/hooks/useGetProjectQuery.ts
  src/components/sopticle/UploadSopticle.stories.tsx
  src/components/sopticle/UploadSopticle.tsx
  src/components/wordchain/WordchainChatting/Wordchain/index.tsx
  src/components/wordchain/WordchainChatting/index.tsx
  src/components/wordchain/WordchainWinners/hooks/useWordchainWinnersQuery.ts
  src/pages/_app.tsx
  src/pages/auth/reconnect.tsx
  src/pages/auth/register.tsx
  src/pages/members/edit.tsx
  src/pages/members/upload.tsx
  src/pages/projects/upload/index.tsx
  src/pages/sopticle/index.tsx
  yarn.lock
Labels: size/XXL

#1041 feat: 카테고리 셀렉터 구현
  package.json
  playground-common/package.json
  public/icons/icon_check.svg
  public/icons/icon_chevron_left.svg
  src/components/common/BottomSheet/index.stories.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/feed/upload/Category/CategoryHeader/index.stories.tsx
  src/components/feed/upload/Category/CategoryHeader/index.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/Category/CategorySelector/index.stories.tsx
  src/components/feed/upload/Category/CategorySelector/index.tsx
  src/components/feed/upload/Category/DropDown/index.stories.tsx
  src/components/feed/upload/Category/DropDown/index.tsx
  src/components/feed/upload/Category/TagSelector/TagSelectOptions.tsx
  src/components/feed/upload/Category/TagSelector/index.stories.tsx
  src/components/feed/upload/Category/TagSelector/index.tsx
  src/components/feed/upload/Category/constants.ts
  src/components/feed/upload/Category/index.stories.tsx
  src/components/feed/upload/Category/index.tsx
  src/components/feed/upload/Category/types.ts
  yarn.lock
Labels: size/XL

#1057 fix: 끝말잇기 스크롤 오류 수정
  src/components/wordchain/WordchainChatting/index.tsx
Labels: size/S

#1053 feat: 모바일에서 input focus 시 화면이 확대되는 현상 막기
  src/pages/_app.tsx
Labels: size/S

#1056 feat: 모달 재구현
  .storybook/preview.tsx
  package.json
  src/components/common/Modal/Alert.tsx
  src/components/common/Modal/Confirm.tsx
  src/components/common/Modal/index.stories.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Modal/parts/ModalButton.tsx
  src/components/common/Modal/parts/index.tsx
  src/components/common/Modal/useAlert.tsx
  src/components/common/Modal/useConfirm.tsx
  src/components/members/detail/MessageSection/MessageModal.tsx
  src/components/projects/edit/ProjectEdit.tsx
  src/components/projects/main/ProjectDetail.tsx
  src/components/wordchain/WordchainChatting/Wordchain/index.tsx
  src/pages/_app.tsx
  src/pages/projects/upload/index.tsx
  yarn.lock
Labels: size/XL

#1047 feat: 커뮤니티 이용규칙 구현
  package.json
  public/icons/icon_help.svg
  public/icons/icon_more.svg
  public/icons/polygon.svg
  src/components/feed/upload/UsingRules/UsingRulesButton/index.stories.tsx
  src/components/feed/upload/UsingRules/UsingRulesButton/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesPreview/index.stories.tsx
  src/components/feed/upload/UsingRules/UsingRulesPreview/index.tsx
  src/components/feed/upload/UsingRules/constants.ts
  src/components/feed/upload/UsingRules/index.stories.tsx
  src/components/feed/upload/UsingRules/index.tsx
  src/styles/global.ts
  yarn.lock
Labels: size/L

#1037 feat: 커뮤니티 리스트에 사용되는 FeedCard 구현
  .storybook/main.ts
  package.json
  src/components/common/Checkbox/index.tsx
  src/components/community/list/FeedList.tsx
  src/components/community/page/FeedHomePage.tsx
  src/components/feed/Icon.tsx
  src/components/feed/detail/DetailFeedCard.stories.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/main/FeedCard.stories.tsx
  src/components/feed/main/FeedCard.tsx
  src/components/feed/utils.ts
  src/constants/links.ts
  yarn.lock
Labels: size/XXL

#1058 feat: 커뮤니티 > 피드 이미지 슬라이더 구현
  package.json
  src/components/common/BottomSheet/index.tsx
  src/components/community/page/FeedHomePage.tsx
  src/components/debug/SideBar.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/slider/DynamicImage.tsx
  src/components/feed/detail/slider/FeedImageSlider.stories.tsx
  src/components/feed/detail/slider/FeedImageSlider.tsx
  src/components/feed/upload/Category/DropDown/index.tsx
  src/components/members/detail/MessageSection/Modal.tsx
  src/hooks/useEscapeCallback.ts
  yarn.lock
Labels: size/L

#1052 feat: 커뮤니티 규칙 세부 모달 및 바텀시트 구현
  src/components/common/BottomSheet/index.tsx
  src/components/common/Modal/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesDetail/index.stories.tsx
  src/components/feed/upload/UsingRules/UsingRulesDetail/index.tsx
  src/components/feed/upload/UsingRules/constants.ts
Labels: size/M

#1060 refactor: 피드 디렉터리 합치기
  src/components/feed/common/queryParam.tsx
  src/components/feed/common/utils.ts
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/list/FeedCard.stories.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/list/Icon.tsx
  src/components/feed/page/FeedHomePage.tsx
  src/components/feed/page/layout/DesktopCommunityLayout.tsx
  src/components/feed/page/layout/MobileCommunityLayout.tsx
  src/pages/community/index.tsx
Labels: size/S

#1061 feat: 커뮤니티 업로드 > 이미지 업로드 버튼, 이미지 프리뷰 컴포넌트 구현
  src/components/common/ImageUploader/index.tsx
  src/components/feed/upload/ImagePreview/index.stories.tsx
  src/components/feed/upload/ImagePreview/index.tsx
  src/components/feed/upload/ImageUploadButton/index.stories.tsx
  src/components/feed/upload/ImageUploadButton/index.tsx
  src/components/projects/upload/form/ListImageUploader.tsx
  src/hooks/useImageUploader.ts
Labels: ✨ Feature, size/L

#1064 feat: 피드 업로드 input 구현
  package.json
  src/components/feed/upload/Input/ContentsInput/index.stories.tsx
  src/components/feed/upload/Input/ContentsInput/index.tsx
  src/components/feed/upload/Input/TitleInput/index.stories.tsx
  src/components/feed/upload/Input/TitleInput/index.tsx
  yarn.lock
Labels: size/L

#1065 feat: 커뮤니티 피드 업로드 레이아웃 구현
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategoryHeader/index.tsx
  src/components/feed/upload/layout/DesktopFeedUploadLayout.stories.tsx
  src/components/feed/upload/layout/DesktopFeedUploadLayout.tsx
  src/components/feed/upload/layout/MobileFeedUploadLayout.stories.tsx
  src/components/feed/upload/layout/MobileFeedUploadLayout.tsx
  src/pages/community/upload.tsx
Labels: size/L

#1062 feat: 커뮤니티 피드 모바일 대응 (+DynamicImage 버그 fix)
  src/components/feed/common/Icon.tsx
  src/components/feed/detail/DetailFeedCard.stories.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/slider/DynamicImage.tsx
  src/components/feed/detail/slider/FeedImageSlider.stories.tsx
  src/components/feed/detail/slider/FeedImageSlider.tsx
  src/components/feed/list/FeedCard.stories.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
Labels: size/L

#1024 feat: 랜덤 리뷰어 워크플로 추가
  .github/actions/randomReviewer.js
  .github/workflows/assign-reviewer.yml
Labels: size/L

#1070 feat: 로그아웃시 인트로 페이지로 보내기
  src/components/auth/useAuth.ts
Labels: size/XS

#1068 feat: 더보기 드롭다운 추가, 클립보드 복사 유틸 훅 작성
  package.json
  src/components/feed/common/FeedDropdown.stories.tsx
  src/components/feed/common/FeedDropdown.tsx
  src/hooks/useCopyText.tsx
  yarn.lock
Labels: size/L

#1072 feat: 카테고리 get api 구현
  src/api/endpoint/feed/getCategory.ts
Labels: size/S

#1073 feat: 카테고리 가져오기 API 추가
  src/components/feed/common/queryParam.tsx
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/page/FeedHomePage.tsx
Labels: size/M

#1074 feat: 피드 리스트, 상세 api 연결
  package.json
  src/api/endpoint/feed/deleteComment.ts
  src/api/endpoint/feed/deletePost.ts
  src/api/endpoint/feed/getComment.ts
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/api/endpoint/feed/postComment.ts
  src/api/endpoint/feed/postPostHit.ts
  src/components/feed/common/utils.ts
  src/components/feed/detail/DetailFeedCard.stories.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/detail/slider/DynamicImage.tsx
  src/components/feed/detail/slider/FeedImageSlider.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/page/FeedHomePage.tsx
  yarn.lock
Labels: size/XL

#1075 feat: 피드 업로드 데이터 저장 로직 구현
  public/icons/icon-expand-more.svg
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategoryHeader/index.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/Category/CategorySelector/index.stories.tsx
  src/components/feed/upload/Category/CategorySelector/index.tsx
  src/components/feed/upload/Category/TagSelector/TagSelectOptions.tsx
  src/components/feed/upload/Category/TagSelector/index.stories.tsx
  src/components/feed/upload/Category/TagSelector/index.tsx
  src/components/feed/upload/Category/constants.ts
  src/components/feed/upload/Category/index.tsx
  src/components/feed/upload/Category/types.ts
  src/components/feed/upload/Input/ContentsInput/index.tsx
  src/components/feed/upload/Input/TitleInput/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesButton/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesPreview/index.tsx
  src/components/feed/upload/UsingRules/index.tsx
  src/components/feed/upload/hooks/useCategorySelect.ts
  src/components/feed/upload/hooks/useUploadFeedData.ts
  src/components/feed/upload/layout/DesktopFeedUploadLayout.stories.tsx
  src/components/feed/upload/layout/DesktopFeedUploadLayout.tsx
  src/components/feed/upload/layout/MobileFeedUploadLayout.stories.tsx
  src/components/feed/upload/types.ts
  src/hooks/useImageUploader.ts
  src/pages/community/upload.tsx
Labels: size/XL

#1077 feat: feed post api 구현
  src/api/endpoint/feed/uploadFeed.ts
Labels: size/L

#1082 feat: 피드 업로드 post api 연결
  src/api/endpoint/feed/uploadFeed.ts
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/ImageUploadButton/index.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
  src/components/feed/upload/types.ts
Labels: size/L

#1087 feat: 피드 및 피드 댓글 더보기 기능 추가
  src/api/endpoint/feed/deleteComment.ts
  src/api/endpoint/feed/deletePost.ts
  src/api/endpoint/feed/getPosts.ts
  src/components/common/Modal/useConfirm.tsx
  src/components/feed/common/FeedDropdown.tsx
  src/components/feed/common/hooks/useDeleteComment.ts
  src/components/feed/common/hooks/useDeleteFeed.ts
  src/components/feed/common/hooks/useShareFeed.ts
  src/components/feed/detail/DetailFeedCard.stories.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/detail/slider/DynamicImage.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
  src/constants/links.ts
Labels: size/L

#1088 fix: 이미지 슬라이더 위치 버그픽스
  src/components/feed/detail/slider/DynamicImage.tsx
  src/components/feed/detail/slider/FeedImageSlider.tsx
Labels: size/M

#1080 feat: 카테고리 get api 연결
  src/api/endpoint/feed/getCategory.ts
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategoryHeader/index.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/Category/TagSelector/TagSelectOptions.tsx
  src/components/feed/upload/Category/TagSelector/index.tsx
  src/components/feed/upload/Category/index.tsx
Labels: size/M

#1094 fix: 모바일에서 호버 이벤트 삭제
  src/components/feed/upload/Category/CategoryHeader/index.tsx
Labels: size/XS

#1093 feat: 커뮤니티 상세페이지 추가
  src/components/feed/common/hooks/useShareFeed.ts
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetail.tsx
  src/pages/feed/[id].tsx
  src/pages/projects/[id].tsx
  src/styles/global.ts
Labels: size/M

#1092 feat: 커뮤니티 업로드 > 코드 업로드 버튼 구현
  public/icons/img/carbon_code_block.png
  src/components/feed/upload/CodeUploadButton/index.stories.tsx
  src/components/feed/upload/CodeUploadButton/index.tsx
Labels: ✨ Feature, size/L

#1095 fix: 서버 스키마 오류 수정
  src/api/endpoint/feed/getComment.ts
  src/api/endpoint/feed/getPosts.ts
  src/api/typedAxios.ts
Labels: size/M

#1097 fix: 카테고리 모바일 이슈 수정
  src/components/feed/page/layout/MobileCommunityLayout.tsx
Labels: size/S

#1102 fix: 리스트에서도 댓글 익명으로 보이도록 수정
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
Labels: size/S

#1089 feat: 가장 최근 활동 파트 default 설정 구현
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/Category/CategorySelector/index.stories.tsx
  src/components/feed/upload/Category/CategorySelector/index.tsx
  src/components/feed/upload/Category/index.tsx
Labels: size/M

#1110 feat: 모바일 피드 상세 정책 변경
  src/components/feed/list/FeedList.tsx
  src/components/feed/page/FeedHomePage.tsx
  src/components/feed/page/layout/MobileCommunityLayout.tsx
Labels: size/M

#1111 fix: 질문 뱃지 nowrap 추가
  src/components/feed/list/FeedCard.tsx
Labels: size/XS

#1107 fix: 피드 > 드롭다운 수정, 삭제 버튼색 변경
  src/components/feed/list/FeedList.tsx
Labels: size/XS

#1112 feat: 카테고리 wrap 추가
  src/components/feed/list/CategorySelect.tsx
Labels: size/XS

#1106 feat: 커뮤니티 업로드 > 질문글/익명 체크박스, 코드 버튼 추가
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/CheckboxFormItem/index.stories.tsx
  src/components/feed/upload/CheckboxFormItem/index.tsx
  src/components/feed/upload/CodeUploadButton/index.tsx
Labels: ✨ Feature, size/L

#1113 fix: 댓글 추가시 리스트에서도 업데이트 되도록 수정
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/components/feed/common/hooks/useDeleteFeed.ts
  src/components/feed/detail/FeedDetail.tsx
Labels: size/S

#1096 refactor: 바텀시트 react-modal-sheet로 방식 변경
  src/components/common/BottomSheet/index.tsx
  src/components/feed/upload/Category/CategorySelector/index.tsx
  src/components/feed/upload/Category/TagSelector/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesDetail/index.tsx
Labels: size/L

#1114 chore: 불필요 코드 삭제
  src/components/common/BottomSheet/index.tsx
Labels: size/XS

#1115 feat: 피드 상세 태그 추가
  src/components/feed/common/hooks/useCurrentCategory.ts
  src/components/feed/detail/DetailFeedCard.stories.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/page/FeedHomePage.tsx
  src/constants/links.ts
  src/pages/feed/[id].tsx
Labels: size/L

#1117 fix: 피드 상세 URL 직접접근 오류 수정
  functions/feed/[id].ts
Labels: size/S

#1127 Update README.md
  README.md
Labels: size/S

#1119 refactor: 카테고리 정보 가져오는 훅 리팩터링
  src/components/feed/common/hooks/useCurrentCategory.ts
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetail.tsx
Labels: size/M

#1130 fix: 익명 글 및 댓글 작성시 member null로 내려오도록 수정된 것 타입 대응
  src/api/endpoint/feed/getComment.ts
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/components/feed/detail/DetailFeedCard.stories.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/list/FeedCard.stories.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
Labels: size/L

#1133 feat: 뒤로가기 정책 적용
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/page/FeedHomePage.tsx
  src/pages/feed/[id].tsx
Labels: size/M

#1131 feat: 피드 로딩과 에러 처리 추가
  src/components/feed/common/Icon.tsx
  src/components/feed/list/FeedList.tsx
Labels: size/M

#1121 feat: 피드 업로드 디테일 수정
  src/components/common/BottomSheet/index.tsx
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/CodeUploadButton/index.tsx
  src/components/feed/upload/Input/ContentsInput/index.tsx
  src/components/feed/upload/Input/TitleInput/index.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
Labels: size/M

#1126 fix: 업로드 피드 뒤로가기 구현
  src/components/feed/page/FeedUploadPage.tsx
Labels: size/S

#1124 fix: 피드 업로드시 카테고리 선택창이 자동으로 닫히는 문제 해결
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategoryHeader/index.tsx
  src/components/feed/upload/Category/TagSelector/TagSelectOptions.tsx
  src/components/feed/upload/Category/TagSelector/index.tsx
  src/components/feed/upload/Category/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesPreview/index.tsx
  src/components/feed/upload/UsingRules/index.tsx
  src/components/feed/upload/hooks/useCategorySelect.ts
  src/components/feed/upload/hooks/useUploadFeedData.ts
  src/components/feed/upload/types.ts
Labels: size/L

#1140 fix: 카테고리 셀렉터 버그 수정
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategoryHeader/index.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
Labels: size/S

#1147 feat: 글 상세에서 컨텐츠와 댓글에서 링크가 있을 경우 a 태그로 변경
  src/components/feed/detail/DetailFeedCard.tsx
  src/utils/parseTextToLink.tsx
Labels: size/M

#1141 fix: hasBlind, hasQuestion 타입 추가
  src/api/endpoint/feed/getCategory.ts
  src/components/feed/page/FeedUploadPage.tsx
Labels: size/M

#1137 fix: 피드 업로드 익명 경고 박스 구현
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/CheckboxFormItem/BlindWriterWarning/index.stories.tsx
  src/components/feed/upload/CheckboxFormItem/BlindWriterWarning/index.tsx
  src/components/feed/upload/layout/DesktopFeedUploadLayout.tsx
  src/components/feed/upload/layout/MobileFeedUploadLayout.tsx
Labels: size/L

#1148 chore: 커뮤니티 이용규칙 내용 수정
  src/components/common/BottomSheet/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesDetail/index.tsx
Labels: size/L

#1150 chore: 업로드 버튼 스타일 추가
  src/components/feed/list/FeedList.tsx
Labels: size/XS

#1154 chore: 솝티클 링크 변경
  src/components/sopticle/Success.tsx
  src/components/sopticle/UploadSopticle.tsx
Labels: size/XS

#1152 fix: 서버 타입 검증 에러 대응
  src/api/endpoint/feed/getPosts.ts
  src/components/feed/list/FeedList.tsx
Labels: size/M

#1158 feat: 커뮤니티 모바일 레이아웃 변경
  src/components/feed/common/FeedDropdown.tsx
  src/components/feed/page/FeedHomePage.tsx
  src/components/feed/page/layout/MobileCommunityLayout.tsx
  src/pages/feed/[id].tsx
Labels: size/M

#1160 feat: 글마다 작성중 댓글 따로 유지
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetail.tsx
Labels: size/S

#1156 fix: 업로드 css 수정
  src/components/common/BottomSheet/index.tsx
  src/components/common/Checkbox/index.tsx
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/UsingRules/UsingRulesDetail/index.tsx
  src/components/feed/upload/UsingRules/constants.ts
Labels: size/M

#1162 fix: 100vh 문제 해결
  src/components/common/Header/mobile/MobileSideBar.tsx
  src/components/feed/upload/Category/DropDown/index.tsx
  src/components/layout/FullScreenLayout.tsx
  src/components/layout/utils.ts
  src/components/members/detail/MessageSection/MessageModal.tsx
  src/components/wordchain/WordchainChatting/index.tsx
  src/pages/mentoring/[id].tsx
Labels: size/S

#1163 fix: 피드 API 형식 변경
  src/api/endpoint/feed/getPost.ts
  src/components/feed/detail/FeedDetail.tsx
Labels: size/M

#1164 feat: 피드 보기 에러 바운더리 추가
  package.json
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/detail/FeedDetailComments.tsx
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/detail/FeedDetailInput.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/list/FeedListItems.tsx
  yarn.lock
Labels: size/XL

#1165 feat: 데스크톱 레이아웃 구분선 추가
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/page/layout/DesktopCommunityLayout.tsx
Labels: size/S

#1161 feat: 익명 서약 모달 구현
  src/components/common/Modal/useAlert.tsx
  src/components/feed/common/hooks/useBlindWriterPromise.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
Labels: size/M

#964 refactor: 네이밍 변경 (essential -> required)
  src/components/members/upload/AddableItem.tsx
  src/components/members/upload/FormSection/Basic/index.tsx
  src/components/members/upload/forms/FormItem.tsx
Labels: 🛠 Refactor, size/S

#1166 feat: 업로드시 프론트에서 이미지 리사이징
  package.json
  src/components/common/ImageUploader/index.tsx
  src/components/feed/page/FeedUploadPage.tsx
  src/components/projects/upload/form/ListImageUploader.tsx
  src/hooks/useImageUploader.ts
  yarn.lock
Labels: size/M

#1169 fix: post후 데이터가 바로 get되도록
  src/api/endpoint/feed/uploadFeed.ts
Labels: size/S

#1171 피드카드, 상세 피드카드 전반적인 디자인 수정
  public/fonts/SUIT-Light.woff2
  public/fonts/SUIT-Regular.woff2
  src/components/common/Text/index.tsx
  src/components/feed/common/Icon.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailComments.tsx
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
  src/pages/_document.tsx
  src/styles/font.ts
  src/styles/mixin.ts
  src/styles/typography.ts
Labels: size/L

#1174 chore: 백버튼에 cursor pointer 추가하기
  src/components/feed/page/FeedUploadPage.tsx
Labels: size/XS

#1176 feat: 피드 디테일로 들어가지 않아도 수정 버튼 클릭 시 토스트 뜨도록 수정
  src/components/feed/list/FeedListItems.tsx
Labels: size/S

#1177 fix: 질문 글 아닌 경우에는 질문 칩 안 뜨도록 isQuestion 값 내려주기
  src/components/feed/detail/FeedDetailContent.tsx
Labels: size/XS

#1173 feat: 댓글 등록 시 로딩 추가
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailInput.tsx
Labels: size/S

#1178 feat: 커뮤니티 메인 AuthRequired 추가
  src/pages/community/index.tsx
  src/pages/feed/[id].tsx
Labels: size/XS

#1181 feat: 댓글 보낼 때 weblink 같이 보내도록 수정
  src/api/endpoint/feed/postComment.ts
  src/components/feed/detail/FeedDetailInput.tsx
  src/constants/links.ts
Labels: size/XS

#1184 fix: 레이아웃 zIndex로 인해 Modal이 뜨지 않는 이슈 수정
  src/components/common/Modal/index.tsx
  src/components/common/Modal/useAlert.tsx
  src/components/common/Modal/useConfirm.tsx
  src/components/feed/common/hooks/useDeleteComment.ts
  src/components/feed/common/hooks/useReportComment.ts
  src/components/feed/page/layout/MobileCommunityLayout.tsx
  src/styles/zIndex.ts
Labels: size/S

#1185 fix: 빈 텍스트 입력시 댓글 전송 막기
  src/components/feed/detail/FeedDetailInput.tsx
Labels: size/XS

#1186 Revert "chore: 익명박스 하단에 붙도록 수정 (#1180)"
  src/components/feed/detail/DetailFeedCard.tsx
Labels: size/XS

#1187 feat: 댓글 영역 flex:1 로 늘리기
  src/components/feed/detail/FeedDetailComments.tsx
Labels: size/XS

#1168 feat: 이미지 업로드 여러 장 가능하도록
  src/components/common/ImageUploader/index.tsx
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/ImageUploadButton/index.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
  src/components/projects/upload/form/ListImageUploader.tsx
  src/hooks/useImageUploader.ts
Labels: ✨ Feature, size/M

#1188 feat: 특수임원 예외처리
  src/components/feed/common/utils.ts
Labels: size/S

#1191 feat: 취업진로 카테고리에서 이름 나오게
  src/components/feed/common/utils.ts
Labels: size/S

#1193 feat: 댓글 입력창 길이 수정
  src/components/feed/detail/DetailFeedCard.tsx
Labels: size/XS

#1170 feat: 향상된 가로 스크롤 추가
  src/components/common/HorizontalScroller/index.tsx
  src/components/common/ScrollContainer/index.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/page/layout/DesktopCommunityLayout.tsx
  src/styles/mixin.ts
Labels: size/L

#1197 댓글 및 댓글 입력창 UI 전반적인 개선
  src/components/common/Loading/index.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailComments.tsx
  src/components/feed/list/FeedCard.tsx
Labels: size/L

#1194 chore: 이미지 부분과 커뮤니티 이용규칙 프리뷰 겹치는 문제 해결
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/CheckboxFormItem/BlindWriterWarning/index.tsx
  src/components/feed/upload/layout/MobileFeedUploadLayout.tsx
Labels: size/S

#1196 feat: 전체 뷰에서 게시글 카테고리 표기하기
  src/components/feed/common/utils.ts
  src/components/feed/list/FeedCard.stories.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
Labels: size/L

#1198 chore: 모바일에서 토스트 가운데 뜨도록 위치 수정
  src/components/common/Toast/ToastEntry.tsx
Labels: size/S

#1199 feat: 익명, 질문글 체크 후, 체크가 불가능한 카테고리로 이동시 체크박스 값 초기화 구현
  src/components/feed/upload/hooks/useUploadFeedData.ts
Labels: size/M

#1200 feat: 커뮤니티 이용규칙 프리뷰 최초 진입시에만 뜨도록 수정
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/hooks/useCategorySelect.ts
Labels: size/S

#1201 chore: css 수정
  src/components/common/Modal/useConfirm.tsx
  src/components/feed/common/hooks/useBlindWriterPromise.tsx
  src/components/feed/common/hooks/useDeleteComment.ts
  src/components/feed/common/hooks/useDeleteFeed.ts
  src/components/feed/common/hooks/useReportFeed.ts
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailComments.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/upload/Input/ContentsInput/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesDetail/index.tsx
Labels: size/M

#1202 feat: tag가 없는 카테고리인 경우, 표시하지 않기
  src/components/feed/common/hooks/useCategory.ts
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetail.tsx
Labels: size/M

#1208 feat: 신고 후 확인 모달 구현
  public/icons/check_box_field.svg
  src/components/common/Modal/usePopup.tsx
  src/components/feed/common/hooks/useReportFeed.ts
Labels: size/M

#1210 feat: 피드 디테일에서 프로필 클릭 시, 프로필 페이지로 이동
  src/components/common/Text/index.tsx
  src/components/feed/common/hooks/useMoveToProfile.tsx
  src/components/feed/detail/DetailFeedCard.stories.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailComments.tsx
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/list/FeedCard.stories.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
Labels: size/L

#1212 chore: 커서 포인터 없애고, onClick이벤트 Link로 변경
  src/components/feed/common/hooks/useMoveToProfile.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/list/FeedCard.tsx
Labels: size/L

#1213 chore: 오버플로우 속성 추가
  src/components/common/BottomSheet/index.tsx
Labels: size/XS

#1214 chore: css 디테일 더하기
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailComments.tsx
  src/components/feed/upload/UsingRules/UsingRulesDetail/index.tsx
Labels: size/S

#1215 chore: 소소한 css 수정 (댓글 resize none, 인포 ellipsis 처리)
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/FeedCard.tsx
Labels: size/S

#1211 fix: 가로 스크롤 버튼 클릭 오류 수정
  src/components/common/HorizontalScroller/index.tsx
Labels: size/S

#1216 feat: 커뮤니티 몇몇 디테일 추가
  src/components/common/Text/index.tsx
  src/components/feed/detail/DetailFeedCard.tsx
Labels: size/S

#1218 feat: 모바일 화면 메뉴 진입 아이콘 추가
  src/components/feed/list/MenuEntryIcons/Icons.tsx
  src/components/feed/list/MenuEntryIcons/MenuEntryIcons.tsx
  src/components/feed/page/layout/MobileCommunityLayout.tsx
Labels: size/L
