Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-04, with the labels that each got.

#608 fix: 활동 정보 정렬
  components/members/main/MemberDetail/index.tsx
Labels: size/S

#611 fix: 활동정보 모바일 스타일 수정
  components/members/detail/PartItem.tsx
Labels: size/XS

#620 feat: 스터디 모집 배너 제거
  pages/members/index.tsx
  pages/projects/index.tsx
Labels: size/XS

#618 feat: amplitude pageview 추가
  components/eventLogger/controllers/amplitude.ts
  components/eventLogger/controllers/consoleLog.ts
  components/eventLogger/controllers/storybookAction.ts
  components/eventLogger/events.ts
  components/eventLogger/hooks/useEventLogger.ts
  components/eventLogger/types.ts
  components/members/main/MemberDetail/index.tsx
  components/members/main/MemberList/index.tsx
  hooks/useRunOnce.ts
Labels: size/M

#624 feat: 이메일 회원인증 제거
  components/auth/register/verify/Verify.tsx
  components/auth/register/verify/VerifyFrame.stories.tsx
  components/auth/register/verify/VerifyFrame.tsx
  components/auth/register/verify/useByEmail.ts
  components/auth/register/verify/view/ByEmailView.stories.tsx
  components/auth/register/verify/view/ByEmailView.tsx
Labels: size/L

#626 feat: iOS 심사용 루트 추가
  api/auth/index.ts
  components/auth/register/verify/Verify.tsx
  components/auth/register/verify/useByPhone.ts
Labels: size/M

#627 chore: 프로필 업로드 > 공홈 공개 관련 텍스트 수정
  components/members/upload/FormSection/PublicQuestion.tsx
Labels: size/XS

#621 fix: 멤버 업로드 > EditableSelect 스타일 수정, 스토리 추가
  components/common/EditableSelect.stories.tsx
  components/common/EditableSelect.tsx
  components/members/upload/FormSection/Career.tsx
Labels: size/M

#629 feat: 애플 로그인 구현
  .env.development
  api/auth/index.ts
  components/auth/identityProvider/apple/AppleAuthButton.tsx
  components/auth/identityProvider/apple/useAppleAuth.ts
  components/auth/register/Register.tsx
  components/auth/states/lastLoginMethodAtom.ts
  components/eventLogger/events.ts
  constants/env.ts
  pages/auth/callback/apple/login.tsx
  pages/auth/callback/apple/register.tsx
  pages/auth/login.tsx
Labels: size/L

#634 feat: SOPT 1차 행사 배너 제작
  components/common/Banner/SOPTEventBanner/DesktopEventBanner.tsx
  components/common/Banner/SOPTEventBanner/MobileEventBanner.tsx
  components/common/Banner/SOPTEventBanner/constants.ts
  components/common/Banner/SOPTEventBanner/index.tsx
  components/common/Banner/StudyBanner/CountdownTimer.tsx
  components/common/Banner/StudyBanner/DesktopStudyBanner.tsx
  components/common/Banner/StudyBanner/index.tsx
  pages/members/index.tsx
  pages/projects/index.tsx
Labels: size/L

#635 fix: iOS 딥링크 오류 수정
  components/auth/oauth/OAuthCallback.tsx
  components/auth/oauth/whitelists.ts
Labels: size/S

#636 feat: oauth 자세한 오류 메시지 추가
  components/auth/oauth/OAuthCallback.tsx
Labels: size/XS

#639 fix: target='_blank' 제거
  components/common/Banner/SOPTEventBanner/constants.ts
  components/common/Banner/SOPTEventBanner/index.tsx
Labels: size/XS

#641 fix: 아이폰 사파리 인증 오류 대응
  components/auth/oauth/OAuthCallback.tsx
Labels: size/XS

#642 feat: 인증 후 딥링크 동작 방식 변경
  components/auth/oauth/OAuthCallback.tsx
Labels: size/M

#643 chore: 글로벌 스타일 button 태그에 cursor: pointer; 추가
  styles/global.ts
Labels: size/XS

#646 feat: 1차행사 모집 배너 철거
  pages/members/index.tsx
  pages/projects/index.tsx
Labels: size/XS

#644 feat: 이메일 없는 유저에게 쪽지 보내려고 할 경우, 쪽지 보낼 수 없다는 토스트 띄우기
  components/common/Modal/index.tsx
  components/common/Toast/ToastEntry.tsx
  components/members/main/MemberDetail/Section/Interest.stories.tsx
  components/members/main/MemberDetail/Section/Interest.tsx
  components/members/main/MemberDetail/Section/Message.stories.tsx
  components/members/main/MemberDetail/Section/Message.tsx
  components/members/main/MemberDetail/Section/index.ts
  components/members/main/MemberDetail/index.tsx
Labels: ✨ Feature, size/L

#649 refactor: 멤버 상세 컴포넌트 폴더링 개선
  components/members/detail/InterestSection/index.stories.tsx
  components/members/detail/InterestSection/index.tsx
  components/members/detail/MemberDetail.tsx
  components/members/detail/MemberDetailSection.ts
  components/members/detail/MessageSection/CoffeeChatModal.stories.tsx
  components/members/detail/MessageSection/CoffeeChatModal.tsx
  components/members/detail/MessageSection/index.stories.tsx
  components/members/detail/MessageSection/index.tsx
  pages/members/[id].tsx
Labels: 🛠 Refactor, size/S

#653 fix: 푸터에 맞춰 토스트 위치 변경
  components/common/Toast/providers/ToastProvider.tsx
Labels: 🐛 Bug, size/XS

#656 refactor: 쪽지를 Message로 네이밍 통일
  components/members/detail/MessageSection/MessageModal.stories.tsx
  components/members/detail/MessageSection/MessageModal.tsx
  components/members/detail/MessageSection/index.tsx
Labels: 🛠 Refactor, size/M

#657 refactor: 프로필 디테일 > InterestSection 다른 섹션과 구조 통일
  components/members/detail/InterestSection/index.stories.tsx
  components/members/detail/InterestSection/index.tsx
  components/members/detail/MemberDetail.tsx
  components/members/detail/MessageSection/index.tsx
Labels: 🛠 Refactor, size/M

#659 feat: 프로필 상세 > 커리어 영역 디자인 변경
  api/members/type.ts
  components/members/detail/CareerItem.tsx
  components/members/detail/CareerSection/CareerItem.stories.tsx
  components/members/detail/CareerSection/CareerItem.tsx
  components/members/detail/CareerSection/index.stories.tsx
  components/members/detail/CareerSection/index.tsx
  components/members/detail/MemberDetail.tsx
Labels: ✨ Feature, size/L

#660 fix: 누락된 null 체크
  components/members/detail/CareerSection/index.tsx
  components/members/detail/MemberDetail.tsx
Labels: 🐛 Bug, size/XS

#666 feat: 멤버 프로필 모바일 헤더 삭제
  components/common/MobileHeader/index.tsx
  pages/members/[id].tsx
Labels: size/M

#665 feat: 멤버 프로필 리스트 카드 리디자인
  .yarn/cache/@radix-ui-react-aspect-ratio-npm-1.0.2-b00447a940-cbad29a82b.zip
  .yarn/cache/@radix-ui-react-tooltip-npm-1.0.5-7c34bded26-621929e92d.zip
  components/members/detail/MemberDetail.tsx
  components/members/detail/MessageSection/MessageModal.stories.tsx
  components/members/detail/MessageSection/MessageModal.tsx
  components/members/detail/MessageSection/index.stories.tsx
  components/members/detail/MessageSection/index.tsx
  components/members/main/MemberCard/MessageButton.tsx
  components/members/main/MemberCard/index.stories.tsx
  components/members/main/MemberCard/index.tsx
  components/members/main/MemberList/index.tsx
  package.json
  pages/members/index.tsx
  public/icons/icon-message.svg
  styles/colors.ts
  styles/typography.ts
  yarn.lock
Labels: size/XL

#663 chore: 프로젝트 카테고리 기타 -> 사이드 프로젝트 워딩 변경
  components/members/detail/constants.ts
  components/projects/form/fields/CategoryField.tsx
  components/projects/upload/ProjectCategory.tsx
  components/projects/upload/constants.ts
Labels: size/XS

#669 fix: 프로필 상세 > 프로젝트 뱃지에 프로젝트 카테고리 모두 표시되도록
  api/members/type.ts
  api/projects/type.ts
  components/members/detail/MemberDetail.tsx
  components/projects/upload/constants.ts
Labels: size/M

#668 refactor: Career 타입 구별된 유니온으로 정확한 타이핑 할 수 있도록 하기
  api/members/type.ts
  components/members/detail/types.ts
  components/members/upload/constants.ts
  components/members/upload/types.ts
  pages/members/edit.tsx
Labels: 🛠 Refactor, size/M

#670 fix: 멤버 카드 오류 수정
  components/members/main/MemberCard/index.stories.tsx
  components/members/main/MemberCard/index.tsx
  components/members/main/MemberList/index.tsx
Labels: size/M

#672 refactor: 기존 API 파일 레거시화
  api/endpoint_LEGACY/auth/index.ts
  api/endpoint_LEGACY/hooks/index.ts
  api/endpoint_LEGACY/hooks/members.ts
  api/endpoint_LEGACY/hooks/projects.ts
  api/endpoint_LEGACY/image/index.ts
  api/endpoint_LEGACY/makers/index.ts
  api/endpoint_LEGACY/makers/types.ts
  api/endpoint_LEGACY/members/index.ts
  api/endpoint_LEGACY/members/type.ts
  api/endpoint_LEGACY/projects/index.ts
  api/endpoint_LEGACY/projects/type.ts
  components/auth/identityProvider/apple/useAppleAuth.ts
  components/auth/identityProvider/facebook/useFacebookAuth.ts
  components/auth/identityProvider/google/useGoogleAuth.ts
  components/auth/oauth/OAuthCallback.tsx
  components/auth/register/verify/useByPhone.ts
  components/common/Header/index.tsx
  components/common/ImageUploader/Legacy.tsx
  components/common/ImageUploader/index.tsx
  components/eventLogger/providers/AmplitudeProvider.tsx
  components/members/common/WithMemberMetadata.tsx
  components/members/detail/CareerSection/index.tsx
  components/members/detail/MemberDetail.tsx
  components/members/detail/MemberProjectCard.tsx
  components/members/detail/MessageSection/MessageModal.tsx
  components/members/main/MemberList/index.tsx
  components/members/main/hooks/useMemberProfileQuery.ts
  components/projects/main/ProjectCard.tsx
  components/projects/main/ProjectDetail.tsx
  components/projects/upload/MemberForm/MemberSearch.tsx
  components/projects/upload/MemberForm/constants.ts
  components/projects/upload/ProjectImageSection.tsx
  components/projects/upload/constants.ts
  components/projects/upload/hooks/useCreateProjectMutation.ts
  components/projects/upload/hooks/useGetMembersByNameQuery.ts
  components/projects/upload/hooks/useGetProjectListQuery.ts
  components/projects/upload/hooks/useGetProjectQuery.ts
  pages/auth/register.tsx
  pages/makers/index.tsx
  pages/members/edit.tsx
  pages/members/index.tsx
  pages/members/upload.tsx
  pages/projects/upload/index.tsx
Labels: size/M

#674 feat: TypedAxios 모듈 생성
  api/endpoint/makers/index.ts
  api/endpoint/members/index.ts
  api/endpoint_LEGACY/hooks/members.ts
  api/typedAxios.ts
  components/projects/upload/hooks/useGetMembersByNameQuery.ts
  pages/makers/index.tsx
Labels: size/L

#677 fix: 프로필 업로드 > 커리어 validate 버그 fix
  components/members/upload/schema.ts
Labels: 🐛 Bug, size/XS
