Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-03, with the labels that each got.

#475 fix: 구글 로그인 오류 수정
  pages/auth/callback/google/login.tsx
  pages/auth/callback/google/register.tsx
Labels: 🐛 Bug, ⚡️ Urgent, size/S

#474 feat: CategoryField 추가
  components/projects/form/ProjectForm.tsx
  components/projects/form/fields/CategoryField.stories.tsx
  components/projects/form/fields/CategoryField.tsx
  components/projects/form/fields/GenerationField.tsx
  components/projects/form/schema.ts
Labels: size/L

#478 feat: 메이커스 정보 엔드포인트 변경
  api/makers/index.ts
  api/makers/types.ts
  pages/makers/index.tsx
Labels: size/M

#481 fix: 이메일 입력 인풋 크기 수정
  components/auth/register/VerifyByEmail.tsx
Labels: size/XS

#480 feat: 멤버 리스트 페이지네이션 api interface 변경 대응
  api/members/index.ts
  api/members/type.ts
  components/members/common/WithMemberMetadata.tsx
  components/members/main/MemberList/index.tsx
  components/members/main/hooks/useMemberProfileQuery.ts
Labels: size/M

#483 feat: OAuth 플로우 구현
  api/auth/index.ts
  components/auth/identityProvider/facebook/useFacebookAuth.ts
  components/auth/identityProvider/google/useGoogleAuth.ts
  components/auth/oauth/OAuthCallback.tsx
  components/auth/oauth/whitelists.ts
  components/auth/register/VerifyByEmail.tsx
  pages/auth/oauth.tsx
  pages/auth/register.tsx
Labels: size/L

#487 fix: 모바일 헤더 프로필 이미지 수정
  components/common/Header/mobile/MobileSideBar.tsx
Labels: size/XS

#485 feat: Select 구현
  .yarn/cache/@radix-ui-number-npm-1.0.0-b3aa2fa871-517ac0790e.zip
  .yarn/cache/@radix-ui-react-arrow-npm-1.0.2-a5b307fce8-d9c4a81037.zip
  .yarn/cache/@radix-ui-react-collection-npm-1.0.2-2b90742ccd-f7d92f52c7.zip
  .yarn/cache/@radix-ui-react-dismissable-layer-npm-1.0.3-426aece87b-cb2a38a65d.zip
  .yarn/cache/@radix-ui-react-focus-scope-npm-1.0.2-0b3c5abaa0-f04f7412c8.zip
  .yarn/cache/@radix-ui-react-popper-npm-1.1.1-abba226c1f-d9be4be002.zip
  .yarn/cache/@radix-ui-react-portal-npm-1.0.2-dacc9f2542-1165b4bced.zip
  .yarn/cache/@radix-ui-react-scroll-area-npm-1.0.3-8c3e3c7f95-54f6d604f9.zip
  .yarn/cache/@radix-ui-react-select-npm-1.2.1-dcf8efaa36-884b00af83.zip
  .yarn/cache/@radix-ui-react-use-previous-npm-1.0.0-9262a82c5e-b45bbc8a7e.zip
  .yarn/cache/@radix-ui-react-visually-hidden-npm-1.0.2-e3319b1bfa-67c4a55cfa.zip
  components/members/common/select/Select.stories.tsx
  components/members/common/select/Select.tsx
  package.json
  public/icons/icon-select-arrow.svg
  yarn.lock
Labels: size/L

#491 feat: playground-common 패키지 버전 업
  playground-common/package.json
Labels: size/XS

#492 chore: ScrollBar 보이는 조건 수정
  components/members/common/select/Select.tsx
Labels: size/XS

#489 feat: 메이커스 2기 정보 추가
  components/makers/MakersMembers.tsx
  components/makers/data/generation2.ts
  components/makers/data/index.ts
Labels: size/L

#495 refactor: 프로필 업로드와 디테일 타입 의존성 분리
  components/members/detail/ActivityBadge.tsx
  components/members/detail/CareerItem.tsx
  components/members/detail/MemberProjectCard.tsx
  components/members/detail/constants.ts
  components/members/detail/types.ts
Labels: 🛠 Refactor, size/S

#498 Fix: 스토리북 배경 색상 수정
  .storybook/preview.js
Labels: size/XS

#502 fix: 잘못된 메이커스 멤버 정보 수정
  components/makers/data/generation2.ts
Labels: size/XS

#507 chore: React Query v3 -> v4 마이그레이션
  .storybook/preview.js
  .yarn/cache/@tanstack-query-core-npm-4.27.0-2fd798e498-914b4f01ac.zip
  .yarn/cache/@tanstack-react-query-npm-4.27.0-a8d6af73e5-15cebe9ccb.zip
  .yarn/cache/broadcast-channel-npm-3.7.0-81ceba70bb-803794c48d.zip
  .yarn/cache/detect-node-npm-2.1.0-e8de0e94f7-832184ec45.zip
  .yarn/cache/js-sha3-npm-0.8.0-decf3ddcfa-75df77c1fc.zip
  .yarn/cache/match-sorter-npm-6.3.1-ff3565ebb9-a4b02b676a.zip
  .yarn/cache/microseconds-npm-0.2.0-dbdb8ab8bb-22bfa8553f.zip
  .yarn/cache/nano-time-npm-1.0.0-6eca938be8-eef8548546.zip
  .yarn/cache/oblivious-set-npm-1.0.0-8e7336b241-f31740ea9c.zip
  .yarn/cache/react-query-npm-3.38.0-396d538e0a-9318952a3e.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/unload-npm-2.2.0-c40df6b4d0-88ba950c5f.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  api/hooks/members.ts
  api/hooks/projects.ts
  components/auth/callback/OAuthLoginCallback.tsx
  components/auth/register/VerifyByEmail.tsx
  components/common/Example/index.tsx
  components/members/main/MemberList/index.tsx
  components/members/main/hooks/useMemberProfileQuery.ts
  components/projects/upload/hooks/useCreateProjectMutation.ts
  components/projects/upload/hooks/useGetMembersByNameQuery.ts
  components/projects/upload/hooks/useGetProjectListQuery.ts
  components/projects/upload/hooks/useGetProjectQuery.ts
  package.json
  pages/_app.tsx
  pages/auth/register.tsx
  pages/projects/upload/index.tsx
  yarn.lock
Labels: size/L

#512 chore: react query devtools 추가
  .yarn/cache/@tanstack-match-sorter-utils-npm-8.7.6-2bff79c61d-3f3dda277e.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-4.27.0-c0226c9b6e-0477a08285.zip
  .yarn/cache/copy-anything-npm-3.0.3-a24d77ec4d-d456dc5ec9.zip
  .yarn/cache/is-what-npm-4.1.8-57bef8cfbc-b9bec3acff.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/superjson-npm-1.12.2-e37d205ed2-cf7735e172.zip
  package.json
  pages/_app.tsx
  yarn.lock
Labels: size/M

#513 feat: 32기 로고 추가, 모바일 버전 아이콘 안뜨는 이슈 수정
  components/members/detail/PartItem.tsx
  public/icons/logo/time=32.svg
Labels: size/S

#509 feat: member api 변경사항 대응, 새로운 필드 추가
  api/members/type.ts
  components/members/detail/InfoItem.tsx
  components/members/main/MemberDetail/InterestSection.stories.tsx
  components/members/main/MemberDetail/InterestSection.tsx
  components/members/main/MemberDetail/index.tsx
  components/members/upload/AdditionalInfoFormSection.tsx
  components/members/upload/constants.ts
  components/members/upload/schema.ts
  components/members/upload/types.ts
  pages/members/edit.tsx
Labels: size/XL

#516 feat: 파트 텍스트 누락 수정
  components/members/detail/PartItem.tsx
Labels: size/S

#515 fix: 업로드 페이지에서 수정 로직 분리 덜 된 작업 추가
  components/members/upload/BasicFormSection.tsx
Labels: 🐛 Bug, size/S

#506 feat: 로그인 페이지 개선
  components/auth/identityProvider/facebook/FacebookButton.tsx
  components/auth/identityProvider/google/GoogleAuthButton.tsx
  pages/auth/login.tsx
Labels: size/L

#503 feat: 전화번호 인증 후 가입
  .yarn/cache/await-to-js-npm-3.0.0-e2a325d38a-b6e9dcf9f0.zip
  api/auth/index.ts
  components/auth/register/Register.tsx
  components/auth/register/Stepper.stories.tsx
  components/auth/register/Stepper.tsx
  components/auth/register/VerifyByEmail.tsx
  components/auth/register/verify/HelpCard.stories.tsx
  components/auth/register/verify/HelpCard.tsx
  components/auth/register/verify/SendingMailSuccess.tsx
  components/auth/register/verify/Verify.stories.tsx
  components/auth/register/verify/Verify.tsx
  components/auth/register/verify/VerifyFrame.stories.tsx
  components/auth/register/verify/VerifyFrame.tsx
  components/auth/register/verify/VerifySubmitButton.tsx
  components/auth/register/verify/useByEmail.ts
  components/auth/register/verify/useByPhone.ts
  components/auth/register/verify/view/ByEmailView.stories.tsx
  components/auth/register/verify/view/ByEmailView.tsx
  components/auth/register/verify/view/ByPhoneView.stories.tsx
  components/auth/register/verify/view/ByPhoneView.tsx
  components/common/Input/ErrorMessage.tsx
  components/common/Input/index.tsx
  constants/links.ts
  package.json
  pages/auth/register.tsx
  pages/auth/verify.tsx
  yarn.lock
Labels: size/XXL

#518 feat: 프로필 업로드 > 이메일 필수 항목으로 변경
  components/members/upload/BasicFormSection.tsx
  components/members/upload/schema.ts
Labels: ✨ Feature, size/XS

#521 feat: 메이커스 소개 모바일 헤더 디자인 수정
  components/common/Header/SwitchableHeader.tsx
  components/makers/data/generation2.ts
Labels: size/XS

#524 fix: 프로필 상세 > 누락된 텍스트 추가
  components/members/detail/PartItem.tsx
Labels: 🐛 Bug, size/XS

#528 fix: 무한스크롤 오류 수정
  components/members/main/MemberList/index.tsx
Labels: size/S

#522 feat: 프로필 업로드 > MBTI 항목 추가
  .vscode/settings.json
  components/members/upload/TmiSection/MbtiSelector.tsx
  components/members/upload/TmiSection/MbtiToggle.tsx
  components/members/upload/TmiSection/constants.ts
  components/members/upload/TmiSection/index.stories.tsx
  components/members/upload/TmiSection/index.tsx
  components/members/upload/TmiSection/types.ts
  components/members/upload/constants.ts
  components/members/upload/forms/FormItem.tsx
  components/members/upload/forms/FormSection.ts
  components/members/upload/schema.ts
  components/members/upload/types.ts
Labels: ✨ Feature, size/L

#527 fix: 로그인 오류 표시 수정
  components/auth/callback/OAuthLoginCallback.tsx
Labels: size/XS

#533 feat: 프로필 업로드 > TMI 섹션에 '나는 어느 쪽?' 항목 추가
  components/members/upload/TmiSection/FavorToggle.tsx
  components/members/upload/TmiSection/index.tsx
  components/members/upload/TmiSection/types.ts
  components/members/upload/types.ts
Labels: ✨ Feature, size/L

#529 feat: 프로필 업로드 > 기본 정보 섹션 디자인 변경 사항 반영
  components/members/upload/AdditionalInfoFormSection.tsx
  components/members/upload/BasicFormSection.tsx
  components/members/upload/BasicFormSection/index.stories.tsx
  components/members/upload/forms/CountableInput.tsx
  components/members/upload/forms/CountableTextArea.tsx
  pages/members/upload.tsx
Labels: ✨ Feature, size/L

#534 fix: TMI 섹션 > hover 스타일 추가
  components/members/upload/TmiSection/FavorToggle.tsx
  components/members/upload/TmiSection/MbtiToggle.tsx
Labels: size/XS

#537 feat: 윈도우 클론 오류 수정
  components/members/main/MemberDetail/CoffeeChatModal.stories.tsx
Labels: size/XS

#535 refactor: components/members/upload 폴더 구조 개선
  components/members/upload/forms/Form.tsx
  components/members/upload/sections/AdditionalInfoFormSection.tsx
  components/members/upload/sections/BasicFormSection/index.stories.tsx
  components/members/upload/sections/BasicFormSection/index.tsx
  components/members/upload/sections/CareerFormSection.tsx
  components/members/upload/sections/PublicQuestionFormSection.tsx
  components/members/upload/sections/SoptActivityFormSection.tsx
  components/members/upload/sections/TmiSection/FavorToggle.tsx
  components/members/upload/sections/TmiSection/MbtiSelector.tsx
  components/members/upload/sections/TmiSection/MbtiToggle.tsx
  components/members/upload/sections/TmiSection/constants.ts
  components/members/upload/sections/TmiSection/index.stories.tsx
  components/members/upload/sections/TmiSection/index.tsx
  components/members/upload/sections/TmiSection/types.ts
  components/members/upload/types.ts
  pages/members/edit.tsx
  pages/members/upload.tsx
Labels: 🛠 Refactor, size/M

#540 feat: 프로필 업로드 > TMI 섹션 주량, 관심사, 자기소개, 이상형 추가
  components/members/common/select/Select.tsx
  components/members/upload/constants.ts
  components/members/upload/sections/TmiSection/FavorToggle.tsx
  components/members/upload/sections/TmiSection/MbtiSelector.tsx
  components/members/upload/sections/TmiSection/MbtiToggle.tsx
  components/members/upload/sections/TmiSection/index.tsx
  components/members/upload/types.ts
Labels: ✨ Feature, size/L

#536 feat: 마지막 로그인 메시지 추가
  components/auth/states/lastLoginMethodAtom.ts
  pages/auth/callback/facebook/login.tsx
  pages/auth/callback/facebook/register.tsx
  pages/auth/callback/google/login.tsx
  pages/auth/callback/google/register.tsx
  pages/auth/login.tsx
Labels: size/M

#538 fix: 로그인 화면 레이아웃 시프트 수정
  pages/auth/login.tsx
Labels: size/XS

#547 fix: 프로필 업로드 안되는 버그 fix
  components/members/upload/schema.ts
  components/members/upload/sections/TmiSection/index.stories.tsx
Labels: 🐛 Bug, size/S

#545 feat: 프로필 상세 > 이메일이 있어야 쪽지 보낼 수 있도록 하기
  components/members/main/MemberDetail/index.tsx
Labels: size/XS

#551 refactor: MBTI 항목 폼 데이터 관리 방식 개선
  components/members/upload/sections/TmiSection/MbtiSelector.tsx
  components/members/upload/sections/TmiSection/MbtiToggle.tsx
  components/members/upload/sections/TmiSection/constants.ts
  components/members/upload/sections/TmiSection/index.tsx
  components/members/upload/sections/TmiSection/types.ts
Labels: 🛠 Refactor, size/M

#553 chore: 프로필 상세 api 변경 사항 대응 (userFavor)
  api/members/type.ts
  components/members/main/MemberDetail/index.tsx
Labels: size/M

#550 feat: 액세스 토큰 오류시 로그아웃
  components/auth/AuthRequired.tsx
Labels: size/M

#554 feat: TMI 섹션 프로필 업로드/수정 페이지에 추가하기
  api/members/index.ts
  api/members/type.ts
  components/common/EditableSelect.tsx
  components/members/upload/constants.ts
  components/members/upload/format.ts
  components/members/upload/schema.ts
  components/members/upload/sections/TmiSection/index.tsx
  components/members/upload/sections/TmiSection/types.ts
  components/members/upload/utils.ts
  pages/members/edit.tsx
  pages/members/upload.tsx
Labels: ✨ Feature, size/L

#556 fix: 프로필 자유로운 자기소개 > 상세 스타일 버그 fix, 수정/업로드 글자수 제한
  components/members/main/MemberDetail/InterestSection.tsx
  components/members/upload/forms/CountableTextArea.tsx
  components/members/upload/sections/TmiSection/index.tsx
Labels: 🐛 Bug, size/M

#564 chore: 프로필 업로드 > 이름, 이메일, 전화번호 placeholder 추가
  components/members/upload/sections/BasicFormSection/index.tsx
Labels: size/XS

#568 fix: 프로필 업로드 > AddableItem 첫번쨰 원소는 삭제할 수 없게 하기
  components/members/upload/AddableItem.tsx
  components/members/upload/sections/CareerFormSection.tsx
  components/members/upload/sections/SoptActivityFormSection.tsx
Labels: 🐛 Bug, size/M

#570 hotfix: userFavor null 체크 및 기본값 설정
  components/members/main/MemberDetail/index.tsx
  components/members/upload/constants.ts
  pages/members/edit.tsx
Labels: 🐛 Bug, size/M

#549 feat: 이미지 업로더 수정/삭제 기능 추가
  components/common/ImageUploader/Legacy.tsx
  components/common/ImageUploader/index.tsx
  components/projects/upload/ProjectImageSection.tsx
  public/icons/icon-cancel.svg
  public/icons/icon-pencil.svg
Labels: ✨ Feature, size/L

#574 fix: 프로필 상세 > 자유로운 자기소개 개행 되도록
  components/members/main/MemberDetail/InterestSection.tsx
Labels: 🐛 Bug, size/XS

#572 fix: 프로필 업로드 > AddableItem 사용성 개선
  components/members/upload/sections/CareerFormSection.tsx
  components/members/upload/sections/SoptActivityFormSection.tsx
  pages/members/edit.tsx
Labels: size/S

#559 fix: 프로필 없음 표시 안되는 오류 수정
  components/members/main/MemberDetail/index.tsx
Labels: size/L

#575 feat: Amplitude 트리거 추가
  components/auth/register/Register.tsx
  components/auth/register/verify/Verify.tsx
  components/common/Footer/index.tsx
  components/common/Header/index.tsx
  components/eventLogger/controllers/amplitude.ts
  components/eventLogger/controllers/consoleLog.ts
  components/eventLogger/controllers/storybookAction.ts
  components/eventLogger/events.ts
  components/eventLogger/hooks/useEventLogger.ts
  components/eventLogger/providers/AmplitudeProvider.tsx
  components/eventLogger/types.ts
  components/members/main/MemberDetail/index.tsx
  components/members/main/MemberList/OnBoardingBanner.tsx
  components/members/main/MemberList/index.tsx
  pages/_app.tsx
  pages/auth/login.tsx
  pages/members/edit.tsx
Labels: size/L

#577 fix: Amplitude id 오류 수정
  components/eventLogger/controllers/amplitude.ts
Labels: size/XS

#579 feat: 전화번호 인증 오류 추가
  components/auth/register/verify/regex.ts
  components/auth/register/verify/useByPhone.ts
  components/auth/register/verify/view/ByPhoneView.tsx
  components/members/upload/schema.ts
  pages/auth/login.tsx
Labels: size/S

#578 feat: 기수 필터 추가 및 기존 MemberSelectDropdown Select로 변경
  components/members/common/select/Overlay.tsx
  components/members/common/select/Select.stories.tsx
  components/members/common/select/Select.tsx
  components/members/main/MemberCard/index.tsx
  components/members/main/MemberList/GenerationSelect.stories.tsx
  components/members/main/MemberList/GenerationSelect.tsx
  components/members/main/MemberList/MemberRoleMenu/MemberRoleMenu.stories.tsx
  components/members/main/MemberList/MemberRoleMenu/MemberRoleMenu.tsx
  components/members/main/MemberList/MemberRoleMenu/MemberRoleSelect.stories.tsx
  components/members/main/MemberList/MemberRoleMenu/MemberRoleSelect.tsx
  components/members/main/MemberList/MemberRoleMenu/constants.ts
  components/members/main/MemberList/MemberRoleMenu/index.ts
  components/members/main/MemberList/MemberSearch.tsx
  components/members/main/MemberList/index.tsx
  components/members/main/MemberRoleMenu/MemberRoleDropdown.stories.tsx
  components/members/main/MemberRoleMenu/MemberRoleDropdown.tsx
  components/members/main/MemberRoleMenu/index.stories.tsx
  components/members/main/MemberRoleMenu/index.tsx
  components/members/main/MemberRoleMenu/useMemberRoleMenu.ts
  components/members/upload/sections/TmiSection/index.tsx
  public/icons/icon-search-clear.svg
  public/icons/icon-select-arrow.svg
Labels: size/XL

#580 fix: member List 수정
  components/members/common/select/Select.tsx
  components/members/main/MemberList/GenerationSelect.stories.tsx
  components/members/main/MemberList/GenerationSelect.tsx
  components/members/main/MemberList/MemberSearch.tsx
  components/members/main/MemberList/index.tsx
  components/members/upload/sections/TmiSection/index.tsx
Labels: size/M

#583 fix: 멤버 리스트 패칭 동작 오류 수정
  components/members/main/MemberList/index.tsx
  components/members/main/hooks/useMemberProfileQuery.ts
Labels: size/XS

#585 feat: 기수필터 Amplitude 추가
  components/eventLogger/events.ts
  components/members/main/MemberList/index.tsx
Labels: size/XS

#584 feat: FormAccordion 이용해서 커리어 섹션 모바일 접기 대응
  components/common/form/FormCollapsible.tsx
  components/members/upload/sections/CareerFormSection.tsx
  pages/members/upload.tsx
Labels: ✨ Feature, size/S

#590 fix: 프로필 상세 > line-height 통일
  components/members/detail/InfoItem.tsx
  components/members/main/MemberDetail/InterestSection.tsx
Labels: size/S

#592 hotfix: 프로필 상세 > userFavor 모두 빈 값인 경우 의도치 않은 값이 보여지는 버그 fix
  components/members/main/MemberDetail/InterestSection.tsx
  components/members/main/MemberDetail/index.tsx
Labels: 🐛 Bug, size/M

#594 feat: 폼 아코디언 수정페이지에도 추가
  pages/members/edit.tsx
Labels: size/S

#601 hotfix: 프로필 업로드 > 수정 페이지와 submit 로직 통일
  pages/members/upload.tsx
Labels: 🐛 Bug, size/M

#587 feat: 멤버 프로필 활동정보 디자인 변경
  api/members/type.ts
  components/members/detail/ActivityBadge.stories.tsx
  components/members/detail/ActivityBadge.tsx
  components/members/detail/PartItem.stories.tsx
  components/members/detail/PartItem.tsx
  components/members/main/MemberDetail/index.tsx
  pages/members/edit.tsx
Labels: size/L
