Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-10, with the labels that each got.

#1015 feat: 온보딩 화면 개선
  src/components/intro/sections/CatchPhrase/Typer.tsx
  src/components/intro/sections/CatchPhrase/icons.tsx
  src/components/intro/sections/CatchPhrase/index.tsx
  src/components/intro/sections/ValueSection/ValueCard.tsx
  src/components/intro/sections/ValueSection/ValueDescription.tsx
  src/components/intro/sections/ValueSection/index.tsx
  src/components/intro/sections/ValueSection/valueContents/Value1.tsx
  src/components/intro/sections/ValueSection/valueContents/Value2.tsx
  src/components/intro/sections/ValueSection/valueContents/Value3.tsx
  src/components/intro/sections/ValueSection/valueContents/Value4.tsx
  src/components/intro/sections/ValueSection/valueContents/ValueBase.tsx
  src/components/intro/sections/ValueSection/valueContents/value2.png
  src/components/intro/sections/ValueSection/valueContents/value3.png
  src/components/intro/sections/ValueSection/valueContents/value4.png
Labels: size/L

#1017 fix: 프로필 수정 > UI 깨짐 수정
  src/components/members/upload/FormSection/SoptActivity.tsx
Labels: 🐛 Bug, size/XS

#1021 fix: 명예의 전당 줄바뀜 이슈 대응
  src/components/wordchain/WordchainWinners/WordchainWinner/index.stories.tsx
  src/components/wordchain/WordchainWinners/WordchainWinner/index.tsx
Labels: 🌟 QA, size/S

#1023 fix: 줄바꿈 대응
  src/components/wordchain/WordchainWinners/WordchainWinner/index.tsx
Labels: 🌟 QA, size/XS

#1019 chore: 디버그 패널 > 토큰 복사 기능 추가 및 스타일 개선
  src/components/debug/Panel.tsx
  src/components/debug/SideBar.tsx
  src/components/debug/panels/AccessTokenPanel.tsx
  src/components/debug/panels/NavigationPanel.tsx
  src/components/debug/styles.ts
Labels: size/L

#1026 chore: 환영 배너 내리기
  src/components/common/Banner/ActiveBannerSlot.tsx
Labels: size/XS

#1018 fix: 메이커스 소개 기수 탭 스크롤 수정
  src/components/makers/MakersMembers.tsx
Labels: size/XS

#1028 chore: 브컴팀 소개 설명 추가
  src/components/makers/data/generation3.ts
Labels: size/XS

#1036 feat: playground-commons 헤더에 @sopt-makers/colors 의존성 추가
  playground-common/package.json
  yarn.lock
Labels: size/XS

#1038 feat: 커뮤니티 레이아웃 구현
  .storybook/preview.tsx
  package.json
  src/components/community/layout/DesktopCommunityLayout.tsx
  src/components/community/layout/MobileCommunityLayout.tsx
  src/components/community/page.tsx
  src/components/community/queryParam.tsx
  src/components/layout/FullScreenLayout.tsx
  src/components/layout/HeaderFooterLayout.tsx
  src/components/layout/HeaderLayout.tsx
  src/components/layout/utils.ts
  src/pages/_app.tsx
  src/pages/community/index.tsx
  yarn.lock
Labels: size/L
