Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-02, with the labels that each got.

#401 chore: 빌드와 관련없는 파일 수정 시 action 실행되지 않도록 변경
  .github/workflows/build-test.yml
  .github/workflows/deploy-development.yml
Labels: size/S

#405 fix: apiHook 폴더 제거, api 폴더 하위로 이동
  api/hooks/index.ts
  api/hooks/members.ts
  api/hooks/projects.ts
  api/index.ts
  components/common/Header/index.tsx
  components/members/main/MemberDetail/CoffeeChatModal.tsx
  components/members/main/MemberDetail/index.tsx
  components/members/main/MemberList/index.tsx
  components/members/upload/BasicFormSection.tsx
  components/projects/main/ProjectDetail.tsx
  components/projects/upload/ProjectImageSection.tsx
  pages/members/upload.tsx
  pages/projects/upload/index.tsx
Labels: size/M

#409 chore: Actions 워크플로 개선
  .github/workflows/build-test.yml
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/chromatic.yml
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  .yarn/cache/concurrently-npm-7.6.0-2eabc58c36-f705c9a796.zip
  .yarn/cache/rxjs-npm-7.8.0-722f1c7172-61b4d4fd32.zip
  .yarn/cache/shell-quote-npm-1.7.4-b337567168-2874ea9c1a.zip
  .yarn/cache/spawn-command-npm-0.0.2-014d4d5d9f-e35c5d2817.zip
  .yarn/cache/tree-kill-npm-1.2.2-3da0e5a759-49117f5f41.zip
  components/members/main/MemberRoleMenu/MemberRoleDropdown.tsx
  next.config.js
  package.json
  yarn.lock
Labels: size/L

#421 feat: 다른 팀이 컴포넌트를 가져다 쓸 수 있게 제공
  .gitignore
  .yarn/cache/any-promise-npm-1.3.0-f34eeaa7e7-0ee8a9bdbe.zip
  .yarn/cache/bundle-require-npm-3.1.2-93fce3f174-71f8cb81bc.zip
  .yarn/cache/cac-npm-6.7.14-c46284e425-45a2496a94.zip
  .yarn/cache/esbuild-darwin-arm64-npm-0.15.18-37bdbfa731-8.zip
  .yarn/cache/esbuild-npm-0.15.18-61e07796c8-ec12682b2c.zip
  .yarn/cache/glob-npm-7.1.6-1ce3a5189a-351d549dd9.zip
  .yarn/cache/joycon-npm-3.1.1-3033e0e5f4-8003c9c3fc.zip
  .yarn/cache/lilconfig-npm-2.0.6-6231346eaf-40a3cd72f1.zip
  .yarn/cache/load-tsconfig-npm-0.2.3-4c2511c4df-e28d1b2725.zip
  .yarn/cache/lodash.sortby-npm-4.7.0-fda8ab950d-db170c9396.zip
  .yarn/cache/mz-npm-2.7.0-ec3cef4ec2-8427de0ece.zip
  .yarn/cache/postcss-load-config-npm-3.1.4-1cb8a7e276-1c589504c2.zip
  .yarn/cache/rollup-npm-3.12.0-e6bc7e0a76-66182947ea.zip
  .yarn/cache/source-map-npm-0.8.0-beta.0-688a309e94-e94169be64.zip
  .yarn/cache/sucrase-npm-3.29.0-9a73320e42-fc8f04c34f.zip
  .yarn/cache/thenify-all-npm-1.6.0-96309bbc8b-dba7cc8a23.zip
  .yarn/cache/thenify-npm-3.3.1-030bedb22c-84e1b804bf.zip
  .yarn/cache/tr46-npm-1.0.1-9547f343a4-96d4ed46bc.zip
  .yarn/cache/ts-interface-checker-npm-0.1.13-0c7b064494-20c29189c2.zip
  .yarn/cache/tsup-npm-6.5.0-2361533abf-625082f2a2.zip
  .yarn/cache/webidl-conversions-npm-4.0.2-1d159e6409-c93d8dfe90.zip
  .yarn/cache/whatwg-url-npm-7.1.0-d6cae01571-fecb07c872.zip
  components/common/Header/desktop/DesktopHeader.stories.tsx
  components/common/Header/desktop/DesktopHeader.tsx
  components/common/Header/desktop/ProfileButton.tsx
  components/common/Header/desktop/ProfileDropdown.stories.tsx
  components/common/Header/desktop/ProfileDropdown.tsx
  components/common/Header/index.tsx
  components/common/Header/mobile/MobileHeader.stories.tsx
  components/common/Header/mobile/MobileHeader.tsx
  components/common/Header/mobile/MobileSideBar.stories.tsx
  components/common/Header/mobile/MobileSideBar.tsx
  components/common/Header/types.ts
  package.json
  playground-common/.gitignore
  playground-common/.npmignore
  playground-common/README.md
  playground-common/export.ts
  playground-common/package.json
  playground-common/tsconfig.playground-common.json
  playground-common/tsup.config.ts
  tsconfig.json
  yarn.lock
Labels: size/XL

#422 chore: 프로젝트 상세 > 프로필을 등록하지 않은 멤버는 클릭 할 수 없도록 하기
  api/projects/type.ts
  components/projects/main/ProjectDetail.tsx
  components/projects/upload/hooks/useGetProjectQuery.ts
Labels: size/S

#425 Revert "Merge pull request #420 from sopt-makers/revert/member-search"
  .yarn/cache/esbuild-darwin-64-npm-0.15.18-c3c12de20e-8.zip
  .yarn/cache/qs-npm-6.11.0-caf1bc9dea-6e1f29dd53.zip
  api/hooks/members.ts
  api/index.ts
  components/members/main/MemberList/MemberSearch.tsx
  components/members/main/MemberList/index.tsx
  components/members/main/hooks/useMemberProfileQuery.ts
  components/projects/main/ProjectDetail.tsx
  hooks/usePageQueryParams.ts
  package.json
  pages/members/upload.tsx
  pages/projects/upload/index.tsx
  public/icons/icon-member-search.svg
  public/icons/icon-search-clear.svg
  yarn.lock
Labels: size/L

#429 chore: 배포 변수 가져오는부분 수정
  .github/workflows/deploy-production.yml
Labels: size/XS

#431 chore: 모집 마감 시간 업데이트
  components/common/Banner/RecruitingBanner/contants.ts
Labels: size/XS

#428 chore: 액션 path filter 수정
  .github/workflows/check.yml
Labels: size/S

#430 fix: 모바일 접속시 깜빡임 수정
  components/common/Banner/RecruitingBanner/index.tsx
  components/common/Header/index.tsx
  components/common/Responsive/Responsive.stories.tsx
  components/common/Responsive/Responsive.tsx
  components/common/Responsive/ResponsiveProvider.tsx
  components/common/Responsive/context.ts
  components/common/Responsive/index.tsx
  components/layout/HeaderFooterLayout.tsx
  hooks/useMediaQuery.ts
  package.json
  pages/_app.tsx
  yarn.lock
Labels: size/L

#434 chore: 2기 지원 정보 제거
  .github/workflows/check.yml
  README.md
Labels: size/XS

#440 feat: 다이나믹 라우트 적용
  constants/links.ts
  functions/members/[id].ts
  functions/members/detail.ts
  functions/members/index.ts
  functions/projects/[id].ts
  functions/projects/detail.ts
  functions/projects/index.ts
  next.config.js
  pages/members/[id].tsx
  pages/members/detail.tsx
  pages/members/index.tsx
  pages/projects/[id].tsx
  pages/projects/detail.tsx
  pages/projects/index.stories.tsx
  pages/projects/index.tsx
  pages/projects/upload/index.stories.tsx
  playground-common/package.json
Labels: size/L

#443 feat: 모집 배너 제거
  components/makers/AboutMakers.tsx
  components/makers/Notifier.tsx
  pages/makers/index.tsx
  pages/members/index.tsx
  pages/projects/index.tsx
Labels: size/M

#436 chore: 디펜던시 정리
  .yarn/cache/react-spinners-npm-0.13.4-b8116576f3-ae9430bc8a.zip
  components/auth/register/VerifyByEmail.tsx
  components/members/main/MemberDetail/CoffeeChatModal.tsx
  package.json
  pages/auth/callback/facebook/login.tsx
  pages/auth/callback/google/login.tsx
  pages/auth/callback/google/register.tsx
  yarn.lock
Labels: size/M

#442 refactor: lodash-es 사용하도록 변경
  .yarn/cache/@types-lodash-es-npm-4.17.6-fd5abbdc74-9bd239dd52.zip
  .yarn/cache/@types-lodash-npm-4.14.191-67a04a969b-ba0d5434e1.zip
  components/members/main/MemberDetail/index.tsx
  components/members/main/MemberList/index.tsx
  components/projects/main/ProjectList.tsx
  components/projects/upload/MemberForm/index.tsx
  components/projects/upload/hooks/useGetProjectQuery.ts
  hooks/usePageQueryParams.ts
  package.json
  pages/projects/index.tsx
  yarn.lock
Labels: size/M

#446 fix: 메이커스 멤버 정보 데이터 최적화
  pages/makers/index.tsx
Labels: size/S

#441 refactor: bump yup version
  .yarn/cache/@babel-runtime-npm-7.18.3-1883c70fa6-db8526226a.zip
  .yarn/cache/@types-lodash-npm-4.14.182-1073aac722-7dd137aa9d.zip
  .yarn/cache/nanoclone-npm-0.2.1-972ee958a0-96b2954e22.zip
  .yarn/cache/tiny-case-npm-1.0.3-8c9747c74e-3f7a30c39d.zip
  .yarn/cache/type-fest-npm-2.19.0-918b953248-a4ef07ece2.zip
  .yarn/cache/yup-npm-0.32.11-dbaff8ca9c-43a16786b4.zip
  .yarn/cache/yup-npm-1.0.0-e4c420ebd0-5944fd677c.zip
  components/members/upload/schema.ts
  components/projects/upload/schema.ts
  package.json
  yarn.lock
Labels: size/L

#447 refactor: 프로젝트 API 타입 분리
  api/projects/index.ts
  api/projects/type.ts
  components/projects/main/ProjectCard.stories.tsx
  components/projects/main/ProjectCard.tsx
  components/projects/main/ProjectDetail.tsx
  components/projects/upload/LinkForm/constants.ts
  components/projects/upload/LinkForm/index.tsx
  components/projects/upload/MemberForm/constants.ts
  components/projects/upload/ProjectCategory.tsx
  components/projects/upload/constants.ts
  components/projects/upload/types.ts
  pages/projects/upload/index.tsx
Labels: size/L

#445 refactor: 멤버 프로필 목록 레이아웃 시프트 수정
  .storybook/preview.js
  components/members/main/MemberList/MemberSearch.tsx
  components/members/main/MemberList/OnBoardingBanner.stories.tsx
  components/members/main/MemberList/OnBoardingBanner.tsx
  components/members/main/MemberList/index.tsx
Labels: size/L

#454 feat: merge queue 대응시키기
  .github/workflows/check.yml
  .github/workflows/chromatic.yml
  .github/workflows/deploy-development.yml
Labels: size/XS

#456 fix: 다이나믹 라우트 버그 수정
  functions/members/[id].ts
  functions/projects/[id].ts
  tsconfig.json
Labels: size/M

#457 fix: actions/check.yml의 path filter 삭제
  .github/workflows/check.yml
  .github/workflows/deploy-development.yml
  package.json
  tsconfig.json
  utils/test.test.ts
Labels: size/M

#465 fix: 무한 스크롤 버그 수정
  components/members/main/MemberList/index.tsx
Labels: size/XS

#464 feat: 32기 지원 추가
  constants/generation.ts
Labels: size/XS

#462 refactor: Amplitude 지연 로딩
  components/eventLogger/providers/AmplitudeProvider.tsx
Labels: size/S

#467 refactor: framer-motion 번들 사이즈 최적화
  .storybook/preview.js
  components/common/Loading/index.tsx
  pages/_app.tsx
Labels: size/M

#461 refactor: 프로젝트 업로드 폼 구조 다시 잡기
  .yarn/cache/zod-npm-3.20.6-d9ed055758-804b1934b8.zip
  components/common/EditableSelect.tsx
  components/common/Input/ErrorMessage.stories.tsx
  components/common/Input/ErrorMessage.tsx
  components/common/Input/index.stories.tsx
  components/common/Input/index.tsx
  components/projects/form/ProjectForm.stories.tsx
  components/projects/form/ProjectForm.tsx
  components/projects/form/fields/PeriodField.stories.tsx
  components/projects/form/fields/PeriodField.tsx
  components/projects/form/presenter/FormEntry.stories.tsx
  components/projects/form/presenter/FormEntry.tsx
  components/projects/form/schema.test.ts
  components/projects/form/schema.ts
  package.json
  yarn.lock
Labels: 🛠 Refactor, size/XL

#468 fix: Input 스타일 이탈 수정
  components/members/main/MemberList/MemberSearch.tsx
  components/projects/upload/LinkForm/index.tsx
  components/projects/upload/MemberForm/index.tsx
Labels: 🐛 Bug, ⚡️ Urgent, size/M

#470 refactor: 업로드 진행률 구조 잡기
  .yarn/cache/@radix-ui-react-progress-npm-1.0.1-a35e8ff97a-98b16c1886.zip
  components/common/form/FormProgress.stories.tsx
  components/common/form/FormProgress.tsx
  components/projects/form/ProjectForm.tsx
  components/projects/form/UploadProjectProgress.tsx
  package.json
  yarn.lock
Labels: size/L

#469 refactor: 로그인 콜백 코드 리팩터링
  components/auth/callback/LoginCallbackView.stories.tsx
  components/auth/callback/LoginCallbackView.tsx
  components/auth/callback/OAuthLoginCallback.tsx
  components/auth/identityProvider/facebook/useFacebookAuth.ts
  components/auth/register/Register.tsx
  components/auth/states/registerTokenAtom.ts
  pages/auth/callback/facebook/login.tsx
  pages/auth/callback/facebook/register.tsx
  pages/auth/callback/google/login.tsx
  pages/auth/callback/google/register.tsx
  pages/auth/login.tsx
  pages/auth/register.tsx
Labels: 🛠 Refactor, size/XL

#471 refactor: GenerationForm 리팩토링
  components/projects/form/ProjectForm.tsx
  components/projects/form/fields/GenerationField.stories.tsx
  components/projects/form/fields/GenerationField.tsx
  components/projects/form/schema.ts
Labels: size/L
