Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-09, with the labels that each got.

#940 chore: 이준호 없애기
  src/components/mentoring/data/production.ts
Labels: ✨ Feature, size/XS

#943 chore: 페이스북 로그인 불가 알럿 임시 추가
  src/pages/auth/login.tsx
Labels: size/S

#945 chore: 파비콘 변경
  public/favicon.ico
Labels: size/XS

#938 feat: 3기 정보 추가
  src/components/makers/data/generation3.ts
  src/components/makers/data/index.ts
Labels: size/L

#949 fix: 소셜로그인 재설정 오류 수정
  src/api/endpoint/auth/appleChange.ts
  src/api/endpoint/auth/googleChange.ts
  src/pages/auth/login.tsx
Labels: size/XS

#950 fix: 소셜로그인 재설정 엔드포인트 수정
  src/api/endpoint/auth/changeSMSCode.ts
  src/api/endpoint/auth/changeSMSToken.ts
  src/components/auth/reset/useResetLogin.ts
  src/pages/auth/reset.tsx
Labels: size/L

#951 chore: 프로필 업로드 > 공홈 공개 여부 관련 텍스트 제거
  src/components/members/upload/FormSection/PublicQuestion.tsx
Labels: size/S

#961 feat: 프로필 > 휴대폰 번호 필수 항목으로 수정
  components/members/upload/FormSection/Basic/index.tsx
  components/members/upload/schema.ts
Labels: size/S

#957 Revert "feat: 온보딩 배너 삭제"
  components/members/upload/FormSection/Basic/index.tsx
  components/members/upload/schema.ts
  pages/members/index.tsx
Labels: size/S

#921 feat: 회원가입 플로우에 프로필 등록 페이지 추가
  src/components/members/upload/FormSection/Basic/index.tsx
  src/components/members/upload/schema.ts
  src/pages/auth/callback/apple/register.tsx
  src/pages/auth/callback/google/register.tsx
  src/pages/members/edit.tsx
  src/pages/members/upload.tsx
Labels: ✨ Feature, size/M

#954 fix: 프로필 수정 페이지 > 수정하기 버튼 활성화 방식 변경
  src/pages/members/edit.tsx
  src/pages/members/upload.tsx
Labels: 🐛 Bug, size/XS

#962 fix: 프로필 업로드 스키마 > 공홈 공개 여부 nullable로 수정
  src/components/members/upload/schema.ts
Labels: 🐛 Bug, size/XS

#963 fix: 프로필 업로드 > 휴대폰 번호 정규식 수정
  src/components/members/upload/schema.ts
Labels: 🐛 Bug, size/XS

#946 feat: Endpoint 캐시 키 기능 추가
  src/api/typedAxios.ts
Labels: size/S

#975 feat: 메이커스 팀원 정보 변경
  src/components/makers/data/generation3.ts
Labels: size/XS

#980 feat: og tag 추가
  public/icons/img/og_playground.jpeg
  public/icons/img/og_profile.jpg
  public/icons/img/og_project.jpg
  src/pages/_document.tsx
  src/pages/members/[id].tsx
  src/pages/projects/[id].tsx
Labels: size/S

#981 chore: og tag 기본 이미지로 계속 오버라이드 되는 문제 수정
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: size/XS

#977 refactor: 끝말잇기 명예의 전당 코드리뷰 반영
  src/api/endpoint/wordchain/getWordchainWinners.ts
  src/components/wordchain/WordchainChatting/Wordchain/index.tsx
  src/components/wordchain/WordchainWinners/WordchainWinner/index.stories.tsx
  src/components/wordchain/WordchainWinners/WordchainWinner/index.tsx
  src/components/wordchain/WordchainWinners/hooks/useWordchainWinnersQuery.ts
  src/components/wordchain/WordchainWinners/index.stories.tsx
  src/components/wordchain/WordchainWinners/index.tsx
  src/components/wordchain/WordchainWinners/types.ts
  src/pages/wordchain/index.tsx
Labels: 🛠 Refactor, size/L

#987 fix: 플그 소셜로그인 -> 회원가입 플로우 오류 수정
  src/components/members/upload/schema.ts
  src/pages/members/edit.tsx
Labels: size/XS

#989 fix: meta tag에 key를 부여해 페이지에서 override 되도록 수정
  src/pages/_app.tsx
  src/pages/members/[id].tsx
  src/pages/projects/[id].tsx
Labels: size/S

#984 feat: 모바일에서 끝말잇기 영역 줄이기
  public/icons/icon-chevron-right.svg
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
  src/styles/colors.ts
Labels: size/L

#985 feat: 모바일 멘토링 뷰 최소화
  src/components/mentoring/MentoringCard/index.tsx
  src/components/mentoring/MentoringList/MentoringCardContainer.tsx
  src/components/mentoring/MentoringList/index.tsx
  src/pages/members/index.tsx
Labels: ✨ Feature, size/L

#990 feat: 환영 배너 구현
  public/icons/img/Desktop.gif
  public/icons/img/Mobile.gif
  public/icons/welcome-banner-balloon.svg
  public/icons/welcome-banner-rocket.svg
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/components/common/Banner/WelcomeBanner/index.tsx
Labels: ✨ Feature, size/L

#994 chore: 뷰 간격 조정
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/members/main/MemberList/index.tsx
  src/components/mentoring/MentoringList/index.tsx
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
  src/pages/members/index.tsx
Labels: 🌟 QA, size/S

#991 feat: 31-33기인 경우에만 수정/삭제/추가 불가능하도록
  src/components/common/Input/index.tsx
  src/components/members/upload/FormSection/SoptActivity.tsx
  src/components/members/upload/forms/FormHeader.tsx
Labels: size/L

#996 feat: 인트로에서 채널톡 숨기기
  src/pages/intro/index.tsx
Labels: size/XS

#997 fix: 끝말잇기 크래시 수정
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
Labels: size/S

#998 feat: 채널톡 제거
  src/pages/_app.tsx
  src/pages/intro/index.tsx
Labels: size/S

#999 feat: 배너 메세지 변경
  public/icons/img/illust_balloon.svg
  public/icons/img/illust_rocket.svg
  public/icons/welcome-banner-balloon.svg
  public/icons/welcome-banner-rocket.svg
  src/components/common/Banner/WelcomeBanner/index.tsx
Labels: size/L

#995 fix: radix-ui 버전 고정
  playground-common/package.json
  yarn.lock
Labels: size/L

#1000 fix: 끝말잇기 모바일 크기 수정
  src/components/wordchain/WordchainWinners/WordchainWinner/index.tsx
  src/components/wordchain/WordchainWinners/index.tsx
Labels: size/S

#1001 feat: 33기 이미지 추가
  public/icons/logo/time=33.svg
Labels: size/M

#1002 feat: NextSeo 로 적용, csr 페이지 로직 수정
  package.json
  src/pages/_app.tsx
  src/pages/members/[id].tsx
  src/pages/projects/[id].tsx
  yarn.lock
Labels: size/L

#1003 feat: 끝말잇기 배너 줄바꿈 수정
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
Labels: size/XS

#1004 feat: 명예의 전당 우승자 클릭 시 프로필로 넘어가도록 & 글자색 수정
  src/components/wordchain/WordchainWinners/WordchainWinner/index.tsx
  src/components/wordchain/WordchainWinners/index.stories.tsx
  src/components/wordchain/WordchainWinners/index.tsx
Labels: size/S

#1005 chore: 조사 추가
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
Labels: size/XS

#1006 fix: 프로필 수정/업로드 > 활동 정보 모바일 반응형 버그 fix
  src/components/members/upload/FormSection/SoptActivity.tsx
Labels: 🐛 Bug, size/S

#965 feat: SwitchCase 유틸 컴포넌트 추가
  jest.config.ts
  jest.setup.ts
  package.json
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
  src/utils/components/switch-case/SwitchCase.test.tsx
  src/utils/components/switch-case/SwitchCase.tsx
  tsconfig.json
  yarn.lock
Labels: size/XXL

#1009 fix: 무한스크롤 안되는 이슈 해결
  src/components/wordchain/WordchainWinners/index.tsx
Labels: 🐛 Bug, size/XS

#1010 chore: 끝말잇기 배너에 불필요한 margin 제거
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
Labels: size/XS

#1012 chore: 환영배너 이미지 수정
  public/icons/img/illust_balloon.png
  public/icons/img/illust_balloon.svg
  src/components/common/Banner/WelcomeBanner/index.tsx
Labels: 🌟 QA, size/L

#1014 fix: 모바일 뷰 멘토링 카드 radius 수정
  src/components/mentoring/MentoringCard/index.tsx
Labels: 🌟 QA, size/XS
