Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-01, with the labels that each got.

#322 refactor: window.location.search => router.asPath로 쿼리키 변경
  components/members/main/MemberList/index.tsx
Labels: size/XS

#311 feat: 초기 페이지 로드 성능 개선
  components/common/Header/index.tsx
  pages/_document.tsx
  public/icons/icon-logo-mobile.svg
  public/icons/icon-logo.svg
  styles/font.ts
Labels: size/M

#318 feat: 프로필 경력 수정/상세
  api/members/index.ts
  api/members/type.ts
  apiHooks/members.ts
  components/members/detail/CareerItem.tsx
  components/members/main/MemberDetail/index.tsx
  components/members/upload/CareerFormSection.tsx
  components/projects/upload/hooks/useGetMembersByNameQuery.ts
  pages/members/upload.tsx
  styles/typography.ts
Labels: size/L

#324 feat: 로딩 인디케이터 추가
  .yarn/cache/@motionone-animation-npm-10.15.1-f581cc96f3-75b7a1e6c4.zip
  .yarn/cache/@motionone-dom-npm-10.15.3-a0343c9f8b-e43746b837.zip
  .yarn/cache/@motionone-easing-npm-10.15.1-793a4addaa-cf7cfcf991.zip
  .yarn/cache/@motionone-generators-npm-10.15.1-9b31cd017c-0eb6797a64.zip
  .yarn/cache/@motionone-types-npm-10.15.1-0bac46e291-98091f7dca.zip
  .yarn/cache/@motionone-utils-npm-10.15.1-13443b5c16-6ef13cd663.zip
  .yarn/cache/@react-spring-animated-npm-9.4.5-753d5eb113-e85c0bd65b.zip
  .yarn/cache/@react-spring-core-npm-9.4.5-6b597c1158-e5aee7f68f.zip
  .yarn/cache/@react-spring-konva-npm-9.4.5-65e70326bc-9f8658dafe.zip
  .yarn/cache/@react-spring-native-npm-9.4.5-92b2f3b23b-7e3e5d17e4.zip
  .yarn/cache/@react-spring-rafz-npm-9.4.5-3efa1f80a5-0ac722881b.zip
  .yarn/cache/@react-spring-shared-npm-9.4.5-38c372ec24-2f20e410c0.zip
  .yarn/cache/@react-spring-three-npm-9.4.5-faf3618132-704e560c0d.zip
  .yarn/cache/@react-spring-types-npm-9.4.5-4645b5019e-f8fecb5401.zip
  .yarn/cache/@react-spring-web-npm-9.4.5-de05b4094d-9d7eea4b8b.zip
  .yarn/cache/@react-spring-zdog-npm-9.4.5-47f2d87683-b4b58b565c.zip
  .yarn/cache/framer-motion-npm-8.1.3-b856386d41-96461fe106.zip
  .yarn/cache/hey-listen-npm-1.0.8-adb7dae9da-6bad60b367.zip
  .yarn/cache/react-spring-npm-9.4.5-4b355b506e-0bcf67cb0a.zip
  .yarn/install-state.gz
  components/common/Loading/index.stories.tsx
  components/common/Loading/index.tsx
  components/common/Modal/Portal.tsx
  components/common/Modal/index.tsx
  components/common/Portal.tsx
  package.json
  yarn.lock
Labels: size/L

#312 feat: 토스트 공통 컴포넌트
  .storybook/preview.js
  components/common/Checkbox/index.tsx
  components/common/Portal/index.tsx
  components/common/Toast/ToastEntry.stories.tsx
  components/common/Toast/ToastEntry.tsx
  components/common/Toast/ToastWithSignupLink.stories.tsx
  components/common/Toast/context.ts
  components/common/Toast/providers/StorybookToastProvider.tsx
  components/common/Toast/providers/ToastProvider.tsx
  components/common/Toast/types.tsx
  components/common/Toast/useAtomicTimeout.ts
  components/common/Toast/useToast.ts
  components/projects/upload/SignUpLink/index.tsx
  components/projects/upload/ToastProvider/index.tsx
  components/projects/upload/ToastProvider/types.tsx
  pages/_app.tsx
  pages/projects/upload/index.tsx
  public/icons/icon-check.svg
Labels: size/L

#330 fix: 경력 없을 경우 빈 필드 안보이게
  components/members/main/MemberDetail/index.tsx
Labels: 🐛 Bug, size/S

#332 feat: 프로젝트 업로드 / 멤버 검색 개선
  .yarn/install-state.gz
  components/projects/upload/MemberForm/MemberSearch.tsx
  public/icons/icon-member-search-clear.svg
  public/icons/icon-member-search-default.svg
Labels: size/M

#331 fix: 메이커스 소개 오타 수정
  components/makers/data/contributors.ts
  components/makers/data/index.ts
Labels: size/XS

#319 feat: Amplitude 설정
  .env.development
  .storybook/preview.js
  .yarn/cache/@amplitude-analytics-browser-npm-1.6.7-a897de3040-c271117306.zip
  .yarn/cache/@amplitude-analytics-client-common-npm-0.5.1-a3034b95fa-83afba7847.zip
  .yarn/cache/@amplitude-analytics-connector-npm-1.4.6-d9e949e37c-0a2acfa54e.zip
  .yarn/cache/@amplitude-analytics-core-npm-0.11.1-215bd7949d-a64f9546be.zip
  .yarn/cache/@amplitude-analytics-types-npm-0.14.0-7b5c807dc5-23972f7869.zip
  .yarn/cache/@amplitude-ua-parser-js-npm-0.7.31-540ed0892d-c72e7c8656.zip
  .yarn/install-state.gz
  components/eventLogger/context.ts
  components/eventLogger/controllers/amplitude.ts
  components/eventLogger/controllers/consoleLog.ts
  components/eventLogger/controllers/storybookAction.ts
  components/eventLogger/events.ts
  components/eventLogger/hooks/useEventLogger.ts
  components/eventLogger/providers/AmplitudeProvider.tsx
  components/eventLogger/providers/StorybookEventLoggerProvider.tsx
  components/eventLogger/types.ts
  components/members/main/MemberList/index.tsx
  components/projects/main/ProjectCard.tsx
  constants/env.ts
  package.json
  pages/_app.tsx
  yarn.lock
Labels: size/L

#328 feat: 프로필 업로드 폼 > 모바일 키보드 UX 최적화
  components/members/upload/AdditionalInfoFormSection.tsx
  components/members/upload/BasicFormSection.tsx
  components/projects/upload/LinkForm/index.tsx
  components/projects/upload/ProjectPeriod.tsx
Labels: ✨ Feature, size/M

#335 fix: 이미지가 빈 값일 경우 기본 이미지 보여지도록 대응
  components/projects/upload/MemberForm/MemberSearch.tsx
Labels: size/XS

#339 fix: 프로젝트 업로드 > 멤버 검색 시 기본 이미지 노출
  .yarn/install-state.gz
  components/projects/upload/MemberForm/MemberSearch.tsx
Labels: size/S

#341 fix: type="number"인 input 화살표, 스피너 뜨지 않도록
  styles/global.ts
Labels: 🐛 Bug, size/S

#334 refactor: 프로필 업로드 폼 default value 상수화
  components/members/upload/AdditionalInfoFormSection.tsx
  components/members/upload/SoptActivityFormSection.tsx
  components/members/upload/constants.ts
Labels: 🛠 Refactor, size/S

#338 feat: role에 Team Leader추가, 라벨 적용
  api/projects/type.ts
  components/projects/main/ProjectDetail.tsx
  components/projects/upload/MemberForm/constants.ts
  components/projects/upload/MemberForm/index.tsx
Labels: size/M

#333 feat: 프로젝트 수정/삭제 api 연동
  .yarn/install-state.gz
  api/projects/index.ts
  apiHooks/projects.ts
  components/common/Button/style.ts
  components/common/Header/index.tsx
  components/common/ImageUploader/index.tsx
  components/common/Modal/Confirm.tsx
  components/projects/main/ProjectDetail.tsx
  components/projects/upload/MemberForm/MemberSearch.tsx
  components/projects/upload/MemberForm/constants.ts
  components/projects/upload/MemberForm/index.tsx
  components/projects/upload/ProjectImageSection.tsx
  components/projects/upload/utils.ts
  constants/links.ts
  pages/projects/upload/index.tsx
  public/icons/icon-trashcan.svg
Labels: ✨ Feature, size/L

#344 fix: 멤버 추가 오류 수정
  components/projects/upload/MemberForm/index.tsx
Labels: size/XS

#343 feat: 프로필 상세 > 프로필 등록하지 않았을 경우 대응
  apiHooks/members.ts
  components/members/detail/EmptyProfile.tsx
  components/members/main/MemberDetail/index.tsx
Labels: ✨ Feature, size/L

#346 feat: 정연 입맛 기준으로 프로젝트 롤 정렬
  .yarn/install-state.gz
  components/projects/main/ProjectDetail.tsx
  components/projects/upload/MemberForm/constants.ts
Labels: size/S

#351 fix: 프로젝트 상세 링크 모바일 미노출 이슈 수정
  components/projects/main/ProjectDetail.tsx
Labels: 🐛 Bug, size/XS

#350 feat: 프로젝트 멤버 UI 개선
  components/members/common/MemberBlock.stories.tsx
  components/members/common/MemberBlock.tsx
  components/members/common/WithMemberMetadata.tsx
  components/projects/main/ProjectDetail.tsx
Labels: size/L

#354 헤더에 모임 탭 추가
  .yarn/install-state.gz
  components/common/Header/index.tsx
  constants/links.ts
Labels: size/S

#355 feat: 메이커스 소개 멤버 UI 수정
  api/members/type.ts
  components/makers/MakersMembers.tsx
  components/makers/data/contributors.ts
  components/makers/data/generation1.ts
  components/members/common/WithMemberMetadata.tsx
Labels: size/M

#359 chore: 만든사람들 누락된 멤버 추가
  components/makers/data/generation1.ts
Labels: size/XS

#361 fix: 불필요 API 요청 제거
  components/makers/MakersMembers.tsx
Labels: size/M

#363 chore: 유령 파일 제거
  .yarn/install-state.gz
Labels: size/XS

#367 fix: 프로젝트 업로드/수정 페이지에서 업로드 하는 조건 더욱 엄격하게 수정
  pages/projects/upload/index.tsx
Labels: 🐛 Bug, size/XS

#371 fix: optional 항목에 null이 들어올 수 있도록 스키마 수정
  components/members/upload/schema.ts
Labels: 🐛 Bug, size/L

#380 feat: 메이커스 멤버 소개 최적화
  components/makers/MakersMembers.tsx
  pages/makers/index.tsx
Labels: size/M, 🚀 Performance

#384 fix: 프로필 등록 및 수정 버그 fix (경력, 생일)
  pages/members/upload.tsx
Labels: 🐛 Bug, size/S

#387 fix: 모바일 프로필 사진 오류
  components/common/Header/mobile/MobileSideBar.tsx
Labels: 🐛 Bug, size/XS

#381 chore: README 작성
  LICENSE.md
  README.md
Labels: size/M

#389 fix: 인증 화면 여백 수정
  components/auth/register/Stepper.tsx
  components/auth/register/VerifyByEmail.tsx
  components/layout/FullScreenLayout.stories.tsx
  components/layout/FullScreenLayout.tsx
  components/layout/index.tsx
  pages/auth/login.tsx
  pages/auth/register-finished.tsx
  pages/auth/register.tsx
  pages/auth/verify.tsx
Labels: 🐛 Bug, size/M

#393 feat: 모집 홍보 배너 띄우기
  components/common/Banner/RecruitingBanner/CountdownTimer.tsx
  components/common/Banner/RecruitingBanner/MobileRecruitingBanner.tsx
  components/common/Banner/RecruitingBanner/contants.ts
  components/common/Banner/RecruitingBanner/index.tsx
  hooks/useCountdown.tsx
  hooks/useInterval.ts
  pages/members/index.tsx
  pages/projects/index.tsx
  utils/index.ts
Labels: ✨ Feature, size/L

#392 fix: 헤더 이슈들 수정
  components/common/Header/LegacyHeader.stories.tsx
  components/common/Header/LegacyHeader.tsx
  components/common/Header/SwitchableHeader.tsx
  components/common/Header/desktop/ProfileDropdown.tsx
  pages/makers/index.tsx
  utils/layout.tsx
Labels: 🐛 Bug, size/XL

#394 docs: 리드미 수정
  README.md
Labels: 📖 Docs, size/L

#406 refactor: typography 개선
  styles/typography.ts
Labels: size/L

#375 docs: 이슈 템플릿 잘 안 쓰는 항목 주석 처리
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 📖 Docs, size/XS

#408 feat: 2기 모집 예정 박스를 모집 홍보 배너로 변경
  components/common/Banner/RecruitingBanner/index.tsx
  components/makers/AboutMakers.tsx
  pages/makers/index.tsx
Labels: ✨ Feature, size/S

#391 refactor: headless ui 를 radix ui 로 마이그레이션
  .yarn/cache/@radix-ui-react-collapsible-npm-1.0.1-c6b12fe32c-24c4611c06.zip
  .yarn/cache/@radix-ui-react-tabs-npm-1.0.2-a071d049b9-135f166383.zip
  components/debug/Panel.tsx
  components/makers/MakersMembers.tsx
  package.json
  yarn.lock
Labels: size/L

#410 refactor: RecruitingBanner 컴포넌트 가독성 개선
  components/common/Banner/RecruitingBanner/index.tsx
Labels: 🛠 Refactor, size/M

#412 fix: 프로필 수정 > 휴대폰 번호 수정 안되는 버그 fix
  components/members/upload/BasicFormSection.tsx
Labels: 🐛 Bug, ❗️ Important, size/XS

#413 fix: 프로필 상세 > 빈 항목일 경우 해당 영역 없애기
  components/members/main/MemberDetail/index.tsx
Labels: 🐛 Bug, size/M

#415 fix: 프로필 업로드 > 빠뜨렸던 생일 포맷 코드 추가
  pages/members/upload.tsx
Labels: 🐛 Bug, ❗️ Important, size/XS

#300 feat: 멤버 검색 api 구현
  .yarn/cache/qs-npm-6.11.0-caf1bc9dea-6e1f29dd53.zip
  apiHooks/members.ts
  components/members/main/MemberList/MemberSearch.tsx
  components/members/main/MemberList/index.tsx
  components/members/main/hooks/useMemberProfileQuery.ts
  hooks/usePageQueryParams.ts
  package.json
  public/icons/icon-member-search.svg
  yarn.lock
Labels: size/L

#417 feat: 프로필 상세 > 생일/전공/지역 빈 값일 경우 라벨 숨기기
  components/members/main/MemberDetail/index.tsx
Labels: ✨ Feature, size/XS

#419 fix: 프로필 상세 > 프로젝트 카드 이미지 비율 깨지지 않도록
  components/members/detail/MemberProjectCard.tsx
Labels: size/XS

#420 Revert "Merge pull request #300 from sopt-makers/feature/#263"
  .yarn/cache/qs-npm-6.11.0-caf1bc9dea-6e1f29dd53.zip
  apiHooks/members.ts
  components/members/main/MemberList/MemberSearch.tsx
  components/members/main/MemberList/index.tsx
  components/members/main/hooks/useMemberProfileQuery.ts
  hooks/usePageQueryParams.ts
  package.json
  public/icons/icon-member-search.svg
  yarn.lock
Labels: size/L
