Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2023-06, with the labels that each got.

#743 feat: 멘토링 디자인 변경 및 데이터 추가/변경
  components/mentoring/MentoringCard/index.tsx
  components/mentoring/MentoringDetail/index.tsx
  components/mentoring/MentoringList/index.tsx
  components/mentoring/data/development.ts
  components/mentoring/data/production.ts
Labels: size/L

#745 fix: 쪽지 모달 모바일 반응형 임시 대응
  components/common/Modal/index.tsx
  components/members/detail/MessageSection/MessageModal.tsx
Labels: 🐛 Bug, size/S

#746 chore: 멘토링 데이터 수정
  components/mentoring/data/production.ts
Labels: size/XS

#751 chore: 멘토링 데이터 수정(은수 keyword 분리)
  components/mentoring/data/production.ts
Labels: size/XS

#747 feat: 멘토링 리스트 UI 개선
  components/common/Carousel/index.tsx
  components/common/Carousel/useCarousel.ts
  components/mentoring/MentoringList/index.tsx
  hooks/usePagination.ts
Labels: ✨ Feature, size/M

#749 fix: 캐러셀 > 스크린 리사이징으로 인해 존재하지 않는 페이지 넘버가 된 경우 대응
  components/common/Carousel/useCarousel.ts
Labels: 🐛 Bug, size/M

#752 feat: 멘토링 마감 기능 구현
  components/common/Carousel/index.stories.tsx
  components/mentoring/MentoringCard/index.stories.tsx
  components/mentoring/MentoringCard/index.tsx
  components/mentoring/MentoringDetail/index.tsx
  components/mentoring/MentoringList/index.tsx
  components/mentoring/data/development.ts
  components/mentoring/data/index.ts
  components/mentoring/data/production.ts
  components/mentoring/data/types.ts
Labels: ✨ Feature, size/L

#754 feat: 쪽지 모달 컨텐츠 글자 수 제한하기
  components/members/detail/MessageSection/MessageModal.tsx
Labels: size/XS

#755 fix: 쪽지 모달 > 쪽지 보내기 버튼 로딩 스피너 보이지 않는 버그 fix
  components/common/Loading/index.tsx
  components/members/detail/MessageSection/MessageModal.tsx
Labels: 🐛 Bug, size/S

#757 fix: 멘토링 리스트 > 캐러셀 페이지 이동 시 layout shift fix
  components/mentoring/MentoringCard/index.tsx
Labels: 🐛 Bug, size/XS

#759 hotfix: 쪽지 모달 컨텐츠 길이 제한 버그 fix
  components/members/detail/MessageSection/MessageModal.tsx
Labels: 🐛 Bug, size/XS

#760 feat: 멘토링 카드 title 개행 추가
  components/mentoring/MentoringCard/index.tsx
  components/mentoring/data/production.ts
Labels: size/S

#764 feat: 멘토링 UI 수정
  components/mentoring/MentoringCard/index.tsx
  components/mentoring/MentoringDetail/index.tsx
  components/mentoring/data/development.ts
Labels: size/S

#739 feat: 풀구 헤더 플젝 업로드 버튼 제거, 업로드 넛지영역 추가
  components/common/Header/desktop/DesktopHeader.tsx
  components/members/detail/MemberDetail.tsx
  components/projects/main/ProjectList.tsx
  playground-common/package.json
  public/icons/icon-pen.svg
  public/icons/icon-plus-white.svg
  public/icons/img/project-mask.png
Labels: size/L

#766 chore: 멘토링 데이터 수정
  components/mentoring/data/development.ts
Labels: size/M

#768 fix: 멘토링 리스트 스타일 수정
  components/mentoring/MentoringList/index.tsx
Labels: size/S

#770 fix: 내 프로필일 경우에만 업로드 넛지 영역 보이도록 수정
  api/endpoint/members/getMemberOfMe.ts
  api/endpoint_LEGACY/hooks/members.ts
  api/endpoint_LEGACY/members/index.ts
  components/common/Header/index.tsx
  components/eventLogger/providers/AmplitudeProvider.tsx
  components/members/detail/MemberDetail.tsx
  components/projects/main/ProjectDetail.tsx
  pages/members/index.tsx
  pages/projects/upload/index.tsx
Labels: size/L

#771 refactor: 파라미터 없는 이벤트 사용 개선
  components/common/Footer/index.tsx
  components/common/Header/index.tsx
  components/eventLogger/controllers/amplitude.ts
  components/eventLogger/controllers/consoleLog.ts
  components/eventLogger/controllers/storybookAction.ts
  components/eventLogger/events.ts
  components/eventLogger/types.ts
  components/members/detail/MemberDetail.tsx
  components/members/main/MemberList/OnBoardingBanner.tsx
  components/members/main/MemberList/index.tsx
  components/mentoring/MentoringList/index.tsx
  pages/auth/login.tsx
  pages/members/edit.tsx
Labels: size/L

#772 feat: 페이지뷰 트래킹 기능 추가
  .yarn/cache/@amplitude-analytics-browser-npm-1.10.4-166d34ecd4-e024529e2d.zip
  .yarn/cache/@amplitude-analytics-browser-npm-1.6.7-a897de3040-c271117306.zip
  .yarn/cache/@amplitude-analytics-client-common-npm-0.5.1-a3034b95fa-83afba7847.zip
  .yarn/cache/@amplitude-analytics-client-common-npm-0.7.0-787e58b603-710509aadd.zip
  .yarn/cache/@amplitude-analytics-core-npm-0.11.1-215bd7949d-a64f9546be.zip
  .yarn/cache/@amplitude-analytics-core-npm-0.13.3-c27af64979-c41179d42a.zip
  .yarn/cache/@amplitude-analytics-types-npm-0.14.0-7b5c807dc5-23972f7869.zip
  .yarn/cache/@amplitude-analytics-types-npm-0.20.0-2e7695d33b-e9c8c5e424.zip
  .yarn/cache/@amplitude-plugin-page-view-tracking-browser-npm-0.8.1-0e7786387d-a7b6f9fa36.zip
  .yarn/cache/@amplitude-plugin-web-attribution-browser-npm-0.7.0-58f406b56e-a6b5a8cf8b.zip
  components/eventLogger/controllers/amplitude.ts
  package.json
  yarn.lock
Labels: size/M

#777 feat: 쪽지 모달 > 카테고리 멘토링일 때의 placeholder 변경
  api/endpoint_LEGACY/hooks/members.ts
  api/endpoint_LEGACY/members/index.ts
  api/endpoint_LEGACY/members/type.ts
  components/members/detail/MessageSection/MessageModal.tsx
Labels: ✨ Feature, size/M

#780 feat: 프로필 수정/업로드 버튼에 disable 상태 추가
  components/members/upload/forms/Form.tsx
  pages/members/edit.tsx
  pages/members/upload.tsx
Labels: ✨ Feature, size/M

#778 feat: 멘토링 리스트 > 멘토 신청 버튼 추가
  components/eventLogger/events.ts
  components/mentoring/MentoringList/index.tsx
  constants/links.ts
Labels: ✨ Feature, size/M

#784 feat: 프로필 업로드/수정 페이지 > submit 버튼 디자인 변경 반영
  components/members/upload/forms/Form.tsx
Labels: ✨ Feature, size/M

#789 feat: AppJamBanner 추가
  components/common/Banner/ActiveBannerSlot.tsx
  components/common/Banner/AppJamBanner/AppJamBanner.stories.tsx
  components/common/Banner/AppJamBanner/AppJamBanner.tsx
  components/common/Banner/AppJamBanner/assets/banner-left.svg
  components/common/Banner/AppJamBanner/assets/banner-right.svg
  components/common/Banner/AppJamBanner/assets/mobile-banner-right.svg
Labels: size/L

#790 fix: AppJamBanner 오타 수정
  components/common/Banner/AppJamBanner/AppJamBanner.tsx
Labels: size/XS

#788 feat: 멘토링 리스트 layout shift 개선
  components/mentoring/MentoringList/index.tsx
Labels: size/L

#792 feat: 폰트 경량화(ttf -> woff2 교체)
  pages/_document.tsx
  public/fonts/SUIT-Bold.ttf
  public/fonts/SUIT-Bold.woff2
  public/fonts/SUIT-ExtraBold.ttf
  public/fonts/SUIT-ExtraBold.woff2
  public/fonts/SUIT-Medium.ttf
  public/fonts/SUIT-Medium.woff2
  public/fonts/SUIT-SemiBold.ttf
  public/fonts/SUIT-SemiBold.woff2
  styles/font.ts
Labels: size/S, 🚀 Performance

#786 feat: 채널톡 연동하기
  .env.development
  constants/env.ts
  pages/_app.tsx
  utils/channelService/channelService.ts
  utils/channelService/useChannelService.ts
Labels: ✨ Feature, size/L

#795 feat: 프로필 수정 페이지 > 수정 사항 없을 시 submit 버튼 눌러도 put 요청 보내지지 않도록
  pages/members/edit.tsx
Labels: size/S

#803 feat: 끝말잇기 페이지 레이아웃 구현
  components/wordchain/WordchainRules.stories.tsx
  components/wordchain/WordchainRules.tsx
  pages/wordchain/index.tsx
  public/icons/icon-wordchain-arrow.svg
  public/icons/icon-wordchain-message.svg
Labels: size/L

#805 feat: 끝말잇기 채팅 컴포넌트 마크업
  components/wordchain/WordchainChatting.tsx
  components/wordchain/WordchainChatting/StartWordChatMessage/index.stories.tsx
  components/wordchain/WordchainChatting/StartWordChatMessage/index.tsx
  components/wordchain/WordchainChatting/WordChatMessage/index.stories.tsx
  components/wordchain/WordchainChatting/WordChatMessage/index.tsx
  components/wordchain/WordchainChatting/Wordchain/index.stories.tsx
  components/wordchain/WordchainChatting/Wordchain/index.tsx
  components/wordchain/WordchainChatting/index.tsx
  components/wordchain/WordchainChatting/types.ts
  public/icons/icon-paper-airplane.svg
  public/icons/icon-trophy.svg
  public/logos/logo-makers-circle.svg
Labels: ✨ Feature, size/XL

#806 fix: 메이커스 로고 파일 수정
  components/wordchain/WordchainChatting/StartWordChatMessage/index.tsx
  public/logos/img/logo-makers-circle.png
  public/logos/logo-makers-circle.svg
Labels: size/S

#809 chore: 앱잼 기획경선 배너 제거
  components/common/Banner/ActiveBannerSlot.tsx
Labels: size/XS

#812 chore: 멘토링 데이터 변경
  components/mentoring/data/production.ts
Labels: size/XS

#813 chore: disable 버튼 cursor default로 바꾸기
  components/mentoring/MentoringDetail/index.tsx
Labels: size/XS

#814 feat: 끝말잇기 단어 추가 post api 연결
  api/endpoint/wordchain/getWordchain.ts
  api/endpoint/wordchain/postWord.ts
  components/wordchain/WordchainChatting/index.tsx
Labels: ✨ Feature, size/L

#819 feat: 끝말잇기 최초 로드 및 업데이트 시 스크롤 최하단으로 이동
  components/wordchain/WordchainChatting/WordChatMessage/index.tsx
  components/wordchain/WordchainChatting/index.tsx
Labels: ✨ Feature, size/M

#825 fix: words 없는 경우 대응 및 initial 정보에 api 변경 대응
  api/endpoint/wordchain/getWordchain.ts
  components/wordchain/WordchainChatting/Wordchain/index.tsx
Labels: 🐛 Bug, size/S

#826 feat: 준호 멘토링 추가
  components/mentoring/data/development.ts
  components/mentoring/data/production.ts
Labels: size/M

#828 fix: 멘토링 개행 수정
  components/mentoring/data/development.ts
  components/mentoring/data/production.ts
Labels: size/M

#830 fix: 멘토링 상세 페이지 > 스타일 수정
  components/mentoring/MentoringDetail/InfoItem.tsx
Labels: size/XS

#831 chore: 멘토링 데이터 변경
  components/mentoring/data/production.ts
Labels: size/XS

#836 feat: 멤버리스트 페이지 노운,자잘 이슈 수정
  components/members/main/MemberList/index.tsx
Labels: size/M

#834 feat: 끝말잇기 채팅 단어 생성 에러 처리 구현
  api/endpoint/wordchain/postWord.ts
  components/wordchain/WordchainChatting/Wordchain/index.tsx
  components/wordchain/WordchainChatting/index.tsx
Labels: ✨ Feature, size/M

#723 feat: 솝티클 업로드 추가
  api/endpoint/sopticles/uploadSopticle.ts
  components/common/Header/desktop/DesktopHeader.tsx
  components/common/Header/mobile/MobileSideBar.tsx
  components/sopticle/HelpCard.tsx
  components/sopticle/Success.stories.tsx
  components/sopticle/Success.tsx
  components/sopticle/UploadSopticle.stories.tsx
  components/sopticle/UploadSopticle.tsx
  constants/links.ts
  pages/sopticle/index.tsx
  pages/sopticle/success.tsx
  playground-common/export.ts
Labels: size/XL

#843 fix: 솝티클 링크 수정
  components/sopticle/Success.tsx
Labels: size/XS

#844 chore: storybook 7 관련 편의성 향상
  .vscode/typescripreact.code-snippets
  .yarn/cache/@esbuild-darwin-arm64-npm-0.18.9-624d65eeec-8.zip
  .yarn/cache/babel-loader-npm-8.3.0-a5239d7ed2-d48bcf9e03.zip
  .yarn/cache/esbuild-npm-0.18.9-8947c7ff61-2580d38d2e.zip
  .yarn/cache/eslint-plugin-simple-import-sort-npm-10.0.0-695149a137-23221ff63f.zip
  .yarn/cache/eslint-plugin-simple-import-sort-npm-8.0.0-da2a29579b-d2a92a7d14.zip
  .yarn/cache/postcss-load-config-npm-3.1.4-1cb8a7e276-1c589504c2.zip
  .yarn/cache/postcss-load-config-npm-4.0.1-351eb776f5-b61f890499.zip
  .yarn/cache/prettier-npm-2.6.2-05918420da-48d08dde8e.zip
  .yarn/cache/schema-utils-npm-2.7.1-f84d18c473-32c62fc9e2.zip
  .yarn/cache/tsup-npm-6.7.0-5093540b93-91ff179f0b.zip
  .yarn/cache/tsup-npm-7.1.0-3fe66cd74a-5639c0f499.zip
  .yarn/cache/yaml-npm-2.3.1-743f5688d1-2c7bc9a7cd.zip
  package.json
  yarn.lock
Labels: size/L

#845 feat: 끝말잇기 진입점 새 게임 시작 case 대응
  api/endpoint/wordchain/getWordchain.ts
  components/wordchain/WordchainChatting/Wordchain/index.tsx
  components/wordchain/WordchainEntry/WordChainEntry.tsx
  components/wordchain/WordchainEntry/WordchainMessage.stories.tsx
  components/wordchain/WordchainEntry/WordchainMessage.tsx
Labels: size/L

#837 feat: 끝말잇기 채팅 무한 스크롤 구현
  api/endpoint/wordchain/getWordchain.ts
  components/wordchain/WordchainChatting/index.tsx
Labels: ✨ Feature, size/M

#847 fix: 끝말잇기 채팅 > 우승한 게임 순서, 첫 단어 서버 response 반영
  api/endpoint/wordchain/getWordchain.ts
  components/wordchain/WordchainChatting/Wordchain/index.tsx
Labels: 🐛 Bug, size/XS

#850 chore: 끝말잇기 채팅 GET api cursor 계산 방식 변경
  api/endpoint/wordchain/getWordchain.ts
Labels: size/XS
