Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-11, with the labels that each got.

#1620 feat: 커피챗 상세 페이지 구현
  package.json
  src/api/endpoint/coffeechat/getCoffeechatDetail.ts
  src/api/endpoint/coffeechat/postCoffeechatIsBlind.ts
  src/components/coffeechat/detail/CoffeechatContents/index.tsx
  src/components/coffeechat/detail/OpenerProfile/index.tsx
  src/components/coffeechat/detail/RegisterCoffeechatButton/index.tsx
  src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx
  src/components/coffeechat/detail/index.tsx
  src/components/members/detail/CareerSection/index.tsx
  src/components/members/detail/ProjectSection/index.tsx
  src/constants/links.ts
  src/pages/coffeechat/[id].tsx
  yarn.lock
Labels: size/XL

#1624 feat: 커피챗 상세페이지 구현 QA (웹미나)
  package.json
  public/icons/icon_coffeechat.svg
  src/api/endpoint/coffeechat/getCoffeechatDetail.ts
  src/api/endpoint/coffeechat/postCoffeechatIsBlind.ts
  src/api/endpoint_LEGACY/members/type.ts
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeChatModal/CoffeeChatCustomPortalModal.tsx
  src/components/coffeechat/CoffeeChatModal/CoffeeChatModal.tsx
  src/components/coffeechat/detail/CoffeechatContents/index.tsx
  src/components/coffeechat/detail/OpenerProfile/index.tsx
  src/components/coffeechat/detail/RegisterCoffeechatButton/index.tsx
  src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx
  src/components/coffeechat/detail/index.tsx
  src/components/common/Modal/useCustomConfirm.tsx
  src/components/members/detail/CareerSection/index.tsx
  src/components/members/detail/ProjectSection/index.tsx
  src/constants/links.ts
  src/pages/coffeechat/[id].tsx
  src/styles/mediaQuery.ts
  yarn.lock
Labels: ✨ Feature, size/XXL

#1627 feat: 클라우드플레어 배포를 위한 경로 설정
  functions/coffeechat/[id].ts
  functions/coffeechat/edit/[id].ts
  functions/coffeechat/index.ts
Labels: size/S

#1631 fix: 커피챗 상세 페이지 qa 반영
  src/components/coffeechat/detail/CoffeechatContents/index.tsx
  src/components/coffeechat/detail/index.tsx
  src/components/members/detail/ActivitySection/MemberDetailSection.ts
  src/components/members/detail/DetailinfoSection/index.tsx
  src/components/members/detail/GroupSection/index.tsx
  src/components/members/detail/ProjectSection/index.tsx
Labels: size/L

#1623 fix: 멤버 검색 이후 프로필로 들어가지지 않는 오류 수정
  src/components/members/main/MemberList/index.tsx
Labels: size/S

#1636 revert: 프로젝트, 모임 공통 컴포넌트 롤백
  src/components/coffeechat/detail/index.tsx
  src/components/members/detail/GroupSection/index.tsx
  src/components/members/detail/ProjectSection/index.tsx
Labels: size/L

#1616 fix: 프로젝트, 모임 섹션 뷰 텍스트 라이팅 변경
  src/components/members/detail/GroupSection/index.tsx
  src/components/members/detail/ProjectSection/index.tsx
Labels: size/L

#1614 feat: 멤버 디테일 커피챗 관련 수정내역 반영
  src/api/endpoint_LEGACY/members/type.ts
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/detail/ActivitySection/MemberDetailSection.ts
  src/components/members/detail/CareerSection/index.tsx
  src/components/members/detail/MessageSection/index.tsx
  src/components/members/upload/FormSection/Career.tsx
  src/components/members/upload/FormSection/CoffeeChat.tsx
  src/components/members/upload/constants.ts
  src/components/members/upload/schema.ts
  src/components/members/upload/types.ts
  src/pages/members/edit.tsx
  src/pages/members/upload.tsx
Labels: size/XL

#1637 feat: 커피챗 내 뱃지 overflow ellipsis 처리, mds Select 제거하고 모바일 BottomSheet 연결
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeChatCategory/CoffeeChatFilterSheet.tsx
  src/components/coffeechat/CoffeeChatCategory/index.tsx
  src/components/coffeechat/CoffeeRecentChatList/index.tsx
  src/components/coffeechat/CoffeeRecentChatList/scrollCarousel.tsx
  src/components/members/main/hooks/useVisibleBadges.ts
Labels: ✨ Feature, size/XXL

#1639 feat: 커피챗 상세 2차 QA 반영
  src/components/coffeechat/CoffeeChatModal/CoffeeChatModal.tsx
  src/components/coffeechat/detail/CoffeechatContents/index.tsx
  src/components/coffeechat/detail/OpenerProfile/index.tsx
Labels: size/L

#1628 feat: 멤버탭 내 커피챗 진입점 연결, 쪽지 모달에서 커피챗 삭제
  src/components/members/detail/MessageSection/MessageModal.tsx
  src/components/members/main/MemberCard/index.tsx
  src/components/members/main/MemberList/index.tsx
Labels: size/M

#1643 fix: 멤버 리스트 내 커피챗 뱃지 클릭시 멤버 카드 클릭과 함께 작동되는 문제 해결
  src/components/members/main/MemberCard/index.tsx
Labels: 🐛 Bug, size/XS

#1621 feat: 커피챗 오픈/수정 로직 구현
  src/api/endpoint/coffeechat/editCoffeechat.ts
  src/api/endpoint/coffeechat/uploadCoffeechat.ts
  src/components/coffeechat/mediaQuery.ts
  src/components/coffeechat/page/CoffeechatUploadPage.tsx
  src/components/coffeechat/page/layout/DesktopCoffeechatUploadLayout.tsx
  src/components/coffeechat/page/layout/MobileCoffeechatUploadLayout.tsx
  src/components/coffeechat/upload/CoffeechatForm/ChipField/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/CoffeechatInfoForm/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/MyInfoForm/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/SubmitDialog/index.stories.tsx
  src/components/coffeechat/upload/CoffeechatForm/SubmitDialog/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/UploadButton/index.stories.tsx
  src/components/coffeechat/upload/CoffeechatForm/UploadButton/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/constants.ts
  src/components/coffeechat/upload/CoffeechatForm/index.stories.tsx
  src/components/coffeechat/upload/CoffeechatForm/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/schema.ts
  src/components/coffeechat/upload/CoffeechatForm/types.ts
  src/components/coffeechat/upload/ProgressBox/index.stories.tsx
  src/components/coffeechat/upload/ProgressBox/index.tsx
  src/components/coffeechat/upload/UploadHeader/index.stories.tsx
  src/components/coffeechat/upload/UploadHeader/index.tsx
  src/components/common/form/FormTitle.tsx
  src/components/common/form/TextFieldLineBreak/index.stories.tsx
  src/components/common/form/TextFieldLineBreak/index.tsx
  src/constants/links.ts
  src/pages/coffeechat/edit/[id].tsx
  src/pages/coffeechat/upload.tsx
Labels: size/XXL

#1647 feat: 커피챗 마무리작업
  src/api/endpoint/coffeechat/getCoffeechatDetail.ts
  src/components/coffeechat/CoffeeChatCategory/index.tsx
  src/components/coffeechat/CoffeeRecentChatList/index.tsx
  src/components/coffeechat/Loading/index.tsx
  src/components/coffeechat/detail/OpenerProfile/index.tsx
  src/components/coffeechat/detail/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/ChipField/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/CoffeechatInfoForm/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/MyInfoForm/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/schema.ts
  src/components/coffeechat/upload/CoffeechatForm/types.ts
  src/components/common/form/TextFieldLineBreak/index.tsx
  src/pages/coffeechat/edit/[id].tsx
  src/pages/coffeechat/index.tsx
  src/pages/coffeechat/upload.tsx
Labels: size/XL

#1618 feat: Empty View 컴포넌트 분리
  src/components/common/EmptyView/index.tsx
  src/components/members/main/MemberList/index.tsx
  src/components/projects/main/ProjectList.tsx
Labels: size/L

#1641 feat: 커피챗 상세 더보기 구현
  src/api/endpoint/coffeechat/deleteCoffeechat.ts
  src/components/coffeechat/detail/OpenerProfile/index.tsx
  src/components/coffeechat/detail/SeemoreSelect/index.tsx
  src/components/coffeechat/detail/index.tsx
  src/components/members/detail/GroupSection/index.tsx
  src/components/members/detail/ProjectSection/index.tsx
  src/pages/_app.tsx
Labels: size/L

#1664 fix: 모바일 gnb 하단 여백 수정
  src/components/feed/page/layout/MobileCommunityLayout.tsx
Labels: size/XS

#1662 feat: 커피챗 오픈하기 모달 추가
  src/components/coffeechat/CoffeeRecentChatList/index.tsx
Labels: size/M

#1657 feat: 커피챗 오픈, 상세 로깅
  src/components/coffeechat/detail/RegisterCoffeechatButton/index.tsx
  src/components/coffeechat/detail/SeemoreSelect/index.tsx
  src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx
  src/components/eventLogger/events.ts
  src/pages/coffeechat/edit/[id].tsx
  src/pages/coffeechat/upload.tsx
Labels: size/L

#1660 feat: 커피챗 메인 QA, 배너, 로깅 추가
  package.json
  public/lottie/coffee_MO.json
  public/lottie/coffee_PC.json
  src/components/coffeechat/Banner/CoffeeChatLottie.tsx
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeChatCategory/index.tsx
  src/components/coffeechat/CoffeeChatModal/CoffeeChatModal.tsx
  src/components/coffeechat/CoffeeRecentChatList/index.tsx
  src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx
  src/components/common/Divider/Divider.tsx
  src/components/eventLogger/events.ts
  src/pages/coffeechat/index.tsx
  yarn.lock
Labels: size/L

#1655 feat: 멤버 로깅 추가
  src/components/eventLogger/events.ts
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/detail/MessageSection/index.tsx
  src/components/members/main/MemberCard/index.tsx
  src/components/members/main/MemberList/index.tsx
Labels: size/L

#1666 fix: 커피챗 QA
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeChatCategory/index.tsx
  src/components/coffeechat/detail/index.tsx
  src/components/members/detail/ProjectSection/index.tsx
Labels: size/S

#1656 test: Amplitude User Properties 추가
  src/components/eventLogger/controllers/amplitude.ts
  src/components/eventLogger/controllers/consoleLog.ts
  src/components/eventLogger/controllers/storybookAction.ts
  src/components/eventLogger/events.ts
  src/components/eventLogger/providers/AmplitudeProvider.tsx
  src/components/eventLogger/types.ts
Labels: size/M

#1665 feat: 커피챗 QA
  package.json
  src/api/endpoint/coffeechat/getCoffeechatDetail.ts
  src/api/endpoint/members/getMemberOfMe.ts
  src/components/coffeechat/CoffeeRecentChatList/index.tsx
  src/components/coffeechat/detail/CoffeechatContents/index.tsx
  src/components/coffeechat/detail/OpenerProfile/index.tsx
  src/components/coffeechat/detail/SeemoreSelect/index.tsx
  src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx
  src/components/coffeechat/detail/index.tsx
  src/components/coffeechat/page/layout/MobileCoffeechatUploadLayout.tsx
  src/components/coffeechat/upload/CoffeechatForm/CoffeechatInfoForm/index.tsx
  src/pages/coffeechat/edit/[id].tsx
  src/pages/coffeechat/upload.tsx
  yarn.lock
Labels: size/L

#1670 fix: qa 적용
  src/components/coffeechat/Banner/CoffeeChatLottie.tsx
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeChatCategory/index.tsx
  src/components/coffeechat/CoffeeRecentChatList/index.tsx
  src/components/coffeechat/detail/SeemoreSelect/index.tsx
Labels: size/S

#1671 feat: 커피챗 qa
  src/components/coffeechat/detail/SeemoreSelect/index.tsx
  src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx
  src/components/coffeechat/detail/index.tsx
  src/components/coffeechat/page/CoffeechatUploadPage.tsx
  src/components/coffeechat/upload/CoffeechatForm/MyInfoForm/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/SubmitDialog/index.stories.tsx
  src/components/coffeechat/upload/CoffeechatForm/SubmitDialog/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/UploadButton/index.tsx
  src/pages/coffeechat/edit/[id].tsx
  src/pages/coffeechat/upload.tsx
Labels: size/M

#1674 feat: 커피챗 qa
  src/components/coffeechat/detail/SeemoreSelect/index.tsx
  src/components/coffeechat/detail/ShowCoffeechatToggle/index.tsx
  src/components/coffeechat/detail/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/MyInfoForm/index.tsx
  src/pages/coffeechat/edit/[id].tsx
  src/pages/coffeechat/upload.tsx
Labels: size/M

#1675 feat: css 수정
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/detail/SeemoreSelect/index.tsx
Labels: size/M

#1676 refactor: 쿼리키 무효화 반영되지 않는 이슈 수정
  src/components/coffeechat/detail/SeemoreSelect/index.tsx
Labels: size/S

#1678 Hotfix: 커피챗 디자인 QA 수정
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeRecentChatList/index.tsx
Labels: size/M

#1681 feat: 창업 중 경력 옵션 추가
  src/components/coffeechat/upload/CoffeechatForm/constants.ts
Labels: size/XS

#1683 feat: 쪽지 보내기 모달 mds로 변경 및 반응형 처리
  src/components/coffeechat/CoffeeChatModal/CoffeeChatModal.tsx
  src/components/members/detail/MessageSection/MessageModal.tsx
  src/components/members/detail/MessageSection/Modal.tsx
Labels: size/L

#1685 feat: 프로필 등록 완료 페이지 내 멤버카드를 mds 디자인으로 변경
  src/components/members/main/MemberCard/index.tsx
  src/components/members/upload/complete/MemberCardOfMe.tsx
Labels: size/M

#1686 Hotfix: User Property 필드 수정
  src/api/endpoint/members/ getMemberProperty.ts
  src/components/eventLogger/events.ts
  src/components/eventLogger/providers/AmplitudeProvider.tsx
Labels: size/M

#1689 feat: 창업 중 필터링 추가
  src/components/coffeechat/constants/index.ts
Labels: size/L

#1690 feat: 광고 구좌 변경
  src/components/common/Banner/AdsBanner/AdsBox/index.tsx
  src/components/common/Banner/AdsBanner/constants/ads.ts
  src/components/common/Banner/AdsBanner/index.tsx
Labels: size/M

#1692 fix: 멤버 프로필 기본 이미지 수정
  src/components/members/detail/ProfileSection/index.tsx
  src/components/members/main/MemberCard/index.tsx
Labels: 🐛 Bug, size/M

#1694 feat: 11/26 광고 구좌 변경
  src/components/common/Banner/AdsBanner/constants/ads.ts
Labels: size/S
