Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-02, with the labels that each got.

#1291 fix: 콘텐츠 카드 max-width 설정
  src/components/common/ContentsCard/index.tsx
Labels: size/XS

#1293 chore: 4기 지원 가능 날짜 변경
  src/components/makers/Notifier.tsx
Labels: size/XS

#1292 refactor: 컨텐츠 카드 가로 길이 문제 해결
  src/components/common/ContentsCard/index.tsx
  src/components/members/detail/MemberDetail.tsx
  src/components/members/detail/MemberProjectCard.tsx
Labels: size/S

#1294 chore: 4기 모집 중 멘트 내리기
  src/components/makers/Notifier.tsx
Labels: size/S

#1297 refactor: mainCategoryId 따로 저장하는 로직 걷어내기
  src/components/feed/common/hooks/useCategory.ts
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategoryHeader/index.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/Category/CategorySelector/index.stories.tsx
  src/components/feed/upload/Category/CategorySelector/index.tsx
  src/components/feed/upload/Category/TagSelector/TagSelectOptions.tsx
  src/components/feed/upload/Category/TagSelector/index.stories.tsx
  src/components/feed/upload/Category/TagSelector/index.tsx
  src/components/feed/upload/Category/index.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
  src/components/feed/upload/types.ts
  src/pages/feed/edit/[id].tsx
  src/pages/feed/upload.tsx
Labels: size/L

#1301 feat: 34기 적용
  src/constants/generation.ts
Labels: size/XS
