Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-05, with the labels that each got.

#1400 chore: 활동 정보 확인 모달 스타일링 수정
  src/components/members/hooks/useRegisterModal.tsx
Labels: size/S

#1409 fix: 솝커톤용 임시 게시물 hover 이벤트 추가
  src/components/feed/list/FeedCard.tsx
Labels: size/XS

#1405 feat: 프로젝트 등록 후 슬라이드 업 구현
  src/components/common/SlideUp/SlideUpEntry.stories.tsx
  src/components/common/SlideUp/SlideUpEntry.tsx
  src/components/common/SlideUp/context.ts
  src/components/common/SlideUp/providers/SlideUpProvider.tsx
  src/components/common/SlideUp/types.tsx
  src/components/common/SlideUp/useToast.ts
  src/pages/_app.tsx
  src/pages/projects/upload/index.tsx
Labels: size/L

#1411 feat: 프로젝트 등록 후 팝업 공유하러 가기 클릭 이벤트 로깅
  src/components/eventLogger/events.ts
  src/pages/projects/upload/index.tsx
Labels: size/XS

#1413 fix: 388번 게시물에 대해 솝커톤용 UI 지정
  src/components/feed/list/FeedCard.tsx
Labels: size/XS

#1419 fix: 솝커톤용 UI 내리기
  src/components/feed/list/FeedCard.stories.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
Labels: size/S

#1420 feat: 멤버 프로필 상세 및 등록/수정 페이지 UI 수정
  public/icons/icon-behance-gray.svg
  public/icons/icon-facebook-gray.svg
  public/icons/icon-github-gray.svg
  public/icons/icon-instagram-gray.svg
  public/icons/icon-link-gray.svg
  public/icons/icon-linkedin-gray.svg
  src/api/endpoint/members/putMemberProfile.ts
  src/api/endpoint_LEGACY/members/type.ts
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/detail/CareerSection/CareerItem.tsx
  src/components/members/detail/CareerSection/index.tsx
  src/components/members/detail/InterestSection/index.stories.tsx
  src/components/members/detail/InterestSection/index.tsx
  src/components/members/detail/MessageSection/index.tsx
  src/components/members/upload/FormSection/Career.tsx
  src/components/members/upload/FormSection/Tmi/index.tsx
  src/components/members/upload/schema.ts
  src/components/members/upload/types.ts
  src/components/mentoring/MentoringDetail/index.tsx
  src/pages/members/edit.tsx
  src/pages/members/upload.tsx
Labels: size/L

#1422 fix: 멤버 프로필 필터링 오류 해결
  src/components/members/common/select/Select.tsx
  src/components/members/main/MemberList/index.tsx
Labels: size/S

#1415 feat: 멤버 프로필 필터링 수정
  src/api/endpoint/members/getMembersSearchByName.ts
  src/components/eventLogger/events.ts
  src/components/members/common/select/Select.tsx
  src/components/members/main/MemberCard/MessageButton.tsx
  src/components/members/main/MemberList/filters/MemberListFilter.tsx
  src/components/members/main/MemberList/filters/constants.ts
  src/components/members/main/MemberList/index.tsx
  src/components/projects/upload/hooks/useGetMembersByNameQuery.ts
Labels: size/L

#1423 feat: 카카오톡 채팅 기능 추가
  src/components/common/Footer/index.tsx
  src/components/common/Header/mobile/MobileSideBar.tsx
  src/components/common/KakaoScript/index.tsx
  src/hooks/useKakao.ts
  src/kakao.d.ts
  src/pages/_app.tsx
Labels: size/L
