Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-07, with the labels that each got.

#1460 feat: 활동 후기 페이지 세팅
  .storybook/preview.tsx
  package.json
  public/mockServiceWorker.js
  src/components/common/Example/index.stories.tsx
  src/components/remember/index.tsx
  src/components/remember/mocks/browser.ts
  src/components/remember/mocks/handlers.ts
  src/pages/remember/index.tsx
  yarn.lock
Labels: size/XL

#1462 Feat: 다짐메시지 모달 UI
  src/api/endpoint/resolution/postResolution.ts
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/members/upload/complete/CardBack.tsx
  src/components/members/upload/complete/MemberCardOfMe.tsx
  src/components/resolution/constants.ts
  src/components/resolution/read/ResolutionBackground.tsx
  src/components/resolution/read/ResolutionMessage.tsx
  src/components/resolution/read/ResolutionReadModal.tsx
  src/components/resolution/read/images.tsx
  src/components/resolution/submit/ResolutionSubmitModal.tsx
  src/components/resolution/submit/useConfirmResolution.ts
  src/components/resolution/submit/useOpenResolutionModal.ts
  src/pages/index.tsx
  src/pages/members/complete.tsx
Labels: size/XL

#1465 fix: 다짐메시지 테스트 삭제
  src/pages/index.tsx
Labels: size/XS

#1466 feat: 활동 후기 메시지 전시 구현
  package.json
  src/api/endpoint/remember/getReviews.ts
  src/api/endpoint/remember/uploadReview.ts
  src/components/remember/index.tsx
  src/components/remember/mocks/handlers.ts
  src/components/remember/reviews/ReviewCard/index.stories.tsx
  src/components/remember/reviews/ReviewCard/index.tsx
  src/components/remember/reviews/index.tsx
  src/pages/remember/index.tsx
  yarn.lock
Labels: size/L

#1470 feat: 활동 후기 메시지 input 구현
  src/api/endpoint/remember/uploadReview.ts
  src/components/remember/ReviewInput/index.tsx
  src/components/remember/index.tsx
Labels: size/L

#1472 feat: 활동 후기 페이지 수정
  src/api/endpoint/remember/getReviews.ts
  src/api/endpoint/remember/uploadReview.ts
  src/components/remember/ReviewInput/index.tsx
  src/components/remember/index.tsx
  src/components/remember/reviews/index.tsx
  src/pages/remember/index.tsx
Labels: size/L

#1477 chore: 회원가입 전화번호 placeholder 수정
  src/components/auth/register/verify/view/ByPhoneView.tsx
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
  src/pages/remember/index.tsx
Labels: size/L

#1479 feat: 전화번호 - 조건 삭제
  src/components/members/upload/FormSection/Basic/index.tsx
  src/components/members/upload/schema.ts
Labels: size/S

#1482 feat: 전화번호 에러 메시지 수정
  src/components/auth/register/verify/useByPhone.ts
  src/components/auth/reset/useResetLogin.ts
  src/components/members/upload/schema.ts
Labels: size/S

#1483 fix: 활동 후기 타입 에러 수정
  src/api/endpoint/remember/getReviews.ts
  src/components/remember/reviews/index.tsx
Labels: size/S

#1484 feat: 활동 후기 qa
  src/api/endpoint/remember/getReviews.ts
  src/components/remember/index.tsx
Labels: size/S

#1486 Feat: 다짐메시지 관련 QA 반영
  src/components/common/Banner/ClosingCeremonyBanner/index.tsx
  src/components/feed/page/layout/DesktopCommunityLayout.tsx
  src/components/resolution/read/ResolutionReadModal.tsx
  src/components/resolution/read/hooks/useImageDownload.ts
Labels: 🐛 Bug, size/S

#1488 fix: 무한스크롤 수정
  src/api/endpoint/remember/getReviews.ts
  src/components/remember/reviews/index.tsx
Labels: size/S

#1489 chore: 무한스크롤 크기 수정
  src/api/endpoint/remember/getReviews.ts
Labels: size/XS

#1493 chore: 5기 모집 중 텍스트 변경
  src/components/makers/AboutMakers.tsx
  src/components/makers/Notifier.tsx
Labels: size/S

#1494 chore: 텍스트 변경
  src/components/makers/AboutMakers.tsx
Labels: size/XS
