Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-01, with the labels that each got.

#1268 feat: 프로젝트 업로드 > 보라색 걷어내기 수정
  src/components/common/form/FormProgress.tsx
  src/components/projects/upload/form/ProjectForm.tsx
  src/components/projects/upload/form/fields/CategoryField.tsx
  src/components/projects/upload/form/fields/GenerationField.tsx
  src/components/projects/upload/form/fields/LinkField.tsx
  src/components/projects/upload/form/fields/MemberField.tsx
  src/components/projects/upload/form/fields/PeriodField.tsx
  src/components/projects/upload/form/fields/ServiceTypeField.tsx
  src/components/projects/upload/form/fields/StatusField.tsx
  src/components/projects/upload/form/fields/member/MemberSearch.tsx
Labels: size/M

#1270 feat: 프로젝트 리스트 무한스크롤 적용
  src/api/endpoint/projects/getProjects.ts
  src/api/endpoint_LEGACY/hooks/projects.ts
  src/api/endpoint_LEGACY/projects/index.ts
  src/api/endpoint_LEGACY/projects/type.ts
  src/components/projects/main/ProjectList.tsx
  src/components/projects/upload/hooks/useGetProjectListQuery.ts
Labels: size/L

#1265 feat: 피드 수정 구현
  .vscode/settings.json
  src/api/endpoint/feed/editFeed.ts
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/uploadFeed.ts
  src/components/eventLogger/events.ts
  src/components/feed/common/hooks/useCategory.ts
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/edit/EditImpossibleModal.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategoryHeader/index.tsx
  src/components/feed/upload/Category/index.tsx
  src/components/feed/upload/Input/ContentsInput/index.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
  src/components/feed/upload/types.ts
  src/constants/links.ts
  src/pages/feed/edit/[id].tsx
  src/pages/feed/upload.tsx
Labels: size/L

#1275 feat: 새로운 로그인 화면 적용
  src/components/intro/sections/CatchPhrase/icons.tsx
  src/components/intro/sections/CatchPhrase/index.tsx
  src/pages/auth/login.tsx
  src/styles/typography.ts
Labels: size/L

#1276 fix: 로그인 화면 클릭 안됨 오류 해결
  src/pages/auth/login.tsx
Labels: size/L

#1279 feat: 프로젝트 검색 기능 추가 / 업로드 버튼 플로팅으로 변경
  src/components/projects/main/ProjectList.tsx
  src/components/projects/main/ProjectSearch.tsx
Labels: size/L

#1281 feat: 4기 모집 준비 대응
  src/components/intro/sections/Footer.tsx
  src/components/makers/Notifier.tsx
Labels: size/S

#1283 fix: feed edit 페이지 라우팅 이슈 해결
  functions/feed/edit/[id].ts
Labels: size/S

#1285 feat: 프로젝트 리스트 필터 3종 추가
  src/api/endpoint_LEGACY/projects/type.ts
  src/components/members/common/select/context.ts
  src/components/projects/main/ProjectCategorySelect.stories.tsx
  src/components/projects/main/ProjectCategorySelect.tsx
  src/components/projects/main/ProjectFilterChip.stories.tsx
  src/components/projects/main/ProjectFilterChip.tsx
  src/components/projects/main/ProjectList.tsx
Labels: size/L

#1280 feat: 프로필 내 프로젝트 카드 변경
  src/components/members/detail/MemberDetail.tsx
  src/components/members/detail/MemberProjectCard.tsx
  src/components/members/detail/MemberProjectCardLegacy.tsx
Labels: size/L

#1287 feat: 프로젝트 리스트 모바일 화면 들썩임 현상 수정
  src/components/projects/main/ProjectList.tsx
Labels: size/XS

#1288 fix: 프로젝트 리스트 모바일 > padding 위치 수정
  src/components/projects/main/ProjectList.tsx
Labels: size/XS

#1289 feat: 프로젝트 필터 스토리 추가
  src/components/projects/main/ProjectCategorySelect.stories.tsx
Labels: size/M

#1290 chore: 4기 모집 시작으로 워딩 변경
  src/components/makers/Notifier.tsx
  src/components/makers/data/generation3.ts
Labels: size/XS
