Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-12, with the labels that each got.

#1706 feat: 커피챗 상세 페이지 로직 변경 및 리패치
  src/components/coffeechat/Banner/CoffeeChatLottie.tsx
  src/components/coffeechat/detail/OpenerProfile/index.tsx
Labels: ✨ Feature, size/S

#1704 refactor: 커뮤니티 글쓰기 이미지 디바운싱
  src/hooks/useImageUploader.ts
Labels: size/M

#1709 feat: 광고 구좌 변경
  src/components/common/Banner/AdsBanner/constants/ads.ts
  src/hooks/useImageUploader.ts
Labels: size/M

#1712 refactor: 광고 구좌 이미지 수정
  src/components/common/Banner/AdsBanner/constants/ads.ts
Labels: size/XS

#1713 refactor: 커피챗 커리어 타입 수정
  src/components/coffeechat/upload/CoffeechatForm/types.ts
  src/pages/coffeechat/edit/[id].tsx
Labels: size/XS

#1715 fix: 커피챗 상세 페이지 QA 적용
  src/components/coffeechat/detail/index.tsx
Labels: 🌟 QA, size/S
