Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-08, with the labels that each got.

#1496 fix: 다짐메시지 배너 내리기
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
Labels: 🐛 Bug, size/L

#1498 fix: 끝말잇기 max-width 변경
  src/components/feed/page/layout/DesktopCommunityLayout.tsx
Labels: 🐛 Bug, size/XS

#1499 feat: 멤버 프로필 등록 / 수정 페이지 - 커피챗 기능 구현
  package.json
  public/icons/icon-coffee.svg
  src/api/endpoint_LEGACY/members/type.ts
  src/components/common/Input/index.tsx
  src/components/members/upload/FormSection/Career.tsx
  src/components/members/upload/FormSection/CoffeeChat.tsx
  src/components/members/upload/constants.ts
  src/components/members/upload/forms/Form.tsx
  src/components/members/upload/schema.ts
  src/components/members/upload/types.ts
  src/pages/_app.tsx
  src/pages/members/edit.tsx
  src/pages/members/upload.tsx
  src/styles/global.ts
  yarn.lock
Labels: size/XXL

#1502 feat: 멤버 목록 페이지 - 커피챗 활성화 멤버 목록 조회
  public/icons/icon-coffeechat.svg
  public/icons/icon-send.svg
  public/icons/img/coffeechat_sample1.png
  public/icons/img/coffeechat_sample2.png
  public/icons/img/coffeechat_sample3.png
  src/api/endpoint/members/getMembersCoffeeChat.ts
  src/api/endpoint_LEGACY/members/type.ts
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeChatList/index.tsx
  src/components/coffeechat/constants/index.ts
  src/components/common/HorizontalScroller/index.tsx
  src/components/members/detail/MessageSection/MessageModal.tsx
  src/components/members/main/MemberCard/MessageButton.tsx
  src/components/members/main/MemberCard/index.tsx
  src/components/members/main/MemberList/index.tsx
  src/components/members/upload/FormSection/CoffeeChat.tsx
  src/components/mentoring/MentoringDetail/index.tsx
  src/constants/links.ts
  src/pages/members/index.tsx
Labels: size/XL

#1504 feat: 커피챗 활성화/비활성화시 커피챗 활성화 멤버 목록 invalidate
  src/api/endpoint/members/putMemberProfile.ts
  src/pages/members/upload.tsx
Labels: size/XS

#1509 feat: 커피챗 기능 QA 대응
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeChatList/index.tsx
  src/components/members/detail/MessageSection/MessageModal.tsx
Labels: size/L

#1511 feat: 커피챗 기능 클릭 이벤트 로깅
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeChatList/index.tsx
  src/components/eventLogger/events.ts
  src/components/members/main/MemberCard/MessageButton.tsx
  src/components/members/upload/FormSection/CoffeeChat.tsx
Labels: size/M

#1505 feat: 광고 구좌 구현
  package.json
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/components/common/Banner/AdsBanner/AdsBox/index.tsx
  src/components/common/Banner/AdsBanner/constants/ads.ts
  src/components/common/Banner/AdsBanner/index.tsx
  src/components/feed/page/layout/DesktopCommunityLayout.tsx
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
  src/pages/_app.tsx
  yarn.lock
Labels: size/L

#1513 feat: 상세 프로필 커피챗 아이콘 노출 및 직무 기간 변경 이슈 해결
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/upload/FormSection/Career.tsx
Labels: size/M

#1516 feat: 광고 배너 유무에 따른 끝말잇기 배너 변경
  src/components/common/Banner/AdsBanner/constants/ads.ts
  src/components/feed/page/layout/DesktopCommunityLayout.tsx
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
Labels: size/L

#1519 feat: 커피챗 활성화 유저 없을 경우 처리
  src/components/coffeechat/CoffeeChatList/index.tsx
Labels: size/XS

#1517 feat: 광고 배너 qa 반영
  src/components/common/Banner/AdsBanner/AdsBox/index.tsx
  src/components/common/Banner/AdsBanner/constants/ads.ts
  src/components/common/Banner/AdsBanner/index.tsx
Labels: size/M

#1524 feat: mds 반응형 적용
  package.json
  src/styles/global.ts
  yarn.lock
Labels: size/S

#1526 fix: 프로필 수정 페이지에서 skill 항목 null safety 처리
  src/pages/members/edit.tsx
Labels: 🐛 Bug, size/XS

#1529 chore: 랜덤 리뷰어 리스트에 하윤, 도영 추가
  .github/actions/randomReviewer.js
Labels: size/XS
