Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-06, with the labels that each got.

#1427 chore: 카카오톡 채널 연동 테스트
  src/components/common/KakaoScript/index.tsx
  src/hooks/useKakao.ts
Labels: size/M

#1429 feat: 멤버 프로필 링크 디자인 수정
  public/icons/icon-behance-gray.svg
  public/icons/icon-facebook-gray.svg
  public/icons/icon-github-gray.svg
  public/icons/icon-instagram-gray.svg
  public/icons/icon-link-gray.svg
  public/icons/icon-linkedin-gray.svg
  src/components/members/detail/CareerSection/index.tsx
Labels: size/L

#1434 chore: 카카오톡 앱 키 명칭 변경
  src/hooks/useKakao.ts
Labels: size/XS

#1424 feat: 끝말잇기 이관 작업
  public/icons/icon-message-chat.svg
  src/components/feed/list/FeedList.tsx
  src/components/feed/page/layout/DesktopCommunityLayout.tsx
  src/components/feed/page/layout/MobileCommunityLayout.tsx
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
  src/components/wordchain/WordchainEntry/WordchainMessage.stories.tsx
  src/components/wordchain/WordchainEntry/WordchainMessage.tsx
Labels: size/L

#1433 Fix: Desktop Header 배포
  .env.development
  playground-common/README.md
  playground-common/export.ts
  playground-common/package.json
Labels: size/S

#1435 chore: 우승자의 경우 폰트 흰색 컬러 적용되도록 prop 내려주기
  src/components/wordchain/WordchainEntry/WordchainMessage.tsx
Labels: size/XS

#1439 feat: 끝말잇기 진입점 모바일 반응형
  src/components/feed/list/MenuEntryIcons/MenuEntryIcons.tsx
  src/components/feed/page/layout/MobileCommunityLayout.tsx
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
Labels: size/M

#1441 fix: 메뉴 클릭 영역 수정
  src/components/feed/list/MenuEntryIcons/MenuEntryIcons.tsx
Labels: size/XS

#1443 feat: 모바일 메뉴 진입점 스타일링 수정
  src/components/feed/list/MenuEntryIcons/MenuEntryIcons.tsx
Labels: size/S

#1445 feat: 모바일 메뉴 호버
  src/components/feed/list/MenuEntryIcons/MenuEntryIcons.tsx
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
Labels: size/XS

#1449 fix: getMembersSearchByName parameter 네이밍 수정
  src/api/endpoint/members/getMembersSearchByName.ts
Labels: size/XS

#1447 fix: 끝말잇기 탭 제거
  src/components/common/Header/desktop/DesktopHeader.tsx
Labels: size/XS

#1451 feat: DesktopHeader에서 끝말잇기를 제거한 수정본 배포
  playground-common/package.json
Labels: size/XS

#1453 chore: 이메일 마스킹 코드 제거
  src/api/endpoint_LEGACY/members/type.ts
  src/components/members/upload/FormSection/Basic/index.tsx
  src/components/members/upload/constants.ts
  src/components/members/upload/types.ts
  src/pages/members/edit.tsx
  src/pages/members/upload.tsx
Labels: size/S
