Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-04, with the labels that each got.

#1377 chore: 댓글, 조회수 미리보기 내리기
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
Labels: size/M

#1374 fix: 프로필 등록 완료 페이지에 AuthRequired 추가
  src/pages/members/complete.tsx
Labels: 🐛 Bug, size/XS

#1378 fix: 끝말잇기 이용규칙 디자인 수정
  src/components/wordchain/WordchainRules.tsx
Labels: 🐛 Bug, size/M

#1380 feat: 커뮤니티 UI 수정 및 익명처리 경고문 변경
  public/icons/icon-pencil-simple.svg
  src/components/feed/common/hooks/useBlindWriterPromise.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
Labels: size/M

#1381 chore: 피드 업로드 시간 미리보기 삭제
  src/components/feed/list/FeedCard.tsx
Labels: size/XS

#1385 feat: 익명프로필 구현하기
  src/api/endpoint/feed/getComment.ts
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailComments.tsx
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/list/FeedCard.stories.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
Labels: size/L

#1384 feat: 커뮤니티 게시물 좋아요 기능 추가
  package.json
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/api/endpoint/feed/postLike.ts
  src/components/feed/common/FeedLike.tsx
  src/components/feed/common/Icon.tsx
  src/components/feed/common/hooks/useToggleLike.ts
  src/components/feed/detail/DetailFeedCard.stories.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/list/FeedCard.stories.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
  yarn.lock
Labels: size/XL

#1386 fix: 익명프로필 없는 익명 유저 대응
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedListItems.tsx
Labels: size/S

#1388 chore: 모바일 피드 업로드 헤더 고정
  src/components/feed/page/FeedUploadPage.tsx
Labels: size/M

#1390 fix: 글쓰기 버튼 mds에 맞게 수정
  src/components/feed/list/FeedList.tsx
Labels: size/S

#1392 feat: 좋아요 클릭에 로깅 추가
  src/components/eventLogger/events.ts
  src/components/feed/list/FeedListItems.tsx
Labels: size/M

#1394 chore: 모바일 헤더 앞으로 오도록 수정
  src/components/feed/page/FeedUploadPage.tsx
Labels: size/XS

#1396 chore: 댓글 익명프로필 엑박 이슈 해결
  src/components/feed/detail/DetailFeedCard.tsx
Labels: size/XS

#1398 fix: 게시글 및 댓글 생성날짜 null 예외처리
  src/components/feed/detail/DetailFeedCard.tsx
Labels: size/XS

#1393 fix: 프로필 추가 버튼 보이지 않는 문제 해결
  src/components/members/upload/AddableWrapper.tsx
Labels: size/XS

#1402 fix: 피드 레이아웃과 좋아요/댓글 텍스트 디자인 수정
  src/components/feed/common/FeedLike.tsx
  src/components/feed/list/FeedCard.tsx
Labels: size/XS
