Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-09, with the labels that each got.

#1532 fix: 서버 타입 에러 검증 실패 오류 수정
  src/api/endpoint/feed/getPosts.ts
  src/components/feed/list/FeedListItems.tsx
Labels: size/XS

#1536 fix: 프로젝트 필터링 결과 없을때 예외처리 및 반응형 작업
  src/api/endpoint_LEGACY/projects/type.ts
  src/components/projects/main/ProjectList.tsx
  src/components/projects/upload/hooks/useGetProjectListQuery.ts
Labels: size/L

#1541 feat: 광고 구좌 고도화
  src/components/common/Banner/AdsBanner/AdsBox/index.tsx
  src/components/common/Banner/AdsBanner/constants/ads.ts
  src/components/common/Banner/AdsBanner/index.tsx
  src/components/eventLogger/events.ts
Labels: size/L

#1537 feat: 커피챗/ 쪽지 보내기 기능 고도화, NotOverlay Confirm 모달 구현
  src/components/common/Modal/useCustomConfirm.tsx
  src/components/members/detail/MessageSection/MessageModal.tsx
  src/components/members/detail/MessageSection/Modal.tsx
  src/components/members/main/MemberCard/index.tsx
  src/components/members/main/MemberList/index.tsx
  src/hooks/useOnClickOutside.ts
Labels: size/L

#1544 docs: README.md 프로젝트 소개 업데이트 및 멤버 변경
  README.md
Labels: size/M

#1547 docs: readme 레이아웃 수정
  README.md
Labels: size/S

#1542 chore: 광고 구좌 qa 반영
  src/components/common/Banner/AdsBanner/AdsBox/index.tsx
  src/components/common/Banner/AdsBanner/constants/ads.ts
  src/components/common/Banner/AdsBanner/index.tsx
Labels: size/M

#1549 fix: '만든 사람들' 페이지에서 35기 모집 멘트 내리기
  src/components/makers/Notifier.tsx
Labels: 📖 Docs, size/S

#1551 fix: makers 페이지 멘트 오타 수정
  src/components/makers/Notifier.tsx
Labels: 📖 Docs, size/XS

#1553 chore: 광고 고화질 사진으로 변경
  src/components/common/Banner/AdsBanner/constants/ads.ts
Labels: size/S

#1555 feat: 게시글 신고 Toast mds로 변경 및 멤버 신고/차단 기능 추가
  package.json
  public/icons/icon-dots-vertical.svg
  src/api/endpoint/members/postBlockMember.ts
  src/api/endpoint/members/postReportMember.ts
  src/components/common/Modal/parts/index.tsx
  src/components/common/Modal/useConfirm.tsx
  src/components/feed/common/FeedDropdown.tsx
  src/components/feed/common/hooks/useReportFeed.ts
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/hooks/useBlockMember.ts
  src/components/members/hooks/useReportMember.ts
  yarn.lock
Labels: size/L

#1559 Revert "feat: 게시글 신고 Toast mds로 변경 및 멤버 신고/차단 기능 추가 (#1555)"
  package.json
  public/icons/icon-dots-vertical.svg
  src/api/endpoint/members/postBlockMember.ts
  src/api/endpoint/members/postReportMember.ts
  src/components/common/Modal/parts/index.tsx
  src/components/common/Modal/useConfirm.tsx
  src/components/feed/common/FeedDropdown.tsx
  src/components/feed/common/hooks/useReportFeed.ts
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/hooks/useBlockMember.ts
  src/components/members/hooks/useReportMember.ts
  yarn.lock
Labels: size/L

#1558 feat: 코드잇 2차 광고 구좌 변경
  src/components/common/Banner/AdsBanner/constants/ads.ts
Labels: size/S

#1560 feat: 게시글 신고 Toast mds로 변경 및 멤버 신고/차단 기능 추가
  package.json
  public/icons/icon-dots-vertical.svg
  src/api/endpoint/members/postBlockMember.ts
  src/api/endpoint/members/postReportMember.ts
  src/components/common/Modal/parts/index.tsx
  src/components/common/Modal/useConfirm.tsx
  src/components/feed/common/FeedDropdown.tsx
  src/components/feed/common/hooks/useDeleteComment.ts
  src/components/feed/common/hooks/useReportComment.ts
  src/components/feed/common/hooks/useReportFeed.ts
  src/components/feed/detail/FeedDetail.tsx
  src/components/feed/detail/FeedDetailComments.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/hooks/useBlockMember.ts
  src/components/members/hooks/useReportMember.ts
  yarn.lock
Labels: size/L

#1554 feat: 메이커스 35기 갱신
  src/components/makers/data/generation35.ts
  src/components/makers/data/index.ts
  src/constants/generation.ts
Labels: size/L

#1565 feat: 다짐메시지 모달
  src/components/common/form/FormItem.tsx
  src/components/resolution/submit/ResolutionSubmitModal.tsx
  src/components/resolution/submit/useConfirmResolution.ts
  src/components/resolution/submit/useOpenResolutionModal.ts
Labels: size/M

#1566 feat: 프로필 등록 완료 페이지
  public/logos/and-sopt.svg
  src/components/members/upload/complete/CardBack.tsx
  src/pages/members/complete.tsx
Labels: size/L

#1556 fix: Custom Confirm 컴포넌트 디자인 변경점 적용
  src/components/common/Modal/useCustomConfirm.tsx
  src/components/members/detail/MessageSection/MessageModal.tsx
Labels: size/M

#1570 feat: 홈 로딩 스켈레톤 적용
  src/components/common/Banner/WelcomeBanner/Welcome35.tsx
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/common/Skeleton/index.tsx
  src/components/feed/list/CategorySkeleton.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/feed/list/FeedSkeleton.tsx
  src/components/wordchain/WordchainEntry/WordChainEntry.tsx
  src/components/wordchain/WordchainEntry/WordchainSkeleton.tsx
Labels: ✨ Feature, size/L

#1572 fix: 다짐메시지, 환영배너, 프로필 등록 완료 QA 반영
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/common/Modal/index.tsx
  src/components/members/upload/complete/CardBack.tsx
  src/components/resolution/submit/ResolutionSubmitModal.tsx
Labels: 🐛 Bug, size/L

#1576 feat: 35기 로고 추가
  public/icons/logo/time=35.svg
Labels: ✨ Feature, size/XS

#1568 fix: mds 와의 스타일 충돌 해결
  src/components/debug/SideBar.tsx
  src/components/projects/upload/form/fields/LinkField.tsx
  src/styles/reset.ts
Labels: size/XS

#1579 fix: skill이 공백인 경우 예외처리
  src/components/members/upload/schema.ts
Labels: size/XS

#1581 fix: 커뮤니티 임원진 파트 표기 수정
  src/components/feed/common/utils.ts
Labels: 🐛 Bug, size/XS
