Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-10, with the labels that each got.

#1583 fix: makers 35기 -> 35기 makers로 표기 변경
  src/components/makers/Notifier.tsx
Labels: 🐛 Bug, size/S

#1587 fix: 애플 로그인 계정 재설정 유도 텍스트 수정
  src/pages/auth/login.tsx
Labels: size/XS

#1585 fix: 플랫폼 팀원 업데이트
  src/components/makers/data/generation35.ts
Labels: size/XS

#1589 feat: 환영배너 내리기 및 프로필 등록 완료 기존 버전으로 롤백
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/components/common/Banner/WelcomeBanner/Welcome35.tsx
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/members/upload/complete/CardBack.tsx
  src/pages/members/complete.tsx
Labels: ✨ Feature, size/M

#1592 feat: 광고 구좌 변경
  src/components/common/Banner/AdsBanner/constants/ads.ts
Labels: size/M

#1594 feat: 커피챗 오픈 뷰 헤더 구현
  src/components/coffeechat/mediaQuery.ts
  src/components/coffeechat/upload/UploadHeader/index.stories.tsx
  src/components/coffeechat/upload/UploadHeader/index.tsx
Labels: size/M

#1595 feat: 커피챗 입력 progress 박스 구현
  src/components/coffeechat/upload/ProgressBox/index.stories.tsx
  src/components/coffeechat/upload/ProgressBox/index.tsx
Labels: size/L

#1598 feat: 커피챗 업로드 폼 뷰 구현
  package.json
  src/components/coffeechat/mediaQuery.ts
  src/components/coffeechat/page/CoffeechatUploadPage.tsx
  src/components/coffeechat/upload/CoffeechatForm/ChipField/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/CoffeechatInfoForm/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/MyInfoForm/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/UploadButton/index.stories.tsx
  src/components/coffeechat/upload/CoffeechatForm/UploadButton/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/constants.ts
  src/components/coffeechat/upload/CoffeechatForm/index.stories.tsx
  src/components/coffeechat/upload/CoffeechatForm/index.tsx
  src/components/coffeechat/upload/CoffeechatForm/schema.ts
  src/components/coffeechat/upload/CoffeechatForm/types.ts
  src/components/common/form/FormTitle.tsx
  src/components/common/form/TextFieldLineBreak/index.stories.tsx
  src/components/common/form/TextFieldLineBreak/index.tsx
  yarn.lock
Labels: size/XL

#1599 feat: 커피챗 업로드 뷰 데스크탑, 모바일 레이아웃 구현
  src/components/coffeechat/page/CoffeechatUploadPage.tsx
  src/components/coffeechat/page/layout/DesktopCoffeechatUploadLayout.tsx
  src/components/coffeechat/page/layout/MobileCoffeechatUploadLayout.tsx
  src/components/coffeechat/upload/CoffeechatForm/UploadButton/index.tsx
  src/components/coffeechat/upload/ProgressBox/index.tsx
  src/components/common/form/TextFieldLineBreak/index.tsx
  src/pages/coffeechat/upload.tsx
Labels: size/L

#1603 feat: test/image 페이지 제작
  src/pages/test/image/index.tsx
Labels: size/M

#1607 feat: 10/27 광고 구좌 변경
  src/components/common/Banner/AdsBanner/AdsBox/index.tsx
  src/components/common/Banner/AdsBanner/constants/ads.ts
  src/components/common/Banner/AdsBanner/index.tsx
Labels: size/L

#1610 chore: 광고 구좌 변경
  src/components/common/Banner/AdsBanner/constants/ads.ts
Labels: size/XS

#1601 feat: 멤버 프로필, 상세 정보, 프로젝트, 모임 정보 컴포넌트 분리
  src/api/endpoint/members/getMemberCrew.ts
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/detail/CareerSection/index.tsx
  src/components/members/detail/DetailinfoSection/index.stories.tsx
  src/components/members/detail/DetailinfoSection/index.tsx
  src/components/members/detail/GroupSection/index.stories.tsx
  src/components/members/detail/GroupSection/index.tsx
  src/components/members/detail/MessageSection/index.tsx
  src/components/members/detail/ProfileSection/index.stories.tsx
  src/components/members/detail/ProfileSection/index.tsx
  src/components/members/detail/ProjectSection/index.stories.tsx
  src/components/members/detail/ProjectSection/index.tsx
Labels: size/XXL

#1619 feat: 커피챗 상세페이지 Dialog 구현
  public/icons/icon_coffeechat.svg
  src/api/endpoint_LEGACY/members/type.ts
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeChatModal/CoffeeChatCustomPortalModal.tsx
  src/components/coffeechat/CoffeeChatModal/CoffeeChatModal.tsx
  src/components/common/Modal/useCustomConfirm.tsx
  src/styles/mediaQuery.ts
Labels: size/L
