Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2024-03, with the labels that each got.

#1306 chore: 랜덤 리뷰어 4기 기준으로 변경
  .github/actions/randomReviewer.js
Labels: size/XS

#1307 chore: 플레이그라운드 4기 메이커 정보 반영
  README.md
Labels: size/M

#1305 fix: 최근 끝말잇기 limit 조정
  src/api/endpoint/wordchain/getWordchain.ts
Labels: size/XS

#1316 feat: 4기 정보 추가
  src/components/makers/data/generation4.ts
  src/components/makers/data/index.ts
Labels: size/L

#1309 feat: 활동 정보 확인 페이지 구현 (1)
  src/api/endpoint_LEGACY/members/type.ts
  src/components/members/CheckSoptActivity.tsx
  src/components/members/detail/MemberDetail.tsx
  src/components/members/detail/SoptActivitySection/index.stories.tsx
  src/components/members/detail/SoptActivitySection/index.tsx
  src/components/members/upload/FormSection/SoptActivity.tsx
  src/constants/links.ts
  src/pages/auth/callback/apple/register.tsx
  src/pages/auth/callback/google/register.tsx
  src/pages/members/checkSoptActivity.tsx
Labels: ✨ Feature, size/L

#1312 feat: 프로필 내 모임 무한스크롤 API 세팅
  .env.development
  src/api/endpoint/members/getMemberCrew.ts
  src/components/members/detail/MemberDetail.tsx
Labels: ✨ Feature, size/M

#1314 feat: 프로필 내 모임 UI 구현
  public/icons/img/meeting-mask.png
  src/components/common/Banner/Timer.tsx
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/detail/ActivitySection/MemberDetailSection.ts
  src/components/members/detail/ActivitySection/MemberMeetingCard.stories.tsx
  src/components/members/detail/ActivitySection/MemberMeetingCard.tsx
  src/components/members/detail/ActivitySection/MemberProjectCard.stories.tsx
  src/components/members/detail/ActivitySection/MemberProjectCard.tsx
  src/components/members/detail/ActivitySection/MemberProjectCardLegacy.tsx
  src/components/members/detail/CareerSection/index.tsx
  src/components/members/detail/InterestSection/index.tsx
  src/components/members/detail/MemberMeetingCard.tsx
  src/components/members/detail/MessageSection/index.tsx
  src/constants/links.ts
  src/hooks/useCountdown.tsx
  src/pages/members/[id].tsx
  src/utils/index.ts
  src/utils/parseDate.ts
Labels: ✨ Feature, size/L

#1315 feat: 프로필 개인 정보 마스킹
  src/api/endpoint/members/putMemberProfile.ts
  src/api/endpoint_LEGACY/members/type.ts
  src/components/common/Modal/useConfirm.tsx
  src/components/members/upload/FormSection/Basic/index.tsx
  src/components/members/upload/constants.ts
  src/components/members/upload/types.ts
  src/pages/members/edit.tsx
Labels: ✨ Feature, size/L

#1319 feat: 프로필 내 모임 기능 구현 완료
  src/api/endpoint/members/getMemberCrew.ts
  src/api/endpoint_LEGACY/hooks/members.ts
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/detail/ActivitySection/MemberMeetingCard.tsx
Labels: ✨ Feature, size/L

#1323 feat: 다짐메시지 모달
  src/api/endpoint/resolution/getResolutionValidation.ts
  src/api/endpoint/resolution/postResolution.ts
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/common/Modal/index.tsx
  src/components/common/Modal/parts/ModalButton.tsx
  src/components/common/Modal/parts/index.tsx
  src/components/common/Modal/useAlert.tsx
  src/components/common/Modal/useConfirm.tsx
  src/components/common/TextArea/index.tsx
  src/components/resolution/ResolutionModal.tsx
  src/components/resolution/useConfirmResolution.ts
Labels: ✨ Feature, size/L

#1329 feat: 데스크탑에서만 환영 배너 고정하기
  src/components/common/Banner/WelcomeBanner/index.tsx
Labels: size/M

#1333 chore: 배너 밑줄 수정
  playground-common/README.md
  playground-common/export.ts
  src/components/common/Banner/WelcomeBanner/index.tsx
Labels: size/S

#1326 feat: 프로필 등록 완료 페이지
  public/logos/now-sopt.svg
  src/components/resolution/CardBack.tsx
  src/components/resolution/MemberCardOfMe.tsx
  src/pages/members/complete.tsx
  src/pages/members/edit.tsx
  src/pages/members/upload.tsx
Labels: size/L

#1334 feat: 개인 정보 마스킹 API 수정 반영
  src/api/endpoint/members/putMemberProfile.ts
  src/api/endpoint_LEGACY/members/type.ts
  src/pages/members/edit.tsx
  src/pages/members/upload.tsx
Labels: size/M

#1337 feat: 프로필 등록 완료 페이지 cta에 다짐메시지 모달 로직 연결
  src/pages/members/complete.tsx
Labels: ✨ Feature, size/M

#1324 feat: 누락된 회원 정보 대응
  src/api/endpoint/members/getMemberOfMe.ts
  src/api/endpoint/members/putMemberActivityCheck.ts
  src/api/endpoint_LEGACY/members/type.ts
  src/components/common/Modal/parts/ModalButton.tsx
  src/components/common/Modal/parts/index.tsx
  src/components/members/detail/ActivitySection/MemberDetail.tsx
  src/components/members/detail/SoptActivitySection/index.stories.tsx
  src/components/members/detail/SoptActivitySection/index.tsx
  src/components/members/hooks/useRegisterModal.tsx
  src/components/members/upload/AddableItem.tsx
  src/components/members/upload/AddableWrapper.tsx
  src/components/members/upload/CheckActivity/CheckSoptActivity.tsx
  src/components/members/upload/CheckActivity/Modal/CheckActivityModal.tsx
  src/components/members/upload/CheckActivity/Modal/CheckModal.tsx
  src/components/members/upload/CheckActivity/Modal/CheckPopup.tsx
  src/components/members/upload/FormSection/SoptActivity.tsx
  src/components/members/upload/forms/FormHeader.tsx
  src/components/members/upload/forms/FormSection.ts
  src/constants/generation.ts
  src/constants/links.ts
  src/pages/auth/callback/apple/register.tsx
  src/pages/auth/callback/google/register.tsx
  src/pages/members/checkSoptActivity.tsx
  src/pages/members/edit.tsx
Labels: size/XL

#1318 feat: 뉴 - 프로젝트 리스트 카드 UI 적용
  src/api/endpoint_LEGACY/projects/index.ts
  src/api/endpoint_LEGACY/projects/type.ts
  src/components/projects/main/ProjectList.tsx
  src/components/projects/main/card/MobileProjectCard.stories.tsx
  src/components/projects/main/card/MobileProjectCard.tsx
  src/components/projects/main/card/ProjectCard.stories.tsx
  src/components/projects/main/card/ProjectCard.tsx
  src/components/projects/main/card/ProjectCardMemberList.tsx
  src/components/projects/main/card/ProjectCardStatus.tsx
Labels: size/XL

#1339 refactor: 다짐 메시지 모달 로직 개선 및 자잘한 UI 수정
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/common/Footer/index.tsx
  src/components/resolution/ResolutionModal.tsx
  src/components/resolution/useOpenResolutionModal.ts
  src/pages/members/complete.tsx
Labels: 🛠 Refactor, size/L

#1342 fix: 프로필 내 모임 카드 무한 스크롤 트리거 수정
  src/api/endpoint/members/getMemberCrew.ts
  src/components/members/detail/ActivitySection/MemberDetail.tsx
Labels: 🐛 Bug, size/XS

#1344 chore: 환영배너 스타일링 수정
  src/components/common/Banner/WelcomeBanner/index.tsx
Labels: size/S

#1350 feat: 다짐메시지 작성 후, 홈화면으로 랜딩
  public/icons/logo/time=34.svg
  src/components/resolution/useConfirmResolution.ts
Labels: size/S

#1352 feat: 프로필 등록이 안 되어있는 경우, 버튼 추가하기
  src/components/members/detail/EmptyProfile.tsx
Labels: size/XS

#1355 fix: 프로필 등록 완료 페이지 디테일 수정
  src/components/resolution/MemberCardOfMe.tsx
  src/pages/members/complete.tsx
Labels: 🐛 Bug, size/S

#1356 fix: 태그가 아주 많을 경우의 프로필 카드 수정
  src/components/members/main/MemberCard/index.tsx
  src/components/members/main/MemberList/index.tsx
Labels: size/XS

#1357 chore: 34기 로고 사이즈 조정
  public/icons/logo/time=34.svg
Labels: size/XS

#1360 chore: ux writing 수정
  src/components/members/upload/CheckActivity/CheckSoptActivity.tsx
Labels: size/S

#1362 fix: groupDetail link 변경
  src/constants/links.ts
Labels: 🐛 Bug, size/XS

#1364 fix: 모바일 프로필 상세 스타일링 수정
  src/components/members/detail/ActivitySection/MemberDetail.tsx
Labels: size/S

#1366 feat: 프로젝트 이미지 ResizedImage로 변경, 엑박 이미지 대응
  src/components/common/ResizedImage/index.tsx
  src/components/projects/main/card/MobileProjectCard.tsx
  src/components/projects/main/card/ProjectCard.tsx
  src/components/projects/main/card/ProjectCardMemberList.tsx
Labels: size/M

#1368 fix: 익명 여부 수정 모달 zIndex 수정
  src/components/feed/common/hooks/useBlindWriterPromise.tsx
Labels: 🐛 Bug, size/XS

#1370 chore: 프로젝트 검색창 layout shift 수정
  src/components/projects/main/ProjectList.tsx
Labels: size/XS

#1298 fix: 스토리북 에러 대응
  .storybook/preview.tsx
  src/components/feed/upload/Category/CategoryHeader/index.stories.tsx
  src/components/feed/upload/Category/CategorySelector/index.stories.tsx
  src/components/feed/upload/Category/TagSelector/index.stories.tsx
  src/components/feed/upload/Category/index.stories.tsx
Labels: size/L
