Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2025-09, with the labels that each got.

#1976 fix: 실시간 인기글 categoryId undefined에러 수정
  src/components/feed/common/utils.ts
  src/components/feed/home/PopularArea/index.tsx
  src/components/members/main/MemberList/index.tsx
Labels: size/M

#1986 Crew 모임 meetingId, meetingTitle 데이터 연결
  src/components/feed/list/CrewFeedList/CrewFeedListItem.tsx
Labels: size/XS

#1987 main << develop
  src/components/auth/AuthRequired.tsx
  src/components/feed/list/CrewFeedList/CrewFeedListItem.tsx
  src/components/members/main/MemberList/index.tsx
Labels: size/S

#1985 37기 타임캡솝 오픈
  public/icons/img/popup/MO.png
  public/icons/img/popup/PC.png
  public/logos/dive-sopt.svg
  src/components/auth/oauth/OAuthCallback.tsx
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/components/common/Banner/ClosingBanner/index.tsx
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/common/BottomSheet/ModalBottomSheet.tsx
  src/components/common/HomePopup/HomePopupContainer.tsx
  src/components/common/HomePopup/index.tsx
  src/components/luckydraw/LuckyReady.tsx
  src/components/luckydraw/LuckyResult.tsx
  src/components/luckydraw/LuckyWinnerGuide.tsx
  src/components/members/upload/complete/CardBack.tsx
  src/components/members/upload/complete/MemberCardOfMe.tsx
  src/components/resolution/submit/PlaygroundGuideModal.tsx
  src/components/resolution/submit/TimecapsopSubmitModalContent.tsx
  src/components/resolution/submit/constants/cards.tsx
  src/constants/generation.ts
  src/pages/index.tsx
  src/pages/members/complete.tsx
  src/styles/colors.ts
Labels: size/L

#1994 refactor: 멤버 필터링 초기화 추가
  src/components/members/main/MemberList/filters/constants.ts
  src/components/members/main/MemberList/index.tsx
Labels: size/S
