Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2025-04, with the labels that each got.

#1809 [FIX] 앰플리튜드 수정 작업
  src/components/coffeechat/CoffeeChatCard/index.tsx
  src/components/coffeechat/CoffeeChatCategory/index.tsx
  src/components/coffeechat/CoffeeChatModal/CoffeeChatModal.tsx
  src/components/coffeechat/CoffeeRecentChatList/index.tsx
  src/components/eventLogger/events.ts
  src/components/resolution/submit/TimecapsopSubmitModalContent.tsx
  src/pages/feed/[id].tsx
Labels: size/L

#1810 [Fix] 멤버, 프로젝트 앰플리튜드 수정 작업
  src/components/eventLogger/events.ts
  src/components/members/detail/MessageSection/MessageModal.tsx
  src/components/members/main/MemberCard/MessageButton.tsx
  src/components/members/main/MemberCard/index.tsx
  src/components/members/main/MemberList/index.tsx
  src/components/projects/main/ProjectCard.stories.tsx
  src/components/projects/main/ProjectCard.tsx
  src/components/projects/main/ProjectList.tsx
Labels: size/L

#1813 feat: 36기 메이커스 페이지 업데이트
  src/components/makers/Notifier.tsx
  src/components/makers/data/generation36.ts
  src/components/makers/data/index.ts
Labels: size/L

#1814 feat: 커뮤니티에 솝티클 컴포넌트 구현
  .storybook/main.ts
  src/components/feed/list/FeedUrlCard.stories.tsx
  src/components/feed/list/FeedUrlCard.tsx
Labels: size/L

#1819 feat: 타임캡솝 및 팝업 제거
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/pages/index.tsx
  src/pages/members/complete.tsx
Labels: size/XS

#1821 feat: readme 수정
  README.md
Labels: size/L

#1815 feat: 솝티클 툴팁 구현
  src/components/common/HomePopup/index.tsx
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/list/FeedCategoryTooltip/index.tsx
  src/components/feed/list/FeedCategoryTooltip/useTooltip.ts
Labels: size/L

#1817 feat: 솝티클 커뮤니티 api 작업
  public/icons/img/defalut_sopticle_thumbnail.png
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/feed/constants.ts
  src/components/feed/detail/DetailFeedCard.stories.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/list/FeedCard.stories.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/feed/list/FeedUrlCard.stories.tsx
  src/components/feed/list/FeedUrlCard.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
Labels: size/L

#1824 feat: 솝티클 업로드 UI
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategoryHeader/index.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/Category/TagSelector/TagSelectOptions.tsx
  src/components/feed/upload/CheckboxFormItem/BlindWriterWarning/index.tsx
  src/components/feed/upload/CodeUploadButton/index.tsx
  src/components/feed/upload/ImageUploadButton/index.tsx
  src/components/feed/upload/Input/LinkInput/index.tsx
  src/components/feed/upload/hooks/useLinkValidator.ts
  src/components/feed/upload/layout/MobileFeedUploadLayout.tsx
Labels: size/L

#1829 feat: 솝티클 업로드에서 활동후기 업로드로 헤더 변경
  playground-common/package.json
  src/components/common/Header/desktop/DesktopHeader.tsx
  src/components/common/Header/index.tsx
  src/components/common/Header/mobile/MobileSideBar.tsx
  src/components/eventLogger/events.ts
  src/constants/links.ts
Labels: size/S

#1832 feat: 활동후기 업로드 로깅 추가
  src/components/blog/Success.tsx
  src/components/eventLogger/events.ts
  src/pages/blog/index.tsx
Labels: size/S

#1834 fix: 솝티클 수정로직 변경
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Input/LinkInput/index.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
  src/components/feed/upload/types.ts
  src/pages/feed/edit/[id].tsx
  src/pages/feed/upload.tsx
Labels: size/M

#1830 feat: sp1관련 앰플리튜드 로깅 추가
  src/api/endpoint/members/getMemberProperty.ts
  src/components/eventLogger/controllers/amplitude.ts
  src/components/eventLogger/events.ts
  src/components/eventLogger/providers/AmplitudeProvider.tsx
  src/components/feed/common/utils.ts
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/feed/page/FeedHomePage.tsx
  src/pages/feed/upload.tsx
Labels: size/L
