Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2025-08, with the labels that each got.

#1926 feat: /accounts 경로 하위에서 인증중앙화 번들을 로드할 수 있도록 클라우드 플레어 pages functions 추가
  functions/accounts/[[path]].ts
Labels: size/XS

#1938 feat: token refresh in interceptor
  src/api/index.ts
  src/components/auth/AuthRequired.tsx
  src/components/auth/states/accessTokenAtom.ts
Labels: size/L

#1940 feat: fix redirect intro > accounts
  src/components/auth/AuthRequired.tsx
  src/components/auth/useAuth.ts
  src/constants/env.ts
  src/constants/links.ts
Labels: size/XS

#1942 fix: playground api credentials 삭제
  src/api/index.ts
Labels: size/XS

#1945 feat: 크루 api axios / .env setting
  .env.development
  src/api/index.ts
  src/constants/env.ts
Labels: size/M

#1947 fix: member 정보 관련 zod type 에러 수정
  src/api/endpoint/feed/getComment.ts
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/api/endpoint/feed/getRecentSopticle.ts
  src/constants/links.ts
Labels: size/M

#1951 feat: 서비스 점검 공지 홈팝업 등록
  public/icons/img/popup/MO.png
  public/icons/img/popup/PC.png
  src/components/common/HomePopup/HomePopupContainer.tsx
  src/components/common/HomePopup/index.tsx
  src/components/makers/data/makerInfo.ts
  src/pages/makers/index.tsx
Labels: size/XL

#1952 Crew 커뮤니티 통합 모임 피드 작성 추가 부분
  .env.development
  .gitignore
  src/api/index.ts
  src/components/feed/constants.ts
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/Category/index.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
  src/components/feed/upload/select/GroupSelect.tsx
  src/components/feed/upload/select/SelectMeetingOptionItem.tsx
  src/components/feed/upload/select/types.ts
  src/components/feed/upload/types.ts
  src/constants/env.ts
  src/constants/links.ts
Labels: size/XL

#1955 fix: 변경된 멤버 검색 request 반영
  src/components/members/main/MemberList/filters/constants.ts
  src/components/members/main/MemberList/index.tsx
Labels: size/M

#1957 fix: member activities 빈배열 처리
  src/components/members/main/MemberList/index.tsx
Labels: size/XS

#1959 deploy: dev to main
  .env.development
  functions/accounts/[[path]].ts
  playground-common/package.json
  src/api/endpoint/feed/getComment.ts
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/api/endpoint/feed/getRecentSopticle.ts
  src/api/index.ts
  src/components/auth/AuthRequired.tsx
  src/components/auth/states/accessTokenAtom.ts
  src/components/auth/useAuth.ts
  src/components/members/main/MemberList/filters/constants.ts
  src/components/members/main/MemberList/index.tsx
  src/constants/env.ts
  src/constants/links.ts
  src/pages/makers/index.tsx
Labels: size/L

#1960 fix: 인증중앙화, 플레이그라운드 링크 최신화
  src/constants/links.ts
Labels: size/XS

#1964 모임 피드 리스트 구현
  src/api/crew/CrewQueryKey.ts
  src/api/crew/getCrewPost.ts
  src/api/crew/toggleCrewPostLike.ts
  src/api/endpoint/feed/getPosts.ts
  src/components/feed/list/CrewFeedList/CrewFeedListItem.tsx
  src/components/feed/list/CrewFeedList/CrewMeetingLinkRow.tsx
  src/components/feed/list/CrewFeedList/index.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
  src/constants/links.ts
Labels: size/L

#1965 Crew 작업 -> 플그 병합
  .env.development
  .gitignore
  src/api/crew/CrewQueryKey.ts
  src/api/crew/getCrewPost.ts
  src/api/crew/getMeetingList.ts
  src/api/crew/postGroupFeed.ts
  src/api/crew/toggleCrewPostLike.ts
  src/api/endpoint/feed/getPosts.ts
  src/api/index.ts
  src/components/common/BottomSheet/index.tsx
  src/components/feed/constants.ts
  src/components/feed/list/CrewFeedList/CrewFeedListItem.tsx
  src/components/feed/list/CrewFeedList/CrewMeetingLinkRow.tsx
  src/components/feed/list/CrewFeedList/index.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/Category/index.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
  src/components/feed/upload/select/GroupSelect.tsx
  src/components/feed/upload/select/SelectMeetingOptionItem.tsx
  src/components/feed/upload/select/types.ts
  src/components/feed/upload/types.ts
  src/constants/env.ts
  src/constants/links.ts
Labels: size/XL

#1963 fix: development deploy브랜치 develop으로 변경
  .github/workflows/chromatic.yml
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
Labels: size/XS

#1969 크루 피드 리스트에 공유 링크 변경
  src/components/feed/list/CrewFeedList/CrewFeedListItem.tsx
Labels: size/S

#1971 fix: 플그 be 수정된 part 로직에 맞게 filter로 파트 정보 요청
  src/components/members/main/MemberList/filters/constants.ts
  src/components/members/main/MemberList/index.tsx
Labels: size/S
