Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2025-06, with the labels that each got.

#1869 fix: 커뮤니티 홈 모바일 인기글 카드 배치 수정
  src/components/feed/home/PopularArea/PopularCard.tsx
Labels: size/XS

#1877 fix: 파트톡, 홍보 카테고리의 좋아요 이슈
  src/components/feed/common/utils.ts
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/list/FeedListItems.tsx
Labels: size/M

#1875 feat: 플그 홈 배너 어드민 api 연결
  .env.development
  src/api/endpoint/homeBanner/getBannersImages.ts
  src/api/index.ts
  src/components/common/Banner/AdsBanner/AdsBox/index.tsx
  src/components/common/Banner/AdsBanner/constants/ads.ts
  src/components/common/Banner/AdsBanner/index.tsx
  src/constants/env.ts
Labels: size/L

#1881 feat: 투표 조회 및 선택 구현
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/api/endpoint/feed/postVote.ts
  src/components/feed/detail/DetailFeedCard.stories.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/vote/RadioBox.tsx
  src/components/vote/index.stories.tsx
  src/components/vote/index.tsx
Labels: size/XL
