Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2025-02, with the labels that each got.

#1740 feat: 마이 솝트 리포트 구현
  functions/mySoptReport/index.ts
  package.json
  public/logos/img_calendar.svg
  public/logos/img_coffeechat.svg
  public/logos/img_community.svg
  public/logos/img_confetti.svg
  public/logos/img_member.svg
  public/logos/img_service.svg
  public/logos/my-sopt-report.svg
  src/api/endpoint/mySoptReport/getReportData.ts
  src/components/mySoptReport/MyPG/index.tsx
  src/components/mySoptReport/Playground/CoffeeSopt/index.tsx
  src/components/mySoptReport/Playground/Community/index.tsx
  src/components/mySoptReport/Playground/MBTI/index.tsx
  src/components/mySoptReport/Playground/MeetingStudy/index.tsx
  src/components/mySoptReport/Playground/index.tsx
  src/components/mySoptReport/ReportNav/index.stories.tsx
  src/components/mySoptReport/ReportNav/index.tsx
  src/components/mySoptReport/Sopt/PopularMeetingSpotRank/index.tsx
  src/components/mySoptReport/Sopt/ServiceCategoryRankBox/index.tsx
  src/components/mySoptReport/Sopt/index.tsx
  src/components/mySoptReport/common/LabelButton/index.tsx
  src/components/mySoptReport/common/ReportCard/index.tsx
  src/components/mySoptReport/common/ReportTitle/ReportText.tsx
  src/components/mySoptReport/common/ReportTitle/index.stories.tsx
  src/components/mySoptReport/common/ReportTitle/index.tsx
  src/components/mySoptReport/common/Tooltip/index.tsx
  src/components/mySoptReport/constants.ts
  src/components/mySoptReport/index.tsx
  src/components/mySoptReport/types.ts
  src/pages/mySoptReport/index.tsx
  yarn.lock
Labels: size/XXL

#1750 feat: 마솝리 QA 반영
  public/logos/mysoptreport-pc-1.svg
  public/logos/mysoptreport-pc-2.svg
  public/logos/mysoptreport-pc.svg
  src/api/endpoint/members/getMemberProperty.ts
  src/api/endpoint/mySoptReport/getReportData.ts
  src/components/eventLogger/events.ts
  src/components/eventLogger/providers/AmplitudeProvider.tsx
  src/components/mySoptReport/MyPG/index.tsx
  src/components/mySoptReport/Playground/CoffeeSopt/index.tsx
  src/components/mySoptReport/Playground/Community/index.tsx
  src/components/mySoptReport/Playground/MBTI/index.tsx
  src/components/mySoptReport/Playground/MeetingStudy/index.tsx
  src/components/mySoptReport/Playground/index.tsx
  src/components/mySoptReport/ReportNav/index.tsx
  src/components/mySoptReport/Sopt/PopularMeetingSpotRank/index.tsx
  src/components/mySoptReport/Sopt/ServiceCategoryRankBox/index.tsx
  src/components/mySoptReport/Sopt/index.tsx
  src/components/mySoptReport/common/LabelButton/index.tsx
  src/components/mySoptReport/common/ReportTitle/ReportText.tsx
  src/components/mySoptReport/common/ReportTitle/index.tsx
  src/components/mySoptReport/index.tsx
  src/components/mySoptReport/types.ts
Labels: size/XL

#1751 Feat: 마이솝트리포트 마이 플그 데이터 구현
  package.json
  public/icons/img/mySoptReport/card_coffeechat_type.png
  public/icons/img/mySoptReport/card_exsopt_type.png
  public/icons/img/mySoptReport/card_icon.svg
  public/icons/img/mySoptReport/card_new_type.png
  public/icons/img/mySoptReport/card_pg_type.png
  public/icons/img/mySoptReport/card_sokedin_type.png
  public/icons/img/mySoptReport/card_sopgosu_type.png
  public/icons/img/mySoptReport/card_sopmanchu_type.png
  public/icons/img/mySoptReport/card_sub_click.png
  public/icons/img/mySoptReport/card_sub_like.png
  public/icons/img/mySoptReport/card_sub_visit.png
  public/icons/img/mySoptReport/collect_bg.png
  public/icons/img/mySoptReport/game_off.png
  public/icons/img/mySoptReport/game_on.png
  public/icons/img/mySoptReport/heart_off.png
  public/icons/img/mySoptReport/heart_on.png
  public/icons/img/mySoptReport/img_coffeechat.png
  public/icons/img/mySoptReport/img_coffeechat@3x.png
  public/icons/img/mySoptReport/img_community.png
  public/icons/img/mySoptReport/img_community@3x.png
  public/icons/img/mySoptReport/img_group.png
  public/icons/img/mySoptReport/img_group@3x.png
  public/icons/img/mySoptReport/img_member.png
  public/icons/img/mySoptReport/img_member@3x.png
  public/icons/img/mySoptReport/img_new.png
  public/icons/img/mySoptReport/img_new@3x.png
  public/icons/img/mySoptReport/img_project.png
  public/icons/img/mySoptReport/img_project@3x.png
  public/icons/img/mySoptReport/img_wordchain.png
  public/icons/img/mySoptReport/img_wordchain@3x.png
  public/icons/img/mySoptReport/particle_mo.png
  public/icons/img/mySoptReport/particle_pc.png
  public/icons/img/mySoptReport/particle_ta.png
  public/icons/img/mySoptReport/person_off.png
  public/icons/img/mySoptReport/person_on.png
  public/icons/img/mySoptReport/search_off.png
  public/icons/img/mySoptReport/search_on.png
  public/icons/img/mySoptReport/study_off.png
  public/icons/img/mySoptReport/study_on.png
  public/icons/img/mySoptReport/time_off.png
  public/icons/img/mySoptReport/time_on.png
  src/api/endpoint/mySoptReport/getMyPGData.ts
  src/components/mySoptReport/MiniReportCard/index.tsx
  src/components/mySoptReport/MyPG/index.tsx
  src/components/mySoptReport/MyReport/index.tsx
  src/components/mySoptReport/PopUp/index.tsx
  src/components/mySoptReport/ReportCard/CardHeader/index.tsx
  src/components/mySoptReport/ReportCard/MyDataCard/index.tsx
  src/components/mySoptReport/ReportCard/MyTypeCard/index.tsx
  src/components/mySoptReport/ReportCard/index.tsx
  src/components/mySoptReport/constants.ts
  src/components/mySoptReport/index.tsx
  tsconfig.json
  yarn.lock
Labels: size/XXL

#1752 Fix: 이미지 저장시 bg url 변경
  src/components/mySoptReport/MyReport/index.tsx
  src/components/mySoptReport/ReportCard/CardHeader/index.tsx
  src/components/mySoptReport/index.tsx
Labels: size/M

#1754 feat: 종무식 배너에 마이 솝트 리포트 진입점 연결
  src/components/common/Banner/ClosingCeremonyBanner/index.tsx
Labels: size/S

#1755 hotfix: 카드 보이지 않게 변경
  src/components/mySoptReport/MyReport/index.tsx
Labels: size/XS

#1756 hotfix: winCount 변경
  src/components/mySoptReport/MiniReportCard/index.tsx
Labels: size/XS

#1758 fix: 마이 솝트 리포트 배너 이미지 변경
  public/icons/img/banner_my-sopt-report_mobile.png
  src/components/common/Banner/ClosingCeremonyBanner/index.tsx
Labels: size/M

#1760 feat: 마이 솝트 리포트 오픈 예정 팝업 되돌리기
  src/components/common/Banner/ClosingCeremonyBanner/index.tsx
Labels: size/M

#1762 feat: mySoptReport 진입점 오픈
  src/components/common/Banner/ClosingCeremonyBanner/index.tsx
Labels: size/M

#1763 hotfix: 마이 플그 활동 유형 IOS에서 다운되지 않는 오류 수정
  src/components/mySoptReport/ReportCard/CardHeader/index.tsx
Labels: size/S

#1717 feat: 멤버 프로필 등록/수정 mds 적용
  src/components/coffeechat/upload/CoffeechatForm/BottomSheetSelect/index.tsx
  src/components/common/EditableSelect.stories.tsx
  src/components/common/ImageUploader/index.tsx
  src/components/common/Modal/useConfirm.tsx
  src/components/common/MonthPicker.tsx
  src/components/members/upload/AddableItem.tsx
  src/components/members/upload/AddableWrapper.tsx
  src/components/members/upload/CheckActivity/CheckSoptActivity.tsx
  src/components/members/upload/FormSection/Basic/index.tsx
  src/components/members/upload/FormSection/Career.tsx
  src/components/members/upload/FormSection/SoptActivity.tsx
  src/components/members/upload/FormSection/Tmi/FavorToggle.tsx
  src/components/members/upload/FormSection/Tmi/MbtiSelector.tsx
  src/components/members/upload/FormSection/Tmi/MbtiToggle.tsx
  src/components/members/upload/FormSection/Tmi/index.tsx
  src/components/members/upload/constants.ts
  src/components/members/upload/format.ts
  src/components/members/upload/forms/Form.tsx
  src/components/members/upload/forms/FormHeader.tsx
  src/components/members/upload/forms/FormItem.tsx
  src/components/members/upload/forms/FormSection.ts
  src/components/members/upload/forms/Select.tsx
  src/components/members/upload/schema.ts
  src/components/members/upload/types.ts
  src/pages/members/edit.tsx
  src/pages/members/upload.tsx
Labels: size/XXL

#1765 feat: 홈 팝업 컨텐츠 변경
  public/icons/img/SoptReport/popup/MO.png
  public/icons/img/SoptReport/popup/PC.png
  src/components/common/HomePopup.tsx
Labels: size/XS

#1766 hotfix: 인스타그램 스토리 이미지 업로드 오류 해결
  src/components/mySoptReport/MiniReportCard/index.tsx
  src/components/mySoptReport/ReportCard/CardHeader/index.tsx
  src/components/mySoptReport/ReportCard/MyDataCard/index.tsx
  src/components/mySoptReport/constants.ts
Labels: size/M

#1767 hotfix: 사진 재 수정 반영
  public/icons/img/SoptReport/popup/MO.png
  public/icons/img/SoptReport/popup/PC.png
Labels: size/XS

#1771 feat: mySoptReport 배너 내리기
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/components/common/Banner/AdsBanner/constants/ads.ts
Labels: size/S
