Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2025-03, with the labels that each got.

#1775 chore: 랜덤 리뷰어 리스트 36기 기준으로 변경
  .github/actions/randomReviewer.js
Labels: size/XS

#1778 feat: 타입캡솝 생성 모달
  public/icons/icon-cooperation-default.svg
  public/icons/icon-cooperation-hover.svg
  public/icons/icon-cooperation-select.svg
  public/icons/icon-modal-close.svg
  public/icons/icon-networking-default.svg
  public/icons/icon-networking-hover.svg
  public/icons/icon-networking-select.svg
  public/icons/icon-release-default.svg
  public/icons/icon-release-hover.svg
  public/icons/icon-release-select.svg
  public/icons/icon-skill-default.svg
  public/icons/icon-skill-hover.svg
  public/icons/icon-skill-select.svg
  public/icons/icon-startup-default.svg
  public/icons/icon-startup-hover.svg
  public/icons/icon-startup-select.svg
  src/api/endpoint/resolution/postResolution.ts
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/components/common/Banner/WelcomeBanner/WelcomeBannerContainer.tsx
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/resolution/constants.ts
  src/components/resolution/submit/ResolutionSubmitModal.tsx
  src/components/resolution/submit/TimecapsopSubmitModal.tsx
  src/components/resolution/submit/useOpenResolutionModal.ts
  src/constants/generation.ts
  src/pages/members/complete.tsx
Labels: size/XXL

#1781 feat: 36기 YB 환영카드
  package.json
  public/logos/and-sopt.svg
  public/logos/at-sopt.svg
  public/logos/now-sopt.svg
  src/components/members/upload/complete/CardBack.tsx
  src/components/members/upload/complete/MemberCardOfMe.tsx
  src/pages/members/complete.tsx
  yarn.lock
Labels: size/L

#1784 feat: 다른 기능 이동 모달
  public/logos/playgroundGuide/img_coffee.svg
  public/logos/playgroundGuide/img_group.svg
  public/logos/playgroundGuide/img_member.svg
  public/logos/playgroundGuide/img_project.svg
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/resolution/submit/PlaygroundGuideModal.tsx
  src/components/resolution/submit/TimecapsopSubmitModal.tsx
  src/components/resolution/submit/constants/cards.tsx
  src/components/resolution/submit/useOpenResolutionModal.ts
  src/pages/members/complete.tsx
Labels: size/L

#1789 fix: 빌드 에러 해결 및 가이드 모달 추가
  src/components/common/HomePopup/index.tsx
Labels: size/M

#1790 fix: 타임캡솝 QA 반영
  src/api/endpoint/resolution/deleteTimecapsop.ts
  src/api/endpoint/resolution/postResolution.ts
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/common/BottomSheet/ModalBottomSheet.tsx
  src/components/common/HomePopup/index.tsx
  src/components/resolution/constants.ts
  src/components/resolution/delete/index.tsx
  src/components/resolution/submit/PlaygroundGuideModal.tsx
  src/components/resolution/submit/TimecapsopSubmitModal.tsx
  src/components/resolution/submit/TimecapsopSubmitModalContent.tsx
  src/components/resolution/submit/useConfirmResolution.ts
  src/pages/members/complete.tsx
Labels: size/XL

#1793 fix: 다른 기능 이동 모달 QA 반영
  public/logos/playgroundGuide/img_group.svg
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/common/BottomSheet/ModalBottomSheet.tsx
  src/components/common/HomePopup/index.tsx
  src/components/resolution/submit/PlaygroundGuideModal.tsx
  src/pages/members/complete.tsx
Labels: size/M

#1798 feat: 다른기능이동 모달 클릭 이벤트 로깅
  src/components/eventLogger/events.ts
  src/components/resolution/submit/PlaygroundGuideModal.tsx
  src/components/resolution/submit/TimecapsopSubmitModalContent.tsx
  src/components/resolution/submit/constants/cards.tsx
Labels: size/M

#1797 feat: 타임캡솝 amplitude 이벤트 등록
  src/components/common/Banner/WelcomeBanner/index.tsx
  src/components/eventLogger/events.ts
  src/components/resolution/submit/TimecapsopSubmitModalContent.tsx
  src/components/resolution/submit/useConfirmResolution.ts
  src/pages/members/complete.tsx
Labels: size/S

#1802 hotfix: 36기 로고 크기 수정
  public/icons/logo/time=36.svg
Labels: size/XS
