Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2025-01, with the labels that each got.

#1722 fix: bottomsheetselect를 portal로 렌더링
  src/components/coffeechat/upload/CoffeechatForm/BottomSheetSelect/index.tsx
Labels: 🐛 Bug, size/XS

#1725 fix: 이미지 다운로드 테스트용 페이지 모바일에서 안뜨는 현상 해결
  src/components/resolution/read/hooks/useImageDownload.ts
  src/pages/test/image/index.tsx
Labels: 🐛 Bug, size/M

#1719 feat: 커피챗 상세 default 이미지 mds 적용
  src/components/coffeechat/detail/OpenerProfile/index.tsx
Labels: ✨ Feature, size/S

#1727 feat: Home Ads Popup 구현
  public/icons/img/crew_home_popup_mo.png
  public/icons/img/crew_home_popup_pc.png
  public/icons/img/home-popup-sample.png
  src/components/common/HomePopup.tsx
  src/components/eventLogger/events.ts
  src/pages/index.tsx
Labels: size/L

#1737 hotfix: 36기 모집글 등록
  src/components/common/HomePopup.tsx
  src/components/makers/Notifier.tsx
  src/components/makers/data/generation35.ts
Labels: size/S

#1739 feat: 메뉴 탭 바 구현
  package.json
  src/components/mySoptReport/ReportNav/index.stories.tsx
  src/components/mySoptReport/ReportNav/index.tsx
  src/components/mySoptReport/constants.ts
  src/components/mySoptReport/hooks/useIntersectionObserver.ts
  src/components/mySoptReport/index.tsx
  src/pages/mySoptReport/index.tsx
  yarn.lock
Labels: size/L

#1735 feat: 마이 솝트 리포트 솝트, 플레이그라운드 구현
  src/components/mySoptReport/Playground/CoffeeSopt/index.tsx
  src/components/mySoptReport/Playground/Community/index.tsx
  src/components/mySoptReport/Playground/MBTI/index.tsx
  src/components/mySoptReport/Playground/MeetingStudy/index.tsx
  src/components/mySoptReport/Playground/index.tsx
  src/components/mySoptReport/Sopt/PopularMeetingSpotRank/index.tsx
  src/components/mySoptReport/Sopt/ServiceCategoryRankBox/index.tsx
  src/components/mySoptReport/Sopt/index.tsx
  src/components/mySoptReport/common/LabelButton/index.tsx
  src/components/mySoptReport/common/ReportCard/index.tsx
  src/components/mySoptReport/common/ReportTitle/ReportText.tsx
  src/components/mySoptReport/common/ReportTitle/index.stories.tsx
  src/components/mySoptReport/common/ReportTitle/index.tsx
  src/components/mySoptReport/common/Tooltip/index.tsx
  src/components/mySoptReport/index.tsx
  src/components/mySoptReport/types.ts
Labels: size/XXL

#1741 feat: 커피챗 리뷰 작성 페이지 구현
  .github/workflows/build.yml
  .github/workflows/deploy-development.yml
  .github/workflows/deploy-production.yml
  package.json
  src/api/endpoint/coffeechat/getCoffeechatHistory.ts
  src/api/endpoint/coffeechat/postCoffeechatReview.ts
  src/components/coffeechat/CoffeeChatCategory/index.tsx
  src/components/coffeechat/CoffeeChatReveiw/BottomSheetMDS.tsx
  src/components/eventLogger/events.ts
  src/pages/coffeechat/review.tsx
  yarn.lock
Labels: size/XL

#1745 fix: 커피챗 리뷰 등록 qa 적용
  src/components/coffeechat/CoffeeChatReview/CoffeeChatReviewCard.tsx
  src/components/coffeechat/CoffeeChatReview/CoffeeChatReviewModal.tsx
Labels: size/S
