Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2025-05, with the labels that each got.

#1836 feat: 커뮤니티 리서치 홍보 팝업 추가
  public/icons/img/community_research_desktop.png
  public/icons/img/community_research_mobile.png
  src/components/common/HomePopup/index.tsx
  src/pages/index.tsx
Labels: size/M

#1838 fix: 최신 기수 얼리 리턴 해제
  src/components/common/HomePopup/HomePopupContainer.tsx
Labels: size/XS

#1840 feat: 커뮤니티 리서치 팝업 asest 변경
  public/icons/img/community_research_desktop.png
  public/icons/img/community_research_mobile.png
Labels: size/XS

#1842 feat: 홈팝업 제거
  src/components/common/HomePopup/HomePopupContainer.tsx
  src/pages/index.tsx
Labels: size/XS

#1844 fix: 모바일 프로필 수정 input 디자인 오류 해결
  src/components/members/upload/FormSection/Basic/index.tsx
  src/components/members/upload/FormSection/Career.tsx
Labels: size/M

#1852 feat: 크루팀 리서치 홈 팝업 적용
  public/icons/img/popup/crew-homepopup-desktop.png
  public/icons/img/popup/crew-homepopup-mobile.png
  src/components/common/HomePopup/HomePopupContainer.tsx
  src/components/common/HomePopup/index.tsx
  src/pages/index.tsx
Labels: size/S

#1856 feat: 커뮤니티 홈 페이지 레이아웃 및 탭 구현
  public/icons/icon_fire.svg
  src/api/endpoint/feed/getPosts.ts
  src/components/feed/home/PopularArea/PopularCard.stories.tsx
  src/components/feed/home/PopularArea/PopularCard.tsx
  src/components/feed/home/PopularArea/index.tsx
  src/components/feed/home/index.tsx
  src/components/feed/list/CategorySelect.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/list/FeedListItems.tsx
Labels: size/M

#1859 feat: 게시물 카드 디자인 수정 작업
  src/components/feed/common/FeedLike.tsx
  src/components/feed/common/Icon.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/home/QuestionArea/QuestionCard.tsx
  src/components/feed/home/QuestionArea/index.tsx
  src/components/feed/home/SopticleArea/index.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/feed/list/FeedSkeleton.tsx
Labels: size/L

#1860 feat: 커뮤니티 업로드 개선
  src/components/common/Checkbox/index.tsx
  src/components/feed/constants.ts
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Category/CategoryHeader/index.tsx
  src/components/feed/upload/Category/CategorySelector/CategorySelectOptions.tsx
  src/components/feed/upload/Category/CategorySelector/index.tsx
  src/components/feed/upload/Category/DropDown/index.tsx
  src/components/feed/upload/Category/TagSelector/TagSelectOptions.tsx
  src/components/feed/upload/Category/TagSelector/index.tsx
  src/components/feed/upload/Category/index.tsx
  src/components/feed/upload/CheckboxFormItem/BlindWriterWarning/index.tsx
  src/components/feed/upload/CheckboxFormItem/index.tsx
  src/components/feed/upload/ImagePreview/index.tsx
  src/components/feed/upload/ImageUploadButton/index.tsx
  src/components/feed/upload/Input/ContentsInput/index.tsx
  src/components/feed/upload/Input/TitleInput/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesButton/index.tsx
  src/components/feed/upload/UsingRules/UsingRulesPreview/index.tsx
  src/components/feed/upload/UsingRules/index.tsx
  src/components/feed/upload/hooks/useUploadFeedData.ts
  src/components/feed/upload/layout/DesktopFeedUploadLayout.tsx
  src/components/feed/upload/layout/MobileFeedUploadLayout.tsx
  src/components/feed/upload/layout/provider/FooterHeightProvider.tsx
  src/components/feed/upload/types.ts
Labels: size/XL

#1867 fix: 닉네임 말줄임표 추가
  src/components/feed/home/PopularArea/PopularCard.tsx
  src/components/feed/home/PopularArea/index.tsx
  src/components/feed/home/QuestionArea/index.tsx
  src/components/feed/home/SopticleArea/index.tsx
Labels: size/S
