Repository sopt-makers/sopt-playground-frontend, pull requests merged in 2025-07, with the labels that each got.

#1883 feat: 투표 수정 막기 로직 구현
  src/api/endpoint/feed/postVote.ts
  src/components/feed/common/hooks/useDeleteFeed.ts
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/list/FeedList.tsx
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/votePreview/index.stories.tsx
  src/components/feed/upload/votePreview/index.tsx
  src/components/vote/RadioBox.tsx
  src/components/vote/index.tsx
  src/pages/feed/edit/[id].tsx
Labels: size/L

#1891 fix: sp3 qa반영
  src/components/feed/page/FeedUploadPage.tsx
Labels: size/M

#1888 feat: 홈피드 ui 개편
  public/icons/icon-vote.svg
  src/api/endpoint/feed/getRecentPosts.ts
  src/api/endpoint/feed/getWaitingQuestions.ts
  src/api/endpoint/feed/postComment.ts
  src/api/endpoint/feed/postLike.ts
  src/api/endpoint/feed/postVote.ts
  src/components/eventLogger/events.ts
  src/components/feed/common/hooks/useDeleteComment.ts
  src/components/feed/common/hooks/useDeleteFeed.ts
  src/components/feed/common/hooks/useToggleLike.ts
  src/components/feed/common/utils.ts
  src/components/feed/detail/FeedDetailContent.tsx
  src/components/feed/home/PopularArea/PopularCard.tsx
  src/components/feed/home/PopularArea/index.tsx
  src/components/feed/home/RecentArea/FeedIcon.tsx
  src/components/feed/home/RecentArea/RecentCard.stories.tsx
  src/components/feed/home/RecentArea/RecentCard.tsx
  src/components/feed/home/RecentArea/index.tsx
  src/components/feed/home/index.tsx
  src/components/feed/list/FeedListItems.tsx
  src/components/vote/index.tsx
  src/pages/feed/edit/[id].tsx
  src/pages/feed/upload.tsx
Labels: size/L

#1893 feat: 요리배틀 마케팅 홈 팝업 기간 설정
  public/icons/img/popup/cook-desktop.png
  public/icons/img/popup/cook-mobile.png
  public/icons/img/popup/crew-homepopup-desktop.png
  public/icons/img/popup/crew-homepopup-mobile.png
  src/components/common/HomePopup/HomePopupContainer.tsx
  src/components/common/HomePopup/index.tsx
Labels: size/S

#1886 feat: 커뮤니티 유저 언급 기능 구현
  package.json
  src/components/eventLogger/events.ts
  src/components/feed/common/MentionDropdown.tsx
  src/components/feed/common/hooks/useCursorPosition.ts
  src/components/feed/common/hooks/useMention.ts
  src/components/feed/common/utils/parseMention.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/detail/FeedDetailInput.tsx
  src/components/feed/home/RecentArea/RecentCard.tsx
  src/components/feed/list/FeedCard.tsx
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/Input/ContentsInput/index.tsx
  src/components/projects/upload/hooks/useGetMembersByNameQuery.ts
  src/pages/feed/upload.tsx
  src/utils/parseTextToLink.tsx
  yarn.lock
Labels: size/XL

#1895 fix: 커뮤니티 언급 필드 누락 해결
  src/api/endpoint/feed/postComment.ts
  src/components/common/HomePopup/index.tsx
  src/components/feed/common/MentionDropdown.tsx
  src/components/feed/common/utils/parseMention.tsx
  src/components/feed/detail/FeedDetailInput.tsx
  src/components/feed/home/PopularArea/PopularCard.tsx
  src/components/feed/page/FeedUploadPage.tsx
  src/components/feed/upload/types.ts
  src/pages/feed/edit/[id].tsx
  src/pages/feed/upload.tsx
Labels: size/M

#1897 fix: 언급 알림 정보 필드 추가
  src/components/feed/detail/FeedDetailInput.tsx
  src/components/feed/page/FeedUploadPage.tsx
Labels: size/XS

#1899 fix: 게시글 생성 시 익명 상태 관리 수정
  src/components/feed/upload/hooks/useUploadFeedData.ts
Labels: size/XS

#1901 feat: 홈 팝업 광고 리프레시 데이 이벤트 추가
  public/icons/img/community_research_desktop.png
  public/icons/img/community_research_mobile.png
  public/icons/img/crew_home_popup_mo.png
  public/icons/img/crew_home_popup_pc.png
  public/icons/img/popup/MO.png
  public/icons/img/popup/PC.png
  public/icons/img/popup/cook-desktop.png
  public/icons/img/popup/cook-mobile.png
  src/components/common/HomePopup/HomePopupContainer.tsx
  src/components/common/HomePopup/index.tsx
  src/components/feed/home/PopularArea/PopularCard.tsx
Labels: size/S

#1903 feat: 멘션 기능 처리 추가
  src/components/feed/common/utils/parseMention.tsx
  src/components/feed/detail/DetailFeedCard.tsx
  src/components/feed/home/RecentArea/RecentCard.tsx
  src/components/feed/list/FeedCard.tsx
Labels: size/M

#1911 feat: 타임캡솝 조회
  public/icons/img/banner_closing_desktop.jpg
  public/icons/img/banner_closing_mobile.jpg
  public/icons/img/popup/MO.png
  public/icons/img/popup/PC.png
  public/icons/img/resolution/resolutionBG.png
  src/api/endpoint/resolution/getResolution.ts
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/components/common/Banner/ClosingBanner/index.tsx
  src/components/common/HomePopup/HomePopupContainer.tsx
  src/components/common/HomePopup/index.tsx
  src/components/debug/Debugger.tsx
  src/components/eventLogger/events.ts
  src/components/resolution/read/ResolutionMessage.tsx
  src/components/resolution/read/ResolutionReadModal.tsx
  src/pages/index.tsx
Labels: size/XL

#1908 feat: 행운뽑기 기능 추가
  functions/lucky/index.ts
  package.json
  public/icons/img/luckyDraw/LoserImage.png
  public/icons/img/luckyDraw/WinnerImage.png
  public/icons/img/luckyDraw/ready.png
  public/icons/img/luckyDraw/result_desktop.png
  public/icons/img/luckyDraw/result_mobile.png
  public/lottie/lucky.lottie
  react-app-env.d.ts
  src/api/endpoint/resolution/getLuckyPick.ts
  src/components/eventLogger/events.ts
  src/components/luckydraw/LottiePlayer.tsx
  src/components/luckydraw/LuckyLoading.tsx
  src/components/luckydraw/LuckyReady.tsx
  src/components/luckydraw/LuckyResult.tsx
  src/components/luckydraw/LuckyWinnerGuide.tsx
  src/pages/lucky/index.tsx
  yarn.lock
Labels: size/XXL

#1918 Revert "fix: 커뮤니티 조회 멤버 필드 타입 검증 수정"
  src/api/endpoint/feed/getComment.ts
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/api/endpoint/feed/getRecentSopticle.ts
Labels: size/S

#1923 refactor: 행운뽑기 여부 캐시 업데이트 순서 변경
  src/api/endpoint/resolution/getResolution.ts
  src/components/resolution/read/ResolutionReadModal.tsx
  src/pages/lucky/index.tsx
Labels: size/M

#1922 fix: 저용량 이미지로 변경
  public/icons/img/luckyDraw/LoserImage.png
  public/icons/img/luckyDraw/WinnerImage.png
  public/icons/img/luckyDraw/ready.png
  public/icons/img/luckyDraw/result_desktop.png
  public/icons/img/luckyDraw/result_mobile.png
Labels: size/XS

#1924 Revert "Revert "fix: 커뮤니티 조회 멤버 필드 타입 검증 수정""
  src/api/endpoint/feed/getComment.ts
  src/api/endpoint/feed/getPost.ts
  src/api/endpoint/feed/getPosts.ts
  src/api/endpoint/feed/getRecentSopticle.ts
Labels: size/S

#1929 feat: 타임캡솝 이벤트 종료
  src/components/common/Banner/ActiveBannerSlot.tsx
  src/components/common/HomePopup/HomePopupContainer.tsx
  src/components/common/HomePopup/index.tsx
Labels: size/M
